// Owner Console strings (AR/EN), merged into LangContext's TRANSLATIONS.
import { OUTREACH_TRANSLATIONS } from './outreach/outreachStrings'

export const OWNER_TRANSLATIONS: Record<string, { EN: string; AR: string }> = {
  // Shell
  'owner.brand': { EN: 'Platform Owner', AR: 'مالك المنصة' },
  'owner.console': { EN: 'Owner Console', AR: 'وحدة تحكم المالك' },
  'owner.band': { EN: 'PLATFORM OWNER CONSOLE · actions here apply across tenants and are audited', AR: 'وحدة تحكم مالك المنصة · الإجراءات هنا تشمل جميع الجهات وتخضع للتدقيق' },
  'owner.nav.dashboard': { EN: 'Dashboard', AR: 'لوحة المعلومات' },
  'owner.nav.tenants': { EN: 'Tenants', AR: 'الجهات' },
  'owner.nav.audit': { EN: 'Audit', AR: 'سجل التدقيق' },
  'owner.nav.settings': { EN: 'Settings', AR: 'الإعدادات' },
  'owner.nav.demo': { EN: 'Demo requests', AR: 'طلبات العرض التوضيحي' },
  'owner.demo.title': { EN: 'Demo requests', AR: 'طلبات العرض التوضيحي' },
  'owner.demo.help': { EN: 'Requests sent from the public ArchMind website asking for a product demo. Only platform owners can see them; tenant administrators cannot.', AR: 'الطلبات المرسلة من موقع ArchMind العام لطلب عرض توضيحي للمنتج. يطّلع عليها مالكو المنصة فقط، ولا يراها مسؤولو الجهات.' },
  'owner.demo.count': { EN: '{n} requests, newest first', AR: '{n} طلبًا، الأحدث أولًا' },
  'owner.demo.refresh': { EN: 'Refresh', AR: 'تحديث' },
  'owner.demo.empty': { EN: 'No demo requests yet.', AR: 'لا توجد طلبات عرض توضيحي بعد.' },
  'owner.demo.search': { EN: 'Search', AR: 'بحث' },
  'owner.demo.col.date': { EN: 'Submitted', AR: 'تاريخ الإرسال' },
  'owner.demo.col.name': { EN: 'Name', AR: 'الاسم' },
  'owner.demo.col.organization': { EN: 'Organization', AR: 'الجهة' },
  'owner.demo.col.job': { EN: 'Job title', AR: 'المسمى الوظيفي' },
  'owner.demo.col.email': { EN: 'Email', AR: 'البريد الإلكتروني' },
  'owner.demo.col.phone': { EN: 'Phone', AR: 'الهاتف' },
  'owner.demo.col.country': { EN: 'Country', AR: 'الدولة' },
  'owner.demo.col.language': { EN: 'Language', AR: 'اللغة' },
  'owner.demo.col.message': { EN: 'Message', AR: 'الرسالة' },
  'owner.nav.workspace': { EN: 'My tenant workspace', AR: 'مساحة عمل جهتي' },
  'owner.nav.open_console': { EN: 'Owner Console', AR: 'وحدة تحكم المالك' },
  'owner.loading': { EN: 'Loading…', AR: 'جارٍ التحميل…' },
  'owner.retry': { EN: 'Try again', AR: 'إعادة المحاولة' },
  'owner.cancel': { EN: 'Cancel', AR: 'إلغاء' },
  'owner.close': { EN: 'Close', AR: 'إغلاق' },
  'owner.confirm': { EN: 'Confirm', AR: 'تأكيد' },
  'owner.password': { EN: 'Your password (confirmation)', AR: 'كلمة المرور الخاصة بك (للتأكيد)' },
  'owner.password_help': { EN: 'Sensitive owner actions ask for your password again.', AR: 'تطلب إجراءات المالك الحساسة إعادة إدخال كلمة المرور.' },
  'owner.reason': { EN: 'Reason', AR: 'السبب' },
  'owner.none': { EN: 'None', AR: 'لا يوجد' },
  'owner.yes': { EN: 'Yes', AR: 'نعم' },
  'owner.no': { EN: 'No', AR: 'لا' },

  // Delegated access banner
  'owner.access.banner': { EN: 'OWNER ACCESS — You are currently managing {tenant}', AR: 'وصول المالك — أنت تدير حاليًا {tenant}' },
  'owner.access.expires': { EN: 'Session ends at {time}', AR: 'تنتهي الجلسة عند {time}' },
  'owner.access.exit': { EN: 'Exit tenant', AR: 'الخروج من الجهة' },
  'owner.access.help': { EN: 'Everything you do here is recorded under your own name in this tenant\'s audit log. Exit returns you to the Owner Console.', AR: 'كل ما تقوم به هنا يُسجَّل باسمك في سجل تدقيق هذه الجهة. يعيدك الخروج إلى وحدة تحكم المالك.' },
  'owner.enter.title': { EN: 'Enter tenant', AR: 'الدخول إلى الجهة' },
  'owner.enter.button': { EN: 'Enter tenant', AR: 'الدخول إلى الجهة' },
  'owner.enter.help': { EN: 'You enter as the platform owner with tenant administrator rights for a short session. You never sign in as a tenant user. Give a reason; it is recorded with every action.', AR: 'تدخل بصفتك مالك المنصة بصلاحيات مدير الجهة لجلسة قصيرة، دون تسجيل الدخول باسم أي مستخدم في الجهة. اذكر السبب، إذ يُسجَّل مع كل إجراء.' },
  'owner.enter.reason_placeholder': { EN: 'e.g. Support request 1234: configure the Meta Model', AR: 'مثال: طلب دعم 1234: إعداد النموذج الوصفي' },
  'owner.enter.duration': { EN: 'Session length (minutes)', AR: 'مدة الجلسة (بالدقائق)' },

  // Dashboard
  'owner.dash.title': { EN: 'Platform dashboard', AR: 'لوحة معلومات المنصة' },
  'owner.dash.subtitle': { EN: 'All tenants at a glance. Every figure is counted from tenant data; scores show how they are calculated.', AR: 'نظرة شاملة على جميع الجهات. كل رقم محسوب من بيانات الجهات، وتوضح الدرجات طريقة حسابها.' },
  'owner.dash.help': { EN: 'Totals add up the tenants\' repositories. Maturity and health come from each tenant\'s latest assessment (refreshed daily or when you open the tenant). Averages describe the platform; they are not a ranking of organizations with different mandates.', AR: 'تجمع الإجماليات مستودعات الجهات. يأتي النضج والسلامة من أحدث تقييم لكل جهة (يُحدَّث يوميًا أو عند فتح الجهة). تصف المتوسطات المنصة ككل، ولا تمثل ترتيبًا لجهات ذات اختصاصات مختلفة.' },
  'owner.dash.tenants_total': { EN: 'Tenants', AR: 'الجهات' },
  'owner.dash.tenants_active': { EN: 'Active', AR: 'نشطة' },
  'owner.dash.tenants_suspended': { EN: 'Suspended', AR: 'موقوفة' },
  'owner.dash.tenants_new': { EN: 'Created in the last 30 days', AR: 'أُنشئت خلال آخر 30 يومًا' },
  'owner.dash.repository': { EN: 'Repository content across tenants', AR: 'محتوى المستودعات في جميع الجهات' },
  'owner.dash.quality': { EN: 'Repository quality across tenants', AR: 'جودة المستودعات في جميع الجهات' },
  'owner.dash.assessment': { EN: 'Maturity and health', AR: 'النضج والسلامة' },
  'owner.dash.avg_health': { EN: 'Average repository health', AR: 'متوسط سلامة المستودع' },
  'owner.dash.assessed': { EN: 'Tenants assessed', AR: 'الجهات المقيَّمة' },
  'owner.dash.distribution': { EN: 'EA maturity distribution', AR: 'توزيع نضج البنية المؤسسية' },
  'owner.dash.recent': { EN: 'Recently created tenants', AR: 'الجهات المُنشأة حديثًا' },
  'owner.dash.objects': { EN: 'Objects', AR: 'العناصر' },
  'owner.dash.relationships': { EN: 'Relationships', AR: 'العلاقات' },
  'owner.dash.reviews': { EN: 'Architecture reviews', AR: 'مراجعات البنية' },
  'owner.dash.q.withoutOwner': { EN: 'Objects without an owner', AR: 'عناصر بلا مالك' },
  'owner.dash.q.withoutRelationship': { EN: 'Objects without relationships', AR: 'عناصر بلا علاقات' },
  'owner.dash.q.stale': { EN: 'Stale objects (not updated for a year)', AR: 'عناصر قديمة (لم تُحدَّث منذ عام)' },
  'owner.dash.q.withoutLifecycle': { EN: 'Applications/technology without lifecycle', AR: 'تطبيقات/تقنيات بلا دورة حياة' },
  'owner.dash.q.capabilitiesNotTraced': { EN: 'Capabilities not traced to strategy', AR: 'قدرات غير مرتبطة بالاستراتيجية' },

  // EA concepts
  'owner.concept.GOAL': { EN: 'Strategic goals', AR: 'الأهداف الاستراتيجية' },
  'owner.concept.OBJECTIVE': { EN: 'Strategic objectives', AR: 'الأهداف التفصيلية' },
  'owner.concept.INITIATIVE': { EN: 'Initiatives', AR: 'المبادرات' },
  'owner.concept.KPI': { EN: 'KPIs', AR: 'مؤشرات الأداء' },
  'owner.concept.CAPABILITY': { EN: 'Business capabilities', AR: 'القدرات المؤسسية' },
  'owner.concept.SERVICE': { EN: 'Business services', AR: 'الخدمات' },
  'owner.concept.PROCESS': { EN: 'Business processes', AR: 'الإجراءات' },
  'owner.concept.ORG_UNIT': { EN: 'Organization units', AR: 'الوحدات التنظيمية' },
  'owner.concept.BENEFICIARY': { EN: 'Beneficiary segments', AR: 'فئات المستفيدين' },
  'owner.concept.JOURNEY': { EN: 'Beneficiary journeys', AR: 'رحلات المستفيدين' },
  'owner.concept.JOURNEY_STAGE': { EN: 'Journey stages', AR: 'مراحل الرحلة' },
  'owner.concept.CHANNEL': { EN: 'Channels', AR: 'القنوات' },
  'owner.concept.TOUCHPOINT': { EN: 'Touchpoints', AR: 'نقاط التواصل' },
  'owner.concept.APPLICATION': { EN: 'Applications', AR: 'التطبيقات' },
  'owner.concept.APPLICATION_MODULE': { EN: 'Application modules', AR: 'وحدات التطبيقات' },
  'owner.concept.INTEGRATION': { EN: 'Integrations and APIs', AR: 'التكاملات وواجهات البرمجة' },
  'owner.concept.DATA': { EN: 'Data domains and assets', AR: 'نطاقات وأصول البيانات' },
  'owner.concept.TECHNOLOGY': { EN: 'Technology assets', AR: 'الأصول التقنية' },
  'owner.concept.PRINCIPLE': { EN: 'Principles', AR: 'المبادئ' },
  'owner.concept.STANDARD': { EN: 'Standards', AR: 'المعايير' },
  'owner.concept.REGULATION': { EN: 'Regulations', AR: 'الأنظمة والتشريعات' },
  'owner.concept.PROJECT': { EN: 'Projects', AR: 'المشاريع' },
  'owner.concept.VENDOR': { EN: 'Vendors and partners', AR: 'الموردون والشركاء' },
  'owner.concept.RISK': { EN: 'Risks', AR: 'المخاطر' },
  'owner.concept.SECURITY_CONTROL': { EN: 'Security controls', AR: 'الضوابط الأمنية' },
  'owner.concept.RELATIONSHIP': { EN: 'Relationship', AR: 'علاقة' },
  'owner.group.STRATEGY': { EN: 'Strategy', AR: 'الاستراتيجية' },
  'owner.group.BUSINESS': { EN: 'Business', AR: 'الأعمال' },
  'owner.group.BENEFICIARY': { EN: 'Beneficiary experience', AR: 'تجربة المستفيد' },
  'owner.group.APPLICATION': { EN: 'Applications', AR: 'التطبيقات' },
  'owner.group.DATA': { EN: 'Data', AR: 'البيانات' },
  'owner.group.TECHNOLOGY': { EN: 'Technology', AR: 'التقنية' },
  'owner.group.GOVERNANCE': { EN: 'Governance', AR: 'الحوكمة' },

  // Tenants list
  'owner.tenants.title': { EN: 'Tenants', AR: 'الجهات' },
  'owner.tenants.subtitle': { EN: 'Search, compare and open tenants. Create a tenant from its name and official portal.', AR: 'ابحث في الجهات وقارن بينها وافتحها. أنشئ جهة باسمها وبوابتها الرسمية.' },
  'owner.tenants.help': { EN: 'Health is the repository health score of the latest assessment; maturity is the EA maturity level (1-5). Open a tenant to see how each is calculated.', AR: 'السلامة هي درجة سلامة المستودع في أحدث تقييم، والنضج هو مستوى نضج البنية المؤسسية (1-5). افتح الجهة لمعرفة طريقة الحساب.' },
  'owner.tenants.search': { EN: 'Search by name or ID', AR: 'ابحث بالاسم أو المعرّف' },
  'owner.tenants.status_all': { EN: 'All statuses', AR: 'جميع الحالات' },
  'owner.tenants.sort': { EN: 'Sort by', AR: 'الترتيب حسب' },
  'owner.tenants.sort.createdAt': { EN: 'Newest', AR: 'الأحدث' },
  'owner.tenants.sort.name': { EN: 'Name', AR: 'الاسم' },
  'owner.tenants.sort.health': { EN: 'Repository health', AR: 'سلامة المستودع' },
  'owner.tenants.sort.maturity': { EN: 'EA maturity', AR: 'نضج البنية المؤسسية' },
  'owner.tenants.sort.objects': { EN: 'Repository size', AR: 'حجم المستودع' },
  'owner.tenants.create': { EN: 'Create tenant', AR: 'إنشاء جهة' },
  'owner.tenants.list': { EN: 'List', AR: 'القائمة' },
  'owner.tenants.compare': { EN: 'Comparison', AR: 'المقارنة' },
  'owner.tenants.compare_note': { EN: 'Organizations have different mandates: compare to spot gaps, not to rank tenants.', AR: 'للجهات اختصاصات مختلفة: استخدم المقارنة لاكتشاف الفجوات لا لترتيب الجهات.' },
  'owner.tenants.empty': { EN: 'No tenants match.', AR: 'لا توجد جهات مطابقة.' },
  'owner.col.tenant': { EN: 'Tenant', AR: 'الجهة' },
  'owner.col.status': { EN: 'Status', AR: 'الحالة' },
  'owner.col.sector': { EN: 'Sector', AR: 'القطاع' },
  'owner.col.users': { EN: 'Users', AR: 'المستخدمون' },
  'owner.col.objects': { EN: 'Objects', AR: 'العناصر' },
  'owner.col.relationships': { EN: 'Relationships', AR: 'العلاقات' },
  'owner.col.maturity': { EN: 'EA maturity', AR: 'نضج البنية' },
  'owner.col.health': { EN: 'Repository health', AR: 'سلامة المستودع' },
  'owner.col.adoption': { EN: 'ArchMind adoption', AR: 'استخدام ArchMind' },
  'owner.col.created': { EN: 'Created', AR: 'تاريخ الإنشاء' },
  'owner.col.last_activity': { EN: 'Last activity', AR: 'آخر نشاط' },
  'owner.col.applications': { EN: 'Applications', AR: 'التطبيقات' },
  'owner.col.capabilities': { EN: 'Capabilities', AR: 'القدرات' },
  'owner.col.processes': { EN: 'Processes', AR: 'الإجراءات' },
  'owner.col.beneficiaries': { EN: 'Beneficiaries', AR: 'المستفيدون' },
  'owner.col.journeys': { EN: 'Journeys', AR: 'الرحلات' },
  'owner.status.ACTIVE': { EN: 'Active', AR: 'نشطة' },
  'owner.status.SUSPENDED': { EN: 'Suspended', AR: 'موقوفة' },
  'owner.status.OFFBOARDED': { EN: 'Offboarded', AR: 'منتهية' },

  // Create tenant
  'owner.create.title': { EN: 'Create tenant', AR: 'إنشاء جهة' },
  'owner.create.help': { EN: 'Only the organization name is required. With the official portal, ArchMind can research the organization from public sources and prepare an initial repository for your review: nothing is added to the repository until you approve it.', AR: 'اسم الجهة وحده إلزامي. ومع البوابة الرسمية يستطيع ArchMind البحث عن الجهة في المصادر العامة وإعداد مستودع أولي لمراجعتك، ولا يُضاف شيء إلى المستودع قبل اعتمادك.' },
  'owner.create.name': { EN: 'Organization name', AR: 'اسم الجهة' },
  'owner.create.name_ar': { EN: 'Organization name (Arabic)', AR: 'اسم الجهة (بالعربية)' },
  'owner.create.website': { EN: 'Official website / portal', AR: 'الموقع أو البوابة الرسمية' },
  'owner.create.country': { EN: 'Country', AR: 'الدولة' },
  'owner.create.sector': { EN: 'Sector', AR: 'القطاع' },
  'owner.create.org_type': { EN: 'Organization type', AR: 'نوع الجهة' },
  'owner.create.org_type.GOVERNMENT': { EN: 'Government', AR: 'حكومية' },
  'owner.create.org_type.SEMI_GOVERNMENT': { EN: 'Semi-government', AR: 'شبه حكومية' },
  'owner.create.org_type.PRIVATE': { EN: 'Private', AR: 'خاصة' },
  'owner.create.optional': { EN: 'Optional details', AR: 'تفاصيل اختيارية' },
  'owner.create.framework': { EN: 'EA framework (Meta Model)', AR: 'إطار البنية المؤسسية (النموذج الوصفي)' },
  'owner.create.locale': { EN: 'Platform language', AR: 'لغة المنصة' },
  'owner.create.slug': { EN: 'Organization ID (sign-in)', AR: 'معرّف الجهة (لتسجيل الدخول)' },
  'owner.create.slug_help': { EN: 'Leave empty to derive it from the name.', AR: 'اتركه فارغًا ليُشتق من الاسم.' },
  'owner.create.admin_email': { EN: 'First administrator email (invitation)', AR: 'البريد الإلكتروني لأول مدير (دعوة)' },
  'owner.create.admin_name': { EN: 'First administrator name', AR: 'اسم أول مدير' },
  'owner.create.discover': { EN: 'Discover the organization with AI after creating it', AR: 'اكتشاف الجهة بالذكاء الاصطناعي بعد إنشائها' },
  'owner.create.discover_help': { EN: 'Reads the official portal (and the web, if configured) and proposes repository content with sources. You review and approve everything.', AR: 'يقرأ البوابة الرسمية (والويب إن كان مفعّلًا) ويقترح محتوى للمستودع مع مصادره، وتراجع أنت كل شيء وتعتمده.' },
  'owner.create.submit': { EN: 'Create', AR: 'إنشاء' },
  'owner.create.done': { EN: 'Tenant created', AR: 'تم إنشاء الجهة' },
  'owner.create.step.branding': { EN: 'Branding', AR: 'الهوية' },
  'owner.create.step.profile': { EN: 'Organization profile', AR: 'ملف الجهة' },
  'owner.create.step.glossary': { EN: 'Glossary', AR: 'المسرد' },
  'owner.create.step.subscription': { EN: 'Trial subscription', AR: 'الاشتراك التجريبي' },
  'owner.create.step.metaModel': { EN: 'Meta Model (published)', AR: 'النموذج الوصفي (منشور)' },
  'owner.create.step.adminInvitation': { EN: 'Administrator invitation', AR: 'دعوة المدير' },
  'owner.create.step.DONE': { EN: 'Done', AR: 'تم' },
  'owner.create.step.SKIPPED': { EN: 'Skipped', AR: 'تم التخطي' },
  'owner.create.step.FAILED': { EN: 'Failed', AR: 'فشل' },
  'owner.create.open': { EN: 'Open tenant', AR: 'فتح الجهة' },

  // Tenant detail
  'owner.detail.back': { EN: 'All tenants', AR: 'جميع الجهات' },
  'owner.detail.tab.overview': { EN: 'Overview', AR: 'نظرة عامة' },
  'owner.detail.tab.repository': { EN: 'Repository', AR: 'المستودع' },
  'owner.detail.tab.maturity': { EN: 'Maturity', AR: 'النضج' },
  'owner.detail.tab.beneficiaries': { EN: 'Beneficiaries', AR: 'المستفيدون' },
  'owner.detail.tab.enrichment': { EN: 'AI enrichment', AR: 'الإثراء بالذكاء الاصطناعي' },
  'owner.detail.tab.views': { EN: 'EA Views', AR: 'عروض البنية المؤسسية' },
  'owner.detail.tab.recommendations': { EN: 'Recommendations', AR: 'التوصيات' },
  'owner.detail.tab.activity': { EN: 'Activity', AR: 'النشاط' },
  'owner.detail.activate': { EN: 'Activate', AR: 'تفعيل' },
  'owner.detail.suspend': { EN: 'Suspend', AR: 'إيقاف' },
  'owner.detail.status_title': { EN: 'Change tenant status', AR: 'تغيير حالة الجهة' },
  'owner.detail.status_help': { EN: 'Suspending blocks sign-in for everyone in the tenant and ends any owner access session. Data is kept.', AR: 'يمنع الإيقاف تسجيل دخول جميع مستخدمي الجهة وينهي أي جلسة وصول للمالك، مع الاحتفاظ بالبيانات.' },
  'owner.detail.profile': { EN: 'Organization profile', AR: 'ملف الجهة' },
  'owner.detail.website': { EN: 'Official website', AR: 'الموقع الرسمي' },
  'owner.detail.country': { EN: 'Country', AR: 'الدولة' },
  'owner.detail.sector': { EN: 'Sector', AR: 'القطاع' },
  'owner.detail.org_type': { EN: 'Organization type', AR: 'نوع الجهة' },
  'owner.detail.description': { EN: 'Description', AR: 'الوصف' },
  'owner.detail.meta_model': { EN: 'Meta Model', AR: 'النموذج الوصفي' },
  'owner.detail.meta_model_none': { EN: 'No published Meta Model', AR: 'لا يوجد نموذج وصفي منشور' },
  'owner.detail.users': { EN: 'Users', AR: 'المستخدمون' },
  'owner.detail.admins': { EN: 'Administrators', AR: 'المديرون' },
  'owner.detail.pending_invites': { EN: 'Pending invitations', AR: 'دعوات معلّقة' },
  'owner.detail.active_sessions': { EN: 'Active owner access sessions', AR: 'جلسات وصول المالك النشطة' },
  'owner.detail.latest_job': { EN: 'Latest AI enrichment', AR: 'آخر إثراء بالذكاء الاصطناعي' },
  'owner.detail.concepts': { EN: 'Repository content', AR: 'محتوى المستودع' },

  // Maturity
  'owner.maturity.title': { EN: 'EA maturity', AR: 'نضج البنية المؤسسية' },
  'owner.maturity.help': { EN: 'Each domain is at the highest level whose criteria (and those of every lower level) are met by evidence in the tenant\'s own data. Domains without data are not assessed. Overall is the median of assessed domains. Nothing here is scored by AI.', AR: 'يكون كل مجال عند أعلى مستوى تتحقق معاييره (ومعايير كل المستويات الأدنى) بأدلة من بيانات الجهة نفسها. لا تُقيَّم المجالات التي لا تتوفر لها بيانات. المستوى العام هو وسيط المجالات المقيَّمة. لا يُقيَّم أي شيء هنا بالذكاء الاصطناعي.' },
  'owner.maturity.overall': { EN: 'Overall', AR: 'المستوى العام' },
  'owner.maturity.target': { EN: 'Target', AR: 'المستهدف' },
  'owner.maturity.not_assessed': { EN: 'Not assessed', AR: 'غير مقيَّم' },
  'owner.maturity.level.1': { EN: 'Initial', AR: 'أولي' },
  'owner.maturity.level.2': { EN: 'Managed', AR: 'مُدار' },
  'owner.maturity.level.3': { EN: 'Defined', AR: 'مُعرّف' },
  'owner.maturity.level.4': { EN: 'Quantitatively Managed', AR: 'مُدار كمياً' },
  'owner.maturity.level.5': { EN: 'Optimizing', AR: 'مُحسَّن باستمرار' },
  'owner.maturity.criteria': { EN: 'Criteria and evidence', AR: 'المعايير والأدلة' },
  'owner.maturity.next_gaps': { EN: 'To reach the next level', AR: 'للوصول إلى المستوى التالي' },
  'owner.maturity.met': { EN: 'Met', AR: 'متحقق' },
  'owner.maturity.not_met': { EN: 'Not met', AR: 'غير متحقق' },
  'owner.maturity.method': { EN: 'Method', AR: 'المنهجية' },
  'owner.maturity.trend': { EN: 'Trend', AR: 'الاتجاه' },
  'owner.maturity.computed': { EN: 'Computed {time}', AR: 'حُسب في {time}' },
  'owner.health.title': { EN: 'Repository health', AR: 'سلامة المستودع' },
  'owner.health.help': { EN: 'Each indicator is a simple ratio counted in the repository (shown as numerator / denominator). The score is their unweighted mean; staleness counts in reverse. Indicators without data are left out.', AR: 'كل مؤشر نسبة بسيطة محسوبة من المستودع (تُعرض بصيغة البسط / المقام). الدرجة هي متوسطها غير المرجّح، وتُحسب نسبة التقادم عكسيًا. تُستبعد المؤشرات التي لا تتوفر لها بيانات.' },
  'owner.health.indicator': { EN: 'Indicator', AR: 'المؤشر' },
  'owner.health.value': { EN: 'Value', AR: 'القيمة' },
  'owner.health.count': { EN: 'Count', AR: 'العدد' },
  'owner.health.coverage': { EN: 'Coverage of core EA concepts', AR: 'تغطية مفاهيم البنية المؤسسية الأساسية' },
  'owner.adoption.title': { EN: 'ArchMind adoption', AR: 'استخدام ArchMind' },
  'owner.adoption.help': { EN: 'Which ArchMind capabilities this tenant uses, counted from its own activity. Kept separate from maturity and repository health.', AR: 'قدرات ArchMind التي تستخدمها هذه الجهة، محسوبة من نشاطها. تُعرض منفصلة عن النضج وسلامة المستودع.' },
  'owner.adoption.in_use': { EN: '{n} of {m} capabilities in use', AR: '{n} من أصل {m} قدرات مستخدمة' },
  'owner.adoption.unused': { EN: 'Not used yet', AR: 'غير مستخدمة بعد' },

  // Beneficiaries
  'owner.bene.title': { EN: 'Beneficiary experience', AR: 'تجربة المستفيد' },
  'owner.bene.help': { EN: 'Beneficiary Experience is a first-class EA domain: segments, the services they receive, their journeys and the channels they use.', AR: 'تجربة المستفيد مجال أساسي في البنية المؤسسية: فئات المستفيدين والخدمات التي يتلقونها ورحلاتهم والقنوات التي يستخدمونها.' },
  'owner.bene.traceability': { EN: 'Services linked to a beneficiary or journey', AR: 'الخدمات المرتبطة بمستفيد أو رحلة' },
  'owner.bene.journey_service': { EN: 'Journeys linked to a service', AR: 'الرحلات المرتبطة بخدمة' },
  'owner.bene.journey_channel': { EN: 'Journeys linked to a channel', AR: 'الرحلات المرتبطة بقناة' },

  // Enrichment
  'owner.enrich.title': { EN: 'AI organization discovery', AR: 'اكتشاف الجهة بالذكاء الاصطناعي' },
  'owner.enrich.help': { EN: 'ArchMind reads the official portal (and the web, when configured), extracts architecture content with the exact source excerpt, checks every excerpt against the source, maps it to this tenant\'s Meta Model and compares it with the repository. Nothing is written until you approve and commit.', AR: 'يقرأ ArchMind البوابة الرسمية (والويب عند تفعيله)، ويستخرج محتوى البنية مع المقتطف الحرفي من المصدر، ويتحقق من كل مقتطف مقابل مصدره، ثم يربطه بالنموذج الوصفي لهذه الجهة ويقارنه بالمستودع. لا يُكتب شيء قبل اعتمادك وتنفيذك.' },
  'owner.enrich.launch': { EN: 'Start discovery', AR: 'بدء الاكتشاف' },
  'owner.enrich.scopes': { EN: 'What to discover', AR: 'ما المطلوب اكتشافه' },
  'owner.enrich.website': { EN: 'Official website', AR: 'الموقع الرسمي' },
  'owner.enrich.web_search_on': { EN: 'Web search is configured: public sources beyond the portal are also read.', AR: 'البحث في الويب مفعّل: تُقرأ أيضًا مصادر عامة خارج البوابة.' },
  'owner.enrich.web_search_off': { EN: 'Web search is not configured: only the official portal is read.', AR: 'البحث في الويب غير مفعّل: تُقرأ البوابة الرسمية فقط.' },
  'owner.enrich.history': { EN: 'Discovery history', AR: 'سجل الاكتشاف' },
  'owner.enrich.no_jobs': { EN: 'No discovery has been run for this tenant.', AR: 'لم يُنفَّذ أي اكتشاف لهذه الجهة.' },
  'owner.enrich.progress': { EN: 'Progress', AR: 'التقدم' },
  'owner.enrich.running': { EN: 'Discovery is running. You can leave this page; it continues in the background.', AR: 'الاكتشاف قيد التنفيذ. يمكنك مغادرة الصفحة، إذ يستمر في الخلفية.' },
  'owner.enrich.failed': { EN: 'Discovery failed', AR: 'فشل الاكتشاف' },
  'owner.enrich.cancel': { EN: 'Cancel discovery', AR: 'إلغاء الاكتشاف' },
  'owner.enrich.review': { EN: 'Review discoveries', AR: 'مراجعة الاكتشافات' },
  'owner.enrich.commit': { EN: 'Commit approved items', AR: 'تنفيذ العناصر المعتمدة' },
  'owner.enrich.commit_help': { EN: 'Approved items are written to the repository with their sources. Existing values entered by the tenant are never overwritten; empty fields are filled.', AR: 'تُكتب العناصر المعتمدة في المستودع مع مصادرها. لا تُستبدل أبدًا القيم التي أدخلتها الجهة، وتُملأ الحقول الفارغة فقط.' },
  'owner.enrich.apply_profile': { EN: 'Also fill empty organization profile fields with verified statements', AR: 'ملء حقول ملف الجهة الفارغة أيضًا بالعبارات الموثّقة' },
  'owner.enrich.committed': { EN: 'Committed: {created} created, {enriched} enriched, {linked} relationships, {skipped} skipped, {failed} failed', AR: 'تم التنفيذ: {created} أُنشئت، {enriched} أُثريت، {linked} علاقات، {skipped} تم تخطيها، {failed} فشلت' },
  'owner.enrich.objects': { EN: 'Objects', AR: 'العناصر' },
  'owner.enrich.relationships': { EN: 'Relationships', AR: 'العلاقات' },
  'owner.enrich.sources': { EN: 'Sources read', AR: 'المصادر المقروءة' },
  'owner.enrich.limitations': { EN: 'Limitations', AR: 'القيود' },
  'owner.enrich.usage': { EN: 'Usage', AR: 'الاستهلاك' },
  'owner.enrich.usage_line': { EN: '{calls} AI calls · {tokens} tokens · {searches} searches · {pages} pages · {credits} credits', AR: '{calls} طلبات للذكاء الاصطناعي · {tokens} رمز · {searches} عمليات بحث · {pages} صفحات · {credits} رصيد' },
  'owner.enrich.profile': { EN: 'Discovered organization profile', AR: 'ملف الجهة المكتشف' },
  'owner.enrich.logo': { EN: 'Official logo candidate', AR: 'الشعار الرسمي المرشح' },
  'owner.enrich.logo_help': { EN: 'Taken only from the official site\'s own markup. Approve it to store it as the tenant logo when you commit.', AR: 'مأخوذ فقط من شيفرة الموقع الرسمي نفسه. اعتمده ليُحفظ شعارًا للجهة عند التنفيذ.' },
  'owner.enrich.views_projection': { EN: 'Views these discoveries would enable', AR: 'العروض التي ستتيحها هذه الاكتشافات' },
  'owner.enrich.approve': { EN: 'Approve', AR: 'اعتماد' },
  'owner.enrich.reject': { EN: 'Reject', AR: 'رفض' },
  'owner.enrich.merge': { EN: 'Merge into existing', AR: 'دمج مع العنصر الموجود' },
  'owner.enrich.approve_verified': { EN: 'Approve all verified', AR: 'اعتماد كل العناصر الموثّقة' },
  'owner.enrich.evidence': { EN: 'Evidence', AR: 'الأدلة' },
  'owner.enrich.excerpt_found': { EN: 'excerpt found in source', AR: 'المقتطف موجود في المصدر' },
  'owner.enrich.excerpt_missing': { EN: 'excerpt NOT found in source', AR: 'المقتطف غير موجود في المصدر' },
  'owner.enrich.confidence': { EN: 'Confidence', AR: 'الثقة' },
  'owner.enrich.type': { EN: 'Repository type', AR: 'نوع العنصر في المستودع' },
  'owner.enrich.matched': { EN: 'Existing object', AR: 'عنصر موجود' },
  'owner.enrich.duplicates': { EN: 'Possible duplicates', AR: 'تكرارات محتملة' },
  'owner.enrich.filter_all': { EN: 'All', AR: 'الكل' },
  'owner.enrich.no_items': { EN: 'No items match.', AR: 'لا توجد عناصر مطابقة.' },
  'owner.enrich.attributes': { EN: 'Stated attributes', AR: 'الخصائص المذكورة' },
  'owner.enrich.commit_result': { EN: 'Result', AR: 'النتيجة' },
  'owner.enrich.scope.FULL': { EN: 'Full organization discovery', AR: 'اكتشاف شامل للجهة' },
  'owner.enrich.scope.STRATEGY': { EN: 'Strategy', AR: 'الاستراتيجية' },
  'owner.enrich.scope.BUSINESS': { EN: 'Business architecture', AR: 'هندسة الأعمال' },
  'owner.enrich.scope.BENEFICIARY': { EN: 'Beneficiary experience', AR: 'تجربة المستفيد' },
  'owner.enrich.scope.APPLICATIONS': { EN: 'Applications', AR: 'التطبيقات' },
  'owner.enrich.scope.APPLICATION_MODULES': { EN: 'Application modules', AR: 'وحدات التطبيقات' },
  'owner.enrich.scope.PROCESSES': { EN: 'Processes', AR: 'الإجراءات' },
  'owner.enrich.scope.CAPABILITIES': { EN: 'Capabilities', AR: 'القدرات' },
  'owner.enrich.scope.SERVICES': { EN: 'Services', AR: 'الخدمات' },
  'owner.enrich.scope.DATA': { EN: 'Data', AR: 'البيانات' },
  'owner.enrich.scope.TECHNOLOGY': { EN: 'Technology', AR: 'التقنية' },
  'owner.enrich.scope.RELATIONSHIPS': { EN: 'Relationships', AR: 'العلاقات' },
  'owner.enrich.scope.MISSING': { EN: 'Missing repository information', AR: 'معلومات المستودع الناقصة' },
  'owner.stage.QUEUED': { EN: 'Queued', AR: 'في الانتظار' },
  'owner.stage.DISCOVERING': { EN: 'Discovering sources', AR: 'اكتشاف المصادر' },
  'owner.stage.EXTRACTING': { EN: 'Extracting', AR: 'الاستخراج' },
  'owner.stage.NORMALIZING': { EN: 'Normalizing', AR: 'التوحيد' },
  'owner.stage.MAPPING': { EN: 'Mapping to Meta Model', AR: 'الربط بالنموذج الوصفي' },
  'owner.stage.DEDUPLICATING': { EN: 'Deduplicating', AR: 'إزالة التكرار' },
  'owner.stage.VALIDATING': { EN: 'Validating evidence', AR: 'التحقق من الأدلة' },
  'owner.stage.BUILDING_RELATIONSHIPS': { EN: 'Building relationships', AR: 'بناء العلاقات' },
  'owner.stage.PREPARING_VIEWS': { EN: 'Preparing views', AR: 'إعداد العروض' },
  'owner.stage.READY_FOR_REVIEW': { EN: 'Ready for review', AR: 'جاهز للمراجعة' },
  'owner.stage.APPROVED': { EN: 'Approved', AR: 'معتمد' },
  'owner.stage.COMMITTING': { EN: 'Committing', AR: 'جارٍ التنفيذ' },
  'owner.stage.COMPLETED': { EN: 'Completed', AR: 'مكتمل' },
  'owner.stage.FAILED': { EN: 'Failed', AR: 'فشل' },
  'owner.stage.CANCELLED': { EN: 'Cancelled', AR: 'ملغى' },
  'owner.class.VERIFIED': { EN: 'Verified fact', AR: 'حقيقة موثّقة' },
  'owner.class.LIKELY': { EN: 'Likely', AR: 'مرجّح' },
  'owner.class.INFERRED': { EN: 'Inferred', AR: 'مستنتج' },
  'owner.class.INSUFFICIENT_EVIDENCE': { EN: 'Insufficient evidence', AR: 'أدلة غير كافية' },
  'owner.fact.FACT': { EN: 'Stated by the source', AR: 'مذكور في المصدر' },
  'owner.fact.INFERENCE': { EN: 'AI inference', AR: 'استنتاج الذكاء الاصطناعي' },
  'owner.fact.PROPOSED': { EN: 'Proposed architecture', AR: 'بنية مقترحة' },
  'owner.change.NEW': { EN: 'New', AR: 'جديد' },
  'owner.change.ENRICH_EXISTING': { EN: 'Enriches existing', AR: 'يُثري عنصرًا موجودًا' },
  'owner.change.RELATIONSHIP': { EN: 'Relationship discovery', AR: 'اكتشاف علاقة' },
  'owner.change.POSSIBLE_DUPLICATE': { EN: 'Possible duplicate', AR: 'تكرار محتمل' },
  'owner.change.CONFLICT': { EN: 'Conflict (existing kept)', AR: 'تعارض (يُحتفظ بالموجود)' },
  'owner.change.NO_CHANGE': { EN: 'No change', AR: 'لا تغيير' },
  'owner.decision.PENDING': { EN: 'Pending', AR: 'معلّق' },
  'owner.decision.APPROVED': { EN: 'Approved', AR: 'معتمد' },
  'owner.decision.REJECTED': { EN: 'Rejected', AR: 'مرفوض' },
  'owner.decision.MERGE': { EN: 'Merge', AR: 'دمج' },
  'owner.mapping.CONFIGURATION_REQUIRED': { EN: 'Not in this tenant\'s Meta Model (not committed)', AR: 'غير موجود في النموذج الوصفي للجهة (لن يُنفَّذ)' },
  'owner.mapping.NO_DEFINITION': { EN: 'No relationship definition in the Meta Model (not committed)', AR: 'لا يوجد تعريف لهذه العلاقة في النموذج الوصفي (لن تُنفَّذ)' },

  // Views
  'owner.views.title': { EN: 'Recommended EA Views', AR: 'عروض البنية المؤسسية الموصى بها' },
  'owner.views.help': { EN: 'Each library viewpoint is checked against the data this tenant actually has. Value = 40 relationship coverage + 25 data coverage + 20 decision usefulness + 15 strategic/beneficiary relevance. Only READY views are prepared, and a view that would be empty is never created.', AR: 'تُفحص كل وجهة نظر في المكتبة مقابل البيانات المتوفرة فعليًا لدى الجهة. القيمة = 40 لتغطية العلاقات + 25 لتغطية البيانات + 20 لفائدة القرار + 15 للأهمية الاستراتيجية أو للمستفيد. لا تُعدّ إلا العروض الجاهزة، ولا يُنشأ أبدًا عرض فارغ.' },
  'owner.views.prepare': { EN: 'Prepare ready views', AR: 'إعداد العروض الجاهزة' },
  'owner.views.prepared': { EN: '{n} views prepared and published to the tenant\'s View Library', AR: 'تم إعداد {n} عروض ونشرها في مكتبة عروض الجهة' },
  'owner.views.skipped': { EN: 'Skipped', AR: 'تم تخطيه' },
  'owner.views.col.view': { EN: 'View', AR: 'العرض' },
  'owner.views.col.status': { EN: 'Status', AR: 'الحالة' },
  'owner.views.col.value': { EN: 'Value', AR: 'القيمة' },
  'owner.views.col.why': { EN: 'Why / what is missing', AR: 'السبب / الناقص' },
  'owner.views.col.visualization': { EN: 'Visualization', AR: 'طريقة العرض' },
  'owner.views.exists': { EN: 'Already in the library', AR: 'موجود في المكتبة' },
  'owner.views.status.READY': { EN: 'Ready', AR: 'جاهز' },
  'owner.views.status.PARTIAL': { EN: 'Partial', AR: 'جزئي' },
  'owner.views.status.RECOMMENDED_AFTER_ENRICHMENT': { EN: 'After relationship discovery', AR: 'بعد اكتشاف العلاقات' },
  'owner.views.status.INSUFFICIENT_DATA': { EN: 'Insufficient data', AR: 'بيانات غير كافية' },
  'owner.views.status.LIKELY_READY_AFTER_COMMIT': { EN: 'Likely ready after commit', AR: 'جاهز غالبًا بعد التنفيذ' },
  'owner.views.status.IMPROVED_AFTER_COMMIT': { EN: 'Improved after commit', AR: 'يتحسن بعد التنفيذ' },
  'owner.views.show_all': { EN: 'Show views without data', AR: 'عرض العروض التي لا تتوفر لها بيانات' },

  // Recommendations
  'owner.recs.title': { EN: 'Best-practice recommendations', AR: 'توصيات أفضل الممارسات' },
  'owner.recs.help': { EN: 'A recommendation appears only when its gap is found in this tenant\'s numbers. Each one names the evidence, the action, the maturity criterion it helps meet and the ArchMind capability that supports it.', AR: 'لا تظهر التوصية إلا عند اكتشاف فجوتها في أرقام هذه الجهة. وتذكر كل توصية الدليل والإجراء ومعيار النضج الذي تساعد على تحقيقه وقدرة ArchMind الداعمة لها.' },
  'owner.recs.nba': { EN: 'Next best actions', AR: 'أفضل الإجراءات التالية' },
  'owner.recs.none': { EN: 'No gaps detected by the current rules.', AR: 'لم تكتشف القواعد الحالية أي فجوات.' },
  'owner.recs.gap': { EN: 'Gap', AR: 'الفجوة' },
  'owner.recs.why': { EN: 'Why it matters', AR: 'أهميتها' },
  'owner.recs.evidence': { EN: 'Current evidence', AR: 'الدليل الحالي' },
  'owner.recs.action': { EN: 'Recommended action', AR: 'الإجراء الموصى به' },
  'owner.recs.improvement': { EN: 'Expected maturity improvement', AR: 'التحسن المتوقع في النضج' },
  'owner.recs.role': { EN: 'Suggested owner', AR: 'المسؤول المقترح' },
  'owner.recs.timeframe': { EN: 'Timeframe', AR: 'الإطار الزمني' },
  'owner.recs.capability': { EN: 'ArchMind support', AR: 'دعم ArchMind' },
  'owner.priority.HIGH': { EN: 'High', AR: 'عالية' },
  'owner.priority.MEDIUM': { EN: 'Medium', AR: 'متوسطة' },
  'owner.priority.LOW': { EN: 'Low', AR: 'منخفضة' },

  // Activity / audit
  'owner.activity.sessions': { EN: 'Owner access sessions', AR: 'جلسات وصول المالك' },
  'owner.activity.audit': { EN: 'Owner actions', AR: 'إجراءات المالك' },
  'owner.audit.title': { EN: 'Audit', AR: 'سجل التدقيق' },
  'owner.audit.help': { EN: 'Every owner action across the platform, and every delegated access session with its reason, duration and number of changes.', AR: 'كل إجراء للمالك على مستوى المنصة، وكل جلسة وصول مفوّض مع سببها ومدتها وعدد التغييرات.' },
  'owner.audit.col.time': { EN: 'Time', AR: 'الوقت' },
  'owner.audit.col.actor': { EN: 'Owner', AR: 'المالك' },
  'owner.audit.col.action': { EN: 'Action', AR: 'الإجراء' },
  'owner.audit.col.detail': { EN: 'Detail', AR: 'التفاصيل' },
  'owner.audit.col.started': { EN: 'Started', AR: 'البدء' },
  'owner.audit.col.ended': { EN: 'Ended', AR: 'الانتهاء' },
  'owner.audit.col.actions': { EN: 'Changes', AR: 'التغييرات' },
  'owner.audit.end': { EN: 'End session', AR: 'إنهاء الجلسة' },
  'owner.audit.empty': { EN: 'Nothing recorded yet.', AR: 'لم يُسجَّل شيء بعد.' },
  'owner.session.ACTIVE': { EN: 'Active', AR: 'نشطة' },
  'owner.session.ENDED': { EN: 'Ended', AR: 'منتهية' },
  'owner.session.EXPIRED': { EN: 'Expired', AR: 'منتهية الصلاحية' },

  // Settings
  'owner.settings.title': { EN: 'Owner settings', AR: 'إعدادات المالك' },
  'owner.settings.help': { EN: 'How the Owner Console is configured on this platform. These settings are deployment configuration and are shown read-only.', AR: 'طريقة إعداد وحدة تحكم المالك على هذه المنصة. هذه الإعدادات جزء من إعداد النشر وتُعرض للقراءة فقط.' },
  'owner.settings.identity': { EN: 'Your owner identity', AR: 'هويتك كمالك' },
  'owner.settings.email': { EN: 'Email', AR: 'البريد الإلكتروني' },
  'owner.settings.home': { EN: 'Home tenant', AR: 'الجهة الأساسية' },
  'owner.settings.web_search': { EN: 'Web search for AI discovery', AR: 'البحث في الويب للاكتشاف بالذكاء الاصطناعي' },
  'owner.settings.ttl': { EN: 'Owner access session length', AR: 'مدة جلسة وصول المالك' },
  'owner.settings.minutes': { EN: '{n} minutes', AR: '{n} دقيقة' },
  'owner.settings.grant': { EN: 'Platform owners are granted by an operator with database access (scripts/grant-platform-owner.js). No tenant administrator can grant this role.', AR: 'يُمنح دور مالك المنصة من قبل مشغّل لديه صلاحية الوصول إلى قاعدة البيانات (scripts/grant-platform-owner.js)، ولا يستطيع أي مدير جهة منح هذا الدور.' },
  'owner.settings.enabled': { EN: 'Configured', AR: 'مفعّل' },
  'owner.settings.disabled': { EN: 'Not configured', AR: 'غير مفعّل' },
  'owner.create.step.referencePack': { EN: 'Reference models and architectures', AR: 'النماذج والمعماريات المرجعية' },
  'owner.create.industry': { EN: 'Industry', AR: 'القطاع' },
  'owner.create.industry_help': { EN: 'Decides the core business capabilities and core applications proposed for the organization. Leave it on "Detect" to decide it from the organization profile.', AR: 'يحدد قدرات الأعمال المحورية والتطبيقات المحورية المقترحة للجهة. اتركه على «تحديد تلقائي» ليُحدَّد من ملف الجهة.' },
  'owner.create.reference_pack': { EN: 'Prepare NORA reference models and the organization\'s reference architectures', AR: 'إعداد النماذج المرجعية لنورا والمعماريات المرجعية للجهة' },
  'owner.create.reference_pack_help': { EN: 'After the NORA Meta Model is published: the NORA reference models, and business, application and beneficiary reference architectures tailored to the industry (drafts for the organization to review).', AR: 'بعد نشر النموذج الوصفي لنورا: النماذج المرجعية لنورا، ومعماريات مرجعية للأعمال والتطبيقات والمستفيدين مكيّفة وفق القطاع (مسودات تراجعها الجهة).' },
  'owner.detail.tab.reference': { EN: 'Reference architectures', AR: 'المعماريات المرجعية' },
  'owner.pack.title': { EN: 'Reference models and architectures', AR: 'النماذج والمعماريات المرجعية' },
  'owner.pack.help': { EN: 'Prepares the NORA reference models and the organization\'s own reference architectures: core business capabilities and core applications of its industry, everything else as in the NORA models, and its beneficiaries. Only the NORA business capability map is official NORA content; the other models are ArchMind baselines organised by the NORA domains. Preparing again only adds what is missing.', AR: 'يُعدّ النماذج المرجعية لنورا والمعماريات المرجعية الخاصة بالجهة: قدرات الأعمال المحورية والتطبيقات المحورية لقطاعها، وكل ما عداها وفق نماذج نورا، ومستفيديها. خريطة قدرات الأعمال وحدها محتوى رسمي من نورا، أما بقية النماذج فهي نماذج أساسية أعدّتها ArchMind ومنظّمة وفق مجالات نورا. إعادة الإعداد تضيف الناقص فقط.' },
  'owner.pack.prepare': { EN: 'Prepare ({n})', AR: 'إعداد ({n})' },
  'owner.pack.preparing': { EN: 'Preparing…', AR: 'جارٍ الإعداد…' },
  'owner.pack.done': { EN: '{created} created, {added} completed with missing elements.', AR: 'تم إنشاء {created}، واستكمال العناصر الناقصة في {added}.' },
  'owner.pack.industry': { EN: 'Industry', AR: 'القطاع' },
  'owner.pack.industry_help': { EN: 'Core business capabilities and core applications come from the industry. NORA leaves core capabilities to each entity, so they are proposals for the organization to confirm.', AR: 'تأتي قدرات الأعمال المحورية والتطبيقات المحورية من القطاع. تترك نورا تحديد القدرات المحورية لكل جهة، لذا فهي مقترحات تؤكدها الجهة.' },
  'owner.pack.industry_detect': { EN: 'Detect from the organization profile', AR: 'تحديد تلقائي من ملف الجهة' },
  'owner.pack.industry.GOV_LABOR_HR': { EN: 'Labor / Human Resources', AR: 'العمل والموارد البشرية' },
  'owner.pack.industry.GOV_HEALTH': { EN: 'Health', AR: 'الصحة' },
  'owner.pack.industry.GOV_EDUCATION': { EN: 'Education', AR: 'التعليم' },
  'owner.pack.industry.GOV_TRANSPORT': { EN: 'Transport', AR: 'النقل' },
  'owner.pack.industry.GOV_MUNICIPALITY': { EN: 'Municipality', AR: 'الشؤون البلدية' },
  'owner.pack.industry.GOV_FINANCE': { EN: 'Finance', AR: 'المالية' },
  'owner.pack.industry.GOV_JUSTICE': { EN: 'Justice', AR: 'العدل' },
  'owner.pack.industry.GOV_REGULATORY': { EN: 'Regulatory authority', AR: 'جهة تنظيمية' },
  'owner.pack.industry.GOV_SOCIAL_DEVELOPMENT': { EN: 'Social development', AR: 'التنمية الاجتماعية' },
  'owner.pack.industry.GOV_STANDARDS_CONFORMITY': { EN: 'Standards & conformity', AR: 'المواصفات والمطابقة' },
  'owner.pack.industry.GOV_OTHER': { EN: 'Other government sector', AR: 'قطاع حكومي آخر' },
  'owner.pack.basis.OWNER_CHOICE': { EN: 'chosen by you', AR: 'اخترته أنت' },
  'owner.pack.basis.PROFILE_CODE': { EN: 'from the organization classification', AR: 'من تصنيف الجهة' },
  'owner.pack.basis.KEYWORDS': { EN: 'recognised from the organization profile', AR: 'مستنتج من ملف الجهة' },
  'owner.pack.basis.DEFAULT': { EN: 'not recognised: general government', AR: 'لم يُتعرّف عليه: قطاع حكومي عام' },
  'owner.pack.beneficiaries.REPOSITORY': { EN: 'Beneficiaries: those recorded in the organization\'s Repository, with the services they use.', AR: 'المستفيدون: المسجلون في مستودع الجهة، مع الخدمات التي يستخدمونها.' },
  'owner.pack.beneficiaries.INDUSTRY_DEFAULT': { EN: 'Beneficiaries: none recorded yet, so the industry\'s typical beneficiaries are proposed for review. Run AI enrichment, then prepare again to add the real ones.', AR: 'المستفيدون: لا يوجد مستفيدون مسجلون بعد، لذا تُقترح الفئات المعتادة في القطاع للمراجعة. شغّل الإثراء بالذكاء الاصطناعي ثم أعد الإعداد لإضافة المستفيدين الفعليين.' },
  'owner.pack.activate_models': { EN: 'Activate the national reference models', AR: 'تفعيل النماذج المرجعية الوطنية' },
  'owner.pack.activate_models_help': { EN: 'They are platform-provided baselines; the organization\'s architectures tailor them.', AR: 'هي نماذج أساسية توفرها المنصة، وتكيّفها المعماريات الخاصة بالجهة.' },
  'owner.pack.activate_archs': { EN: 'Activate the organization\'s architectures too', AR: 'تفعيل معماريات الجهة أيضاً' },
  'owner.pack.activate_archs_help': { EN: 'Off by default: they stay drafts so the organization\'s architects review the proposals first.', AR: 'غير مفعّل افتراضياً: تبقى مسودات ليراجع معماريو الجهة المقترحات أولاً.' },
  'owner.pack.limitations': { EN: 'Limits', AR: 'حدود الإعداد' },
  'owner.pack.col.architecture': { EN: 'Model / architecture', AR: 'النموذج / المعمارية' },
  'owner.pack.col.authority': { EN: 'Source', AR: 'المصدر' },
  'owner.pack.col.domain': { EN: 'Domain', AR: 'المجال' },
  'owner.pack.col.elements': { EN: 'Elements', AR: 'العناصر' },
  'owner.pack.col.action': { EN: 'What happens', AR: 'ما سيحدث' },
  'owner.pack.counts': { EN: '{resolved} mapped to the Meta Model · {cfg} need configuration', AR: '{resolved} مرتبطة بالنموذج الوصفي · {cfg} تحتاج إعداداً' },
  'owner.pack.tailors': { EN: 'tailors', AR: 'تكيّف' },
  'owner.pack.show_all': { EN: 'Show all {n} elements', AR: 'عرض كل العناصر ({n})' },
  'owner.pack.config_required': { EN: 'Meta Model configuration required', AR: 'يتطلب إعداد النموذج الوصفي' },
  'owner.pack.kind.REFERENCE_MODEL': { EN: 'Reference model', AR: 'نموذج مرجعي' },
  'owner.pack.kind.REFERENCE_ARCHITECTURE': { EN: 'Reference architecture', AR: 'معمارية مرجعية' },
  'owner.pack.provenance.OFFICIAL_STANDARD': { EN: 'Official NORA', AR: 'نورا (رسمي)' },
  'owner.pack.provenance.ARCHMIND_CURATED': { EN: 'ArchMind baseline', AR: 'نموذج أساسي من ArchMind' },
  'owner.pack.provenance.ORGANIZATION_TAILORED': { EN: 'Tailored to the organization', AR: 'مكيّف للجهة' },
  'owner.pack.action.CREATE': { EN: 'Will be created', AR: 'سيُنشأ' },
  'owner.pack.action.ADD_MISSING': { EN: '{n} missing elements will be added', AR: 'ستُضاف {n} من العناصر الناقصة' },
  'owner.pack.action.UP_TO_DATE': { EN: 'Up to date', AR: 'محدّث' },
  'owner.pack.action.SKIPPED': { EN: 'Not prepared', AR: 'لن يُعدّ' },
  'owner.pack.reason.NO_PUBLISHED_META_MODEL': { EN: 'no published Meta Model', AR: 'لا يوجد نموذج وصفي منشور' },
  'owner.pack.reason.DOMAIN_NOT_IN_META_MODEL': { EN: 'the Meta Model has no matching domain', AR: 'لا يحتوي النموذج الوصفي على المجال المطابق' },
  'owner.pack.reason.LATEST_VERSION': { EN: 'its latest version is {status}; start a new draft to add the rest', AR: 'أحدث إصدار له بحالة {status}؛ أنشئ مسودة جديدة لإضافة الباقي' },
  'owner.pack.source.NORA_OFFICIAL': { EN: 'NORA', AR: 'نورا' },
  'owner.pack.source.ARCHMIND_CURATED': { EN: 'ArchMind baseline', AR: 'نموذج ArchMind الأساسي' },
  'owner.pack.source.INDUSTRY_CATALOGUE': { EN: 'industry proposal', AR: 'مقترح قطاعي' },
  'owner.pack.source.TENANT_REPOSITORY': { EN: 'organization Repository', AR: 'مستودع الجهة' },
  'owner.pack.source.PACK_STRUCTURE': { EN: 'structure', AR: 'هيكل' },
  'owner.pack.disposition.ADOPTED': { EN: 'adopted', AR: 'معتمد كما هو' },
  'owner.pack.disposition.EXTENDED': { EN: 'organization-specific', AR: 'خاص بالجهة' },
  'owner.pack.disposition.PENDING_REVIEW': { EN: 'to confirm', AR: 'بانتظار التأكيد' },
  'owner.pack.disposition.ADAPTED': { EN: 'adapted', AR: 'معدّل' },
  'owner.pack.lib.title': { EN: 'NORA library: Repository and knowledge base', AR: 'مكتبة نورا: المستودع وقاعدة المعرفة' },
  'owner.pack.lib.help': { EN: 'National content every government entity shares: national platforms, the government cloud and network and national regulations go into the Repository as drafts to confirm, and the knowledge documents of the library workspace (NORA documents uploaded once to the ArchMind workspace) are copied into the organization\'s knowledge base. Nothing it already has is copied again.', AR: 'المحتوى الوطني المشترك بين الجهات الحكومية: تُضاف المنصات الوطنية والسحابة والشبكة الحكومية والأنظمة الوطنية إلى المستودع كمسودات للتأكيد، وتُنسخ وثائق المعرفة في مساحة المكتبة (وثائق نورا المرفوعة مرة واحدة إلى مساحة ArchMind) إلى قاعدة معرفة الجهة. لا يُنسخ ما هو موجود لديها مسبقاً.' },
  'owner.pack.lib.source': { EN: 'Library workspace: {name}', AR: 'مساحة المكتبة: {name}' },
  'owner.pack.lib.no_source': { EN: 'No library workspace is available; only the national baseline objects are included.', AR: 'لا تتوفر مساحة مكتبة؛ تُضاف الكائنات الوطنية الأساسية فقط.' },
  'owner.pack.lib.repository': { EN: 'Add national objects to the Repository ({n} new)', AR: 'إضافة الكائنات الوطنية إلى المستودع ({n} جديدة)' },
  'owner.pack.lib.repository_help': { EN: 'Added as drafts with their source recorded; the organization confirms them.', AR: 'تُضاف كمسودات مع تسجيل مصدرها، وتؤكدها الجهة.' },
  'owner.pack.lib.knowledge': { EN: 'Copy knowledge documents ({n})', AR: 'نسخ وثائق المعرفة ({n})' },
  'owner.pack.lib.knowledge_help': { EN: 'Copied with their searchable text, ready for Copilot, governance reviews and ADM.', AR: 'تُنسخ مع نصوصها القابلة للبحث، جاهزة للمساعد الذكي ومراجعات الحوكمة ودورات ADM.' },
  'owner.pack.lib.no_documents': { EN: 'The library workspace has no knowledge documents yet. Upload the NORA documents to the ArchMind workspace knowledge base to include them.', AR: 'لا تحتوي مساحة المكتبة على وثائق معرفة بعد. ارفع وثائق نورا إلى قاعدة معرفة مساحة ArchMind لتضمينها.' },
  'owner.pack.lib.chunks': { EN: '{n} passages', AR: '{n} مقطعاً' },
  'owner.pack.lib.done': { EN: 'NORA library: {objects} national objects added, {docs} knowledge documents copied.', AR: 'مكتبة نورا: أُضيف {objects} من الكائنات الوطنية، ونُسخت {docs} من وثائق المعرفة.' },
  'owner.pack.lib.from.NORA_BASELINE': { EN: 'national baseline', AR: 'الأساس الوطني' },
  'owner.pack.lib.from.PLATFORM_LIBRARY': { EN: 'library workspace', AR: 'مساحة المكتبة' },
  'owner.pack.lib.object.CREATE': { EN: 'will be added', AR: 'سيُضاف' },
  'owner.pack.lib.object.EXISTS': { EN: 'already recorded', AR: 'مسجل مسبقاً' },
  'owner.pack.lib.object.NO_TYPE': { EN: 'no matching Meta Model type', AR: 'لا يوجد نوع مطابق في النموذج الوصفي' },
  'owner.pack.lib.doc.COPY': { EN: 'will be copied', AR: 'ستُنسخ' },
  'owner.pack.lib.doc.EXISTS': { EN: 'already in the knowledge base', AR: 'موجودة في قاعدة المعرفة' },
  'owner.pack.lib.doc.NOT_READY': { EN: 'not processed yet', AR: 'لم تُعالج بعد' },
  ...OUTREACH_TRANSLATIONS,
}
