// Government Outreach strings (AR/EN), merged into OWNER_TRANSLATIONS.
// Terms: entity = جهة (a government organisation); tenant = مساحة عمل ArchMind;
// prospect = عميل محتمل.
type S = Record<string, { EN: string; AR: string }>

const fam = (prefix: string, items: Record<string, [string, string]>): S =>
  Object.fromEntries(Object.entries(items).map(([k, [EN, AR]]) => [`${prefix}.${k}`, { EN, AR }]))

export const OUTREACH_TRANSLATIONS: S = {
  'owner.nav.outreach': { EN: 'Government Outreach', AR: 'التواصل مع الجهات الحكومية' },
  'owner.outreach.nav.dashboard': { EN: 'Overview', AR: 'نظرة عامة' },
  'owner.outreach.nav.entities': { EN: 'Entities', AR: 'الجهات' },
  'owner.outreach.nav.prospects': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.nav.campaigns': { EN: 'Campaigns', AR: 'الحملات' },
  'owner.outreach.nav.settings': { EN: 'Settings', AR: 'الإعدادات' },

  'owner.outreach.title': { EN: 'Government Outreach', AR: 'التواصل مع الجهات الحكومية' },
  'owner.outreach.subtitle': { EN: 'KSA government entities, their EA / transformation / innovation leaders, prepared workspaces and approved outreach', AR: 'الجهات الحكومية في المملكة وقادة البنية المؤسسية والتحول الرقمي والابتكار فيها، ومساحات العمل المُعدّة، والتواصل المعتمد' },
  'owner.outreach.help': { EN: 'Find Saudi government entities and the people responsible for enterprise architecture, digital transformation and innovation there, from public sources with evidence. Prepare an ArchMind workspace for the entity, invite selected people securely and send personalised emails only after you approve each one.', AR: 'ابحث عن الجهات الحكومية السعودية والمسؤولين فيها عن البنية المؤسسية والتحول الرقمي والابتكار من مصادر عامة موثّقة بالأدلة. جهّز مساحة عمل ArchMind للجهة، وادعُ الأشخاص المختارين بطريقة آمنة، وأرسل رسائل مخصّصة فقط بعد اعتمادك لكل رسالة.' },
  'owner.outreach.email_not_configured': { EN: 'No email sender is configured (SMTP). You can prepare and approve emails, but nothing can be sent until an administrator configures it.', AR: 'لم يُضبط مرسل البريد الإلكتروني (SMTP). يمكنك إعداد الرسائل واعتمادها، ولكن لا يمكن إرسال أي رسالة حتى يضبطه أحد المسؤولين.' },
  'owner.outreach.web_search_off': { EN: 'Web search is not configured, so discovery can only read official websites. Add entities by hand meanwhile.', AR: 'البحث في الويب غير مفعّل، لذا يقتصر الاكتشاف على قراءة المواقع الرسمية. يمكنك إضافة الجهات يدوياً في الوقت الحالي.' },

  // Dashboard
  'owner.outreach.dash.entities': { EN: 'Government entities', AR: 'الجهات الحكومية' },
  'owner.outreach.dash.professionals': { EN: 'Relevant professionals', AR: 'المختصون ذوو الصلة' },
  'owner.outreach.dash.ea_leaders': { EN: 'EA leaders', AR: 'قادة البنية المؤسسية' },
  'owner.outreach.dash.dt_leaders': { EN: 'Digital transformation leaders', AR: 'قادة التحول الرقمي' },
  'owner.outreach.dash.innovation_leaders': { EN: 'Digital innovation leaders', AR: 'قادة الابتكار الرقمي' },
  'owner.outreach.dash.no_tenant': { EN: 'Entities without an ArchMind workspace', AR: 'جهات بلا مساحة عمل في ArchMind' },
  'owner.outreach.dash.tenants_created': { EN: 'Workspaces created from outreach', AR: 'مساحات عمل أُنشئت من التواصل' },
  'owner.outreach.dash.tenants_enriched': { EN: 'Workspaces enriched', AR: 'مساحات عمل أُثريت' },
  'owner.outreach.dash.invitations_sent': { EN: 'Invitations sent', AR: 'الدعوات المرسلة' },
  'owner.outreach.dash.activated': { EN: 'Activated users', AR: 'المستخدمون المفعّلون' },
  'owner.outreach.dash.engaged_tenants': { EN: 'Engaged workspaces', AR: 'مساحات عمل متفاعلة' },
  'owner.outreach.dash.funnel': { EN: 'Outreach funnel', AR: 'مسار التواصل' },
  'owner.outreach.dash.funnel_note': { EN: 'Qualified = verified by evidence or by you. Engaged = the person used ArchMind after activating.', AR: 'مؤهَّل = تم التحقق منه بالأدلة أو من قِبلك. متفاعل = استخدم الشخص ArchMind بعد تفعيل حسابه.' },
  'owner.outreach.dash.by_type': { EN: 'Entities by type', AR: 'الجهات حسب النوع' },
  ...fam('owner.outreach.funnel', { DISCOVERED: ['Discovered', 'مكتشَف'], QUALIFIED: ['Qualified', 'مؤهَّل'], TENANT_CREATED: ['Workspace ready', 'مساحة العمل جاهزة'], INVITED: ['Invited', 'مدعو'], ACTIVATED: ['Activated', 'مفعَّل'], ENGAGED: ['Engaged', 'متفاعل'] }),

  // Entities
  'owner.outreach.entities.title': { EN: 'Government Entity Directory', AR: 'دليل الجهات الحكومية' },
  'owner.outreach.entities.subtitle': { EN: 'Saudi public-sector organisations, their prospects, ArchMind workspace and outreach status', AR: 'جهات القطاع العام السعودي، وعملاؤها المحتملون، ومساحة عملها في ArchMind، وحالة التواصل' },
  'owner.outreach.entities.help': { EN: 'Each entity is one organisation. Government status comes from its official domain (gov.sa) or name; private companies are kept out of outreach. An entity links to at most one ArchMind workspace.', AR: 'كل جهة تمثّل منظمة واحدة. تُحدَّد الصفة الحكومية من نطاقها الرسمي (gov.sa) أو من اسمها، وتُستبعد الشركات الخاصة من التواصل. ترتبط كل جهة بمساحة عمل واحدة على الأكثر في ArchMind.' },
  'owner.outreach.entities.add': { EN: 'Add entity', AR: 'إضافة جهة' },
  'owner.outreach.entities.add_help': { EN: 'An organisation already in the directory (same website or name) is not added twice.', AR: 'لا تُضاف الجهة مرتين إذا كانت موجودة في الدليل بالموقع نفسه أو الاسم نفسه.' },
  'owner.outreach.entities.discover': { EN: 'Discover entities', AR: 'اكتشاف الجهات' },
  'owner.outreach.entities.discover_help': { EN: 'Searches public sources for Saudi government organisations of the chosen type. Every organisation found cites the source passage; companies and foreign bodies are left out.', AR: 'يبحث في المصادر العامة عن جهات حكومية سعودية من النوع المختار. تستشهد كل جهة يُعثر عليها بمقطع من مصدرها، وتُستبعد الشركات والجهات الأجنبية.' },
  'owner.outreach.entities.search': { EN: 'Search name or website', AR: 'ابحث بالاسم أو الموقع' },
  'owner.outreach.entities.empty': { EN: 'No entities yet. Add one or discover entities from public sources.', AR: 'لا توجد جهات بعد. أضف جهة أو اكتشف الجهات من المصادر العامة.' },
  'owner.outreach.entities.research': { EN: 'Research prospects', AR: 'البحث عن العملاء المحتملين' },
  'owner.outreach.entities.research_help': { EN: 'Looks for EA, digital transformation and innovation leaders of the selected entities (up to 10 at a time) on their official websites and public professional sources. LinkedIn is not accessed.', AR: 'يبحث عن قادة البنية المؤسسية والتحول الرقمي والابتكار في الجهات المختارة (حتى 10 جهات في المرة الواحدة) في مواقعها الرسمية والمصادر المهنية العامة. لا يتم الوصول إلى LinkedIn.' },
  'owner.outreach.entities.research_started': { EN: 'Research started for {n} entities ({skipped} skipped).', AR: 'بدأ البحث في {n} جهة (تم تخطي {skipped}).' },
  'owner.outreach.all_types': { EN: 'All types', AR: 'جميع الأنواع' },
  'owner.outreach.all_gov': { EN: 'Any government status', AR: 'أي صفة حكومية' },
  'owner.outreach.all_tenant': { EN: 'Any workspace status', AR: 'أي حالة لمساحة العمل' },
  'owner.outreach.all_outreach': { EN: 'Any outreach status', AR: 'أي حالة تواصل' },
  'owner.outreach.any': { EN: 'any', AR: 'الكل' },
  ...fam('owner.outreach.tenant', { LINKED: ['Has a workspace', 'لديها مساحة عمل'], NONE: ['No workspace', 'بلا مساحة عمل'] }),
  'owner.outreach.select': { EN: 'Select', AR: 'تحديد' },
  'owner.outreach.selection': { EN: 'Selection', AR: 'المحدَّد' },
  'owner.outreach.selected': { EN: '{n} selected', AR: '{n} محدَّد' },
  'owner.outreach.suppressed': { EN: 'Do not contact', AR: 'عدم التواصل' },
  'owner.outreach.start': { EN: 'Start', AR: 'بدء' },
  'owner.outreach.save': { EN: 'Save', AR: 'حفظ' },
  'owner.outreach.back': { EN: 'Back', AR: 'رجوع' },
  'owner.outreach.edit': { EN: 'Edit', AR: 'تعديل' },
  'owner.outreach.view': { EN: 'View', AR: 'عرض' },
  'owner.outreach.yes': { EN: 'Yes', AR: 'نعم' },
  'owner.outreach.no': { EN: 'No', AR: 'لا' },
  'owner.outreach.created': { EN: 'Created', AR: 'تاريخ الإنشاء' },
  'owner.outreach.default': { EN: 'Default', AR: 'افتراضي' },
  'owner.outreach.tier': { EN: 'tier', AR: 'المستوى' },
  'owner.outreach.country': { EN: 'Country', AR: 'الدولة' },
  'owner.outreach.country.SA': { EN: 'Saudi Arabia', AR: 'المملكة العربية السعودية' },

  'owner.outreach.col.entity': { EN: 'Entity', AR: 'الجهة' },
  'owner.outreach.col.entities': { EN: 'Entities', AR: 'الجهات' },
  'owner.outreach.col.type': { EN: 'Type', AR: 'النوع' },
  'owner.outreach.col.government': { EN: 'Government status', AR: 'الصفة الحكومية' },
  'owner.outreach.col.prospects': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.col.tenant': { EN: 'ArchMind workspace', AR: 'مساحة العمل في ArchMind' },
  'owner.outreach.col.outreach': { EN: 'Outreach', AR: 'التواصل' },
  'owner.outreach.col.name': { EN: 'Name', AR: 'الاسم' },
  'owner.outreach.col.role': { EN: 'Role', AR: 'الدور' },
  'owner.outreach.col.seniority': { EN: 'Seniority', AR: 'المستوى الوظيفي' },
  'owner.outreach.col.employment': { EN: 'Current employment', AR: 'الوضع الوظيفي الحالي' },
  'owner.outreach.col.email': { EN: 'Email', AR: 'البريد الإلكتروني' },
  'owner.outreach.col.relevance': { EN: 'Relevance', AR: 'درجة الملاءمة' },
  'owner.outreach.col.stage': { EN: 'Stage', AR: 'المرحلة' },
  'owner.outreach.col.recipient': { EN: 'Recipient', AR: 'المستلم' },
  'owner.outreach.col.subject': { EN: 'Subject', AR: 'الموضوع' },
  'owner.outreach.col.generator': { EN: 'Written by', AR: 'كُتبت بواسطة' },

  'owner.outreach.field.name_en': { EN: 'Name (English)', AR: 'الاسم (بالإنجليزية)' },
  'owner.outreach.field.name_ar': { EN: 'Name (Arabic)', AR: 'الاسم (بالعربية)' },
  'owner.outreach.field.aliases': { EN: 'Other names / abbreviations (comma-separated)', AR: 'أسماء أخرى أو اختصارات (مفصولة بفواصل)' },
  'owner.outreach.field.website': { EN: 'Official website', AR: 'الموقع الرسمي' },
  'owner.outreach.field.sector': { EN: 'Sector', AR: 'القطاع' },
  'owner.outreach.field.city': { EN: 'City', AR: 'المدينة' },
  'owner.outreach.field.query': { EN: 'Focus (optional)', AR: 'التركيز (اختياري)' },
  'owner.outreach.field.full_name': { EN: 'Full name', AR: 'الاسم الكامل' },
  'owner.outreach.field.full_name_ar': { EN: 'Full name (Arabic)', AR: 'الاسم الكامل (بالعربية)' },
  'owner.outreach.field.job_title': { EN: 'Job title', AR: 'المسمى الوظيفي' },
  'owner.outreach.field.email': { EN: 'Professional email', AR: 'البريد الإلكتروني المهني' },
  'owner.outreach.field.profile_url': { EN: 'Public professional profile URL', AR: 'رابط الملف المهني العام' },
  'owner.outreach.field.linkedin_url': { EN: 'LinkedIn URL (if you have it)', AR: 'رابط LinkedIn (إن توفر لديك)' },
  'owner.outreach.field.source_url': { EN: 'Where you found this (URL)', AR: 'مصدر المعلومة (رابط)' },
  'owner.outreach.field.notes': { EN: 'Notes', AR: 'ملاحظات' },
  'owner.outreach.email_rule': { EN: 'Only an address the person published or gave you. Never a guessed address.', AR: 'فقط عنوان نشره الشخص أو زوّدك به، وليس عنواناً مُخمَّناً.' },
  'owner.outreach.from_title': { EN: 'From the job title', AR: 'وفق المسمى الوظيفي' },

  ...fam('owner.outreach.type', { auto: ['Detect from the name', 'يُحدَّد من الاسم'], MINISTRY: ['Ministries', 'الوزارات'], AUTHORITY: ['Authorities', 'الهيئات'], FUND: ['Funds', 'الصناديق'], COMMISSION: ['Commissions', 'المفوضيات'], AGENCY: ['Agencies', 'الوكالات'], CENTER: ['Centers', 'المراكز'], PROGRAM: ['Programs', 'البرامج'], CORPORATION: ['Public corporations', 'المؤسسات العامة'], COUNCIL: ['Councils', 'المجالس'], PLATFORM: ['National platforms', 'المنصات الوطنية'], OTHER_PUBLIC: ['Other public entities', 'جهات عامة أخرى'] }),
  ...fam('owner.outreach.gov', { CONFIRMED_GOVERNMENT: ['Government (confirmed)', 'حكومية (مؤكدة)'], LIKELY_GOVERNMENT: ['Likely government', 'يُرجَّح أنها حكومية'], UNVERIFIED: ['Not verified', 'غير مُتحقق منها'], NOT_GOVERNMENT: ['Not government', 'ليست جهة حكومية'] }),
  ...fam('owner.outreach.match', { EXISTING_TENANT: ['Workspace exists', 'لها مساحة عمل'], POSSIBLE_MATCH: ['Possible match', 'تطابق محتمل'], NEW_ENTITY: ['No workspace yet', 'لا توجد مساحة عمل بعد'] }),
  ...fam('owner.outreach.match_help', { EXISTING_TENANT: ['An ArchMind workspace already exists for this organisation (same website or name). Link it instead of creating a duplicate.', 'توجد مساحة عمل في ArchMind لهذه الجهة (الموقع نفسه أو الاسم نفسه). اربطها بدلاً من إنشاء مساحة مكررة.'], POSSIBLE_MATCH: ['A workspace with a similar name exists. Link it if it is the same organisation, or confirm it is different when creating one.', 'توجد مساحة عمل باسم مشابه. اربطها إن كانت الجهة نفسها، أو أكّد أنها مختلفة عند الإنشاء.'], NEW_ENTITY: ['No ArchMind workspace matches this organisation.', 'لا توجد مساحة عمل في ArchMind تطابق هذه الجهة.'] }),
  ...fam('owner.outreach.entity_outreach', { NOT_STARTED: ['Not started', 'لم يبدأ'], PROSPECTS_FOUND: ['Prospects found', 'عُثر على عملاء محتملين'], PREPARING: ['Preparing outreach', 'جارٍ إعداد التواصل'], CONTACTED: ['Contacted', 'تم التواصل'], ACTIVATED: ['Activated', 'مفعَّل'], ENGAGED: ['Engaged', 'متفاعل'] }),

  // Entity detail
  'owner.outreach.entity.help': { EN: 'The entity, its prospects grouped by role, and its ArchMind workspace. Create or link the workspace, enrich it from public sources and prepare EA Views before inviting anyone.', AR: 'الجهة وعملاؤها المحتملون مصنّفون حسب الدور، ومساحة عملها في ArchMind. أنشئ مساحة العمل أو اربطها، وأثرِها من المصادر العامة، وجهّز العروض المعمارية قبل دعوة أي شخص.' },
  'owner.outreach.entity.overview': { EN: 'Organisation', AR: 'الجهة' },
  'owner.outreach.entity.tenant': { EN: 'ArchMind workspace', AR: 'مساحة العمل في ArchMind' },
  'owner.outreach.entity.tenant_help': { EN: 'Uses the Owner Console tenant creation, AI enrichment (with your review before anything is written) and EA View preparation. Never creates a duplicate.', AR: 'يستخدم إنشاء المساحات في وحدة تحكم المالك، والإثراء بالذكاء الاصطناعي (مع مراجعتك قبل حفظ أي شيء)، وتجهيز العروض المعمارية. لا يُنشئ مساحة مكررة أبداً.' },
  'owner.outreach.entity.meta_model': { EN: 'Meta Model published', AR: 'النموذج الوصفي منشور' },
  'owner.outreach.entity.enrichment': { EN: 'AI enrichment', AR: 'الإثراء بالذكاء الاصطناعي' },
  'owner.outreach.entity.not_enriched': { EN: 'Not enriched yet', AR: 'لم يتم الإثراء بعد' },
  'owner.outreach.entity.objects': { EN: 'Repository objects', AR: 'عناصر المستودع' },
  'owner.outreach.entity.public_objects': { EN: 'From public research', AR: 'من البحث في المصادر العامة' },
  'owner.outreach.entity.views': { EN: 'Prepared EA Views', AR: 'العروض المعمارية المُعدّة' },
  'owner.outreach.entity.view_tenant': { EN: 'Open workspace', AR: 'فتح مساحة العمل' },
  'owner.outreach.entity.enrich': { EN: 'Enrich from public sources', AR: 'الإثراء من المصادر العامة' },
  'owner.outreach.entity.enrich_started': { EN: 'Enrichment started. Review its findings before they are written to the repository.', AR: 'بدأ الإثراء. راجع نتائجه قبل حفظها في المستودع.' },
  'owner.outreach.entity.review_enrichment': { EN: 'Review enrichment', AR: 'مراجعة الإثراء' },
  'owner.outreach.entity.prepare_views': { EN: 'Prepare EA Views', AR: 'تجهيز العروض المعمارية' },
  'owner.outreach.entity.views_prepared': { EN: '{n} views prepared ({skipped} skipped: not enough data).', AR: 'تم تجهيز {n} عرض (تم تخطي {skipped} لعدم كفاية البيانات).' },
  'owner.outreach.entity.create_tenant': { EN: 'Create ArchMind workspace', AR: 'إنشاء مساحة عمل في ArchMind' },
  'owner.outreach.entity.confirm_not_duplicate': { EN: 'I checked the similar workspace: this is a different organisation.', AR: 'تحققت من مساحة العمل المشابهة: هذه جهة مختلفة.' },
  'owner.outreach.entity.link': { EN: 'Link', AR: 'ربط' },
  'owner.outreach.entity.linked': { EN: 'Workspace linked.', AR: 'تم ربط مساحة العمل.' },
  'owner.outreach.entity.rematch': { EN: 'Check again', AR: 'إعادة التحقق' },
  'owner.outreach.entity.prospects': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.entity.prospects_help': { EN: 'Grouped by role. Click a person to see the evidence and why they are relevant. Select people to prepare invitations and emails.', AR: 'مصنّفون حسب الدور. انقر على الشخص لعرض الأدلة وسبب ملاءمته. حدّد الأشخاص لإعداد الدعوات والرسائل.' },
  'owner.outreach.entity.no_prospects': { EN: 'No prospects yet. Research prospects or add one you know.', AR: 'لا يوجد عملاء محتملون بعد. ابحث عنهم أو أضف شخصاً تعرفه.' },
  'owner.outreach.entity.suppress': { EN: 'Do not contact this entity', AR: 'عدم التواصل مع هذه الجهة' },
  'owner.outreach.entity.unsuppress': { EN: 'Allow contact again', AR: 'السماح بالتواصل مجدداً' },
  'owner.outreach.entity.suppress_help': { EN: 'No one at this entity will be researched, invited or emailed; unsent emails are cancelled.', AR: 'لن يتم البحث عن أي شخص في هذه الجهة أو دعوته أو مراسلته، وتُلغى الرسائل غير المرسلة.' },
  'owner.outreach.entity.unsuppress_help': { EN: 'People who opted out themselves stay suppressed.', AR: 'يبقى من طلب إيقاف الرسائل بنفسه ضمن قائمة عدم التواصل.' },
  'owner.outreach.entity.suppressed_note': { EN: 'This entity is on the do-not-contact list', AR: 'هذه الجهة مدرجة في قائمة عدم التواصل' },
  'owner.outreach.entity.confirm_government': { EN: 'Confirm government status', AR: 'تأكيد الصفة الحكومية' },
  'owner.outreach.entity.confirm_government_help': { EN: 'Normally computed from the official domain and name. Set it only when you have checked the organisation yourself; the reason is recorded.', AR: 'تُحسب عادةً من النطاق الرسمي والاسم. لا تحدّدها إلا بعد التحقق من الجهة بنفسك، ويُسجَّل السبب.' },
  'owner.outreach.entity.keep_computed': { EN: 'Keep the computed status', AR: 'الإبقاء على الحالة المحسوبة' },
  ...fam('owner.outreach.skip', { NOT_FOUND: ['Entity not found.', 'لم يتم العثور على الجهة.'], ENTITY_SUPPRESSED: ['The entity is on the do-not-contact list.', 'الجهة مدرجة في قائمة عدم التواصل.'], NOT_GOVERNMENT: ['The entity is not a government organisation.', 'الجهة ليست جهة حكومية.'], DISCOVERY_RUNNING: ['Research is already running for this entity.', 'البحث جارٍ بالفعل لهذه الجهة.'] }),

  // Discovery jobs
  ...fam('owner.outreach.job.mode', { ENTITIES: ['Entity discovery', 'اكتشاف الجهات'], PROFESSIONALS: ['Prospect research', 'البحث عن العملاء المحتملين'] }),
  ...fam('owner.outreach.job.status', { QUEUED: ['Queued', 'في الانتظار'], ENTITY_DISCOVERY: ['Searching', 'جارٍ البحث'], PROFESSIONAL_DISCOVERY: ['Searching', 'جارٍ البحث'], VERIFICATION: ['Reading sources', 'جارٍ قراءة المصادر'], CLASSIFICATION: ['Verifying', 'جارٍ التحقق'], DEDUPLICATION: ['Checking duplicates', 'جارٍ فحص التكرار'], ENTITY_MAPPING: ['Saving', 'جارٍ الحفظ'], READY_FOR_REVIEW: ['Ready for review', 'جاهز للمراجعة'], COMPLETED: ['Reviewed', 'تمت المراجعة'], FAILED: ['Failed', 'فشل'], CANCELLED: ['Cancelled', 'ملغى'] }),
  ...fam('owner.outreach.job.stage', { ENTITY_DISCOVERY: ['Public search', 'البحث العام'], PROFESSIONAL_DISCOVERY: ['Official site + public search', 'الموقع الرسمي والبحث العام'], VERIFICATION: ['Candidates with evidence', 'مرشحون مع الأدلة'], CLASSIFICATION: ['Verification and role', 'التحقق والدور'], DEDUPLICATION: ['Duplicates and suppression', 'التكرار وقائمة عدم التواصل'], ENTITY_MAPPING: ['Grouped by entity', 'التجميع حسب الجهة'] }),
  'owner.outreach.job.results': { EN: '{created} new, {merged} updated, {dropped} dropped (not verifiable), {suppressed} on the do-not-contact list', AR: '{created} جديد، {merged} محدَّث، {dropped} مستبعد (تعذّر التحقق)، {suppressed} في قائمة عدم التواصل' },
  'owner.outreach.job.limitations': { EN: 'Limits of this research', AR: 'حدود هذا البحث' },
  'owner.outreach.job.rejected': { EN: 'Dropped candidates', AR: 'المرشحون المستبعدون' },
  'owner.outreach.job.sources': { EN: 'Sources read', AR: 'المصادر المقروءة' },
  'owner.outreach.job.mark_reviewed': { EN: 'Mark as reviewed', AR: 'تحديد كمراجَع' },

  // Prospects
  'owner.outreach.prospect': { EN: 'Prospect', AR: 'عميل محتمل' },
  'owner.outreach.prospects.title': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.prospects.subtitle': { EN: 'EA, digital transformation and innovation professionals in Saudi government entities', AR: 'مختصو البنية المؤسسية والتحول الرقمي والابتكار في الجهات الحكومية السعودية' },
  'owner.outreach.prospects.help': { EN: 'Only professional information from public sources (or entered by you), each with its source. Emails are never guessed. A person whose current role is uncertain must be confirmed by you before outreach.', AR: 'معلومات مهنية فقط من مصادر عامة (أو أدخلتها أنت)، ولكل معلومة مصدرها. لا يتم تخمين عناوين البريد الإلكتروني أبداً. يجب أن تؤكد بنفسك الدور الحالي لأي شخص غير مؤكد قبل التواصل معه.' },
  'owner.outreach.prospects.ask': { EN: 'Find', AR: 'ابحث' },
  'owner.outreach.prospects.ask_help': { EN: 'Describe who you are looking for, for example "EA Directors in Saudi ministries". ArchMind turns it into filters you can adjust.', AR: 'صِف من تبحث عنه، مثل "مديري البنية المؤسسية في الوزارات السعودية"، وسيحوّله ArchMind إلى عوامل تصفية يمكنك تعديلها.' },
  'owner.outreach.prospects.ask_example': { EN: 'Find Enterprise Architecture Heads in government authorities', AR: 'ابحث عن رؤساء البنية المؤسسية في الهيئات الحكومية' },
  'owner.outreach.prospects.apply': { EN: 'Apply', AR: 'تطبيق' },
  'owner.outreach.prospects.understood': { EN: 'Understood as', AR: 'فُهم على أنه' },
  'owner.outreach.prospects.discover_matching': { EN: 'Research matching entities', AR: 'البحث في الجهات المطابقة' },
  'owner.outreach.prospects.no_entities': { EN: 'No directory entities match; discover or add entities first.', AR: 'لا توجد جهات مطابقة في الدليل؛ اكتشف الجهات أو أضفها أولاً.' },
  'owner.outreach.prospects.search': { EN: 'Search name or title', AR: 'ابحث بالاسم أو المسمى الوظيفي' },
  'owner.outreach.prospects.empty': { EN: 'No prospects match.', AR: 'لا يوجد عملاء محتملون مطابقون.' },
  'owner.outreach.prospects.add': { EN: 'Add prospect', AR: 'إضافة عميل محتمل' },
  'owner.outreach.prospects.add_help': { EN: 'Professional details only. An email you enter is marked as provided by you. A person who asked not to be contacted cannot be added again.', AR: 'البيانات المهنية فقط. يُعلَّم البريد الإلكتروني الذي تُدخله بأنه مقدَّم منك. لا يمكن إضافة شخص طلب عدم التواصل معه مرة أخرى.' },
  ...fam('owner.outreach.role', { ENTERPRISE_ARCHITECTURE: ['Enterprise Architecture', 'البنية المؤسسية'], DIGITAL_TRANSFORMATION: ['Digital Transformation', 'التحول الرقمي'], DIGITAL_INNOVATION: ['Digital Innovation', 'الابتكار الرقمي'], DIGITAL_STRATEGY: ['Digital Strategy', 'الاستراتيجية الرقمية'], TECHNOLOGY_STRATEGY: ['Technology Strategy', 'استراتيجية التقنية'], OTHER_RELEVANT: ['Other relevant roles', 'أدوار أخرى ذات صلة'] }),
  ...fam('owner.outreach.role_short', { ENTERPRISE_ARCHITECTURE: ['EA', 'البنية المؤسسية'], DIGITAL_TRANSFORMATION: ['DT', 'التحول الرقمي'], DIGITAL_INNOVATION: ['Innovation', 'الابتكار'], DIGITAL_STRATEGY: ['Digital strategy', 'الاستراتيجية الرقمية'], TECHNOLOGY_STRATEGY: ['Tech strategy', 'استراتيجية التقنية'], OTHER_RELEVANT: ['Other', 'أخرى'] }),
  ...fam('owner.outreach.seniority', { EXECUTIVE: ['Executive', 'قيادة تنفيذية'], DIRECTOR: ['Director', 'مدير'], HEAD: ['Head', 'رئيس'], MANAGER: ['Manager', 'مدير قسم'], CONSULTANT: ['Consultant', 'مستشار'], ARCHITECT: ['Architect', 'معماري'], OTHER: ['Other', 'أخرى'] }),
  ...fam('owner.outreach.employment', { CURRENT_CONFIRMED: ['Current (official site)', 'حالي (الموقع الرسمي)'], CURRENT_LIKELY: ['Likely current', 'يُرجَّح أنه حالي'], CURRENT_STATUS_UNCERTAIN: ['Current role uncertain', 'الدور الحالي غير مؤكد'], FORMER: ['Former role', 'دور سابق'] }),
  ...fam('owner.outreach.email_status', { VERIFIED_PUBLIC: ['Published', 'منشور علناً'], OWNER_PROVIDED: ['Provided by you', 'مقدَّم منك'], UNAVAILABLE: ['Unavailable', 'غير متاح'] }),
  ...fam('owner.outreach.stage', { DISCOVERED: ['Discovered', 'مكتشَف'], VERIFIED: ['Verified', 'مُتحقق منه'], SHORTLISTED: ['Shortlisted', 'في القائمة المختصرة'], TENANT_PREPARED: ['Workspace prepared', 'مساحة العمل مُعدّة'], INVITATION_PREPARED: ['Invitation prepared', 'الدعوة مُعدّة'], OUTREACH_READY: ['Email ready', 'الرسالة جاهزة'], CONTACTED: ['Contacted (other channel)', 'تم التواصل (قناة أخرى)'], INVITED: ['Invited', 'مدعو'], ACTIVATED: ['Activated', 'مفعَّل'], ENGAGED: ['Engaged', 'متفاعل'], NOT_INTERESTED: ['Not interested', 'غير مهتم'], INVALID: ['Invalid', 'غير صالح'], DO_NOT_CONTACT: ['Do not contact', 'عدم التواصل'] }),
  'owner.outreach.source': { EN: 'Source', AR: 'المصدر' },
  ...fam('owner.outreach.source', { AI_DISCOVERY: ['Public-source research', 'البحث في المصادر العامة'], OWNER: ['Entered by you', 'أدخلته أنت'] }),
  'owner.outreach.classification': { EN: 'Why this role', AR: 'سبب تصنيف الدور' },
  ...fam('owner.outreach.basis', { LEXICON: ['From the job title', 'من المسمى الوظيفي'], LEXICON_AND_AI: ['From the job title (AI agrees)', 'من المسمى الوظيفي (ويتفق معه الذكاء الاصطناعي)'], AI_PROPOSED: ['Proposed by AI - confirm', 'مقترح من الذكاء الاصطناعي - يحتاج تأكيداً'], OWNER: ['Set by you', 'حدّدته أنت'], NONE: ['Not classified', 'غير مصنّف'] }),
  'owner.outreach.owner_verified': { EN: 'Confirmed by you', AR: 'أكّدته أنت' },
  'owner.outreach.last_verified': { EN: 'Last verified', AR: 'آخر تحقق' },
  'owner.outreach.confidence': { EN: 'Confidence', AR: 'درجة الثقة' },
  'owner.outreach.email_source': { EN: 'Where the email is published', AR: 'مكان نشر البريد الإلكتروني' },
  'owner.outreach.profile': { EN: 'Profiles', AR: 'الملفات المهنية' },
  'owner.outreach.profile_link': { EN: 'Professional profile', AR: 'الملف المهني' },
  'owner.outreach.retain_until': { EN: 'Kept until', AR: 'يُحتفظ به حتى' },
  'owner.outreach.relevance': { EN: 'Relevance', AR: 'درجة الملاءمة' },
  'owner.outreach.relevance_help': { EN: 'The sum of six factors, each explained: role, seniority, current employment, government organisation, source quality and how recent the evidence is. No hidden score.', AR: 'مجموع ستة عوامل موضّحة: الدور، والمستوى الوظيفي، والوضع الوظيفي الحالي، والصفة الحكومية للجهة، وجودة المصدر، وحداثة الأدلة. لا توجد درجة خفية.' },
  ...fam('owner.outreach.factor', { ROLE: ['Role', 'الدور'], SENIORITY: ['Seniority', 'المستوى الوظيفي'], CURRENT_EMPLOYMENT: ['Current employment', 'الوضع الوظيفي الحالي'], GOVERNMENT_ORGANIZATION: ['Government organisation', 'الصفة الحكومية للجهة'], SOURCE_QUALITY: ['Source quality', 'جودة المصدر'], EVIDENCE_RECENCY: ['Evidence recency', 'حداثة الأدلة'] }),
  'owner.outreach.evidence': { EN: 'Evidence', AR: 'الأدلة' },
  'owner.outreach.no_evidence': { EN: 'No public source: entered by you.', AR: 'لا يوجد مصدر عام: أدخلته أنت.' },
  'owner.outreach.read_on': { EN: 'read on', AR: 'قُرئ في' },
  'owner.outreach.dated': { EN: 'dated', AR: 'بتاريخ' },
  'owner.outreach.eligibility': { EN: 'Can this person be emailed?', AR: 'هل يمكن مراسلة هذا الشخص؟' },
  'owner.outreach.eligible': { EN: 'Yes: all checks pass. The email still needs your approval.', AR: 'نعم: اجتاز جميع الفحوصات، ولا تزال الرسالة تحتاج إلى اعتمادك.' },
  'owner.outreach.eligible_short': { EN: 'Ready', AR: 'جاهز' },
  'owner.outreach.suggested_role': { EN: 'Suggested role', AR: 'الدور المقترح' },
  'owner.outreach.messages': { EN: 'Emails', AR: 'الرسائل' },
  'owner.outreach.verify': { EN: 'Confirm current role', AR: 'تأكيد الدور الحالي' },
  'owner.outreach.verify_note': { EN: 'How did you confirm it? (e.g. official page checked today)', AR: 'كيف تحققت من ذلك؟ (مثلاً: راجعت الصفحة الرسمية اليوم)' },
  'owner.outreach.set_stage': { EN: 'Set stage…', AR: 'تحديد المرحلة…' },
  'owner.outreach.dnc.title': { EN: 'Do not contact', AR: 'عدم التواصل' },
  'owner.outreach.dnc.set': { EN: 'Do not contact', AR: 'عدم التواصل' },
  'owner.outreach.dnc.clear': { EN: 'Lift do-not-contact', AR: 'رفع حظر التواصل' },
  'owner.outreach.erase': { EN: 'Erase record', AR: 'حذف السجل' },
  'owner.outreach.erase_reason': { EN: 'Reason (e.g. removal request)', AR: 'السبب (مثلاً: طلب حذف)' },
  'owner.outreach.erase_suppress': { EN: 'Keep a suppression entry (hash only) so this person is never rediscovered or contacted', AR: 'الإبقاء على قيد منع (بصيغة مشفّرة فقط) حتى لا يُكتشف هذا الشخص أو يُتواصل معه مجدداً' },

  // Gates
  ...fam('owner.outreach.blocker', {
    DO_NOT_CONTACT: ['Do not contact', 'عدم التواصل'], ENTITY_SUPPRESSED: ['Entity on the do-not-contact list', 'الجهة في قائمة عدم التواصل'], SUPPRESSED_EMAIL: ['Email address suppressed', 'البريد الإلكتروني ضمن قائمة المنع'],
    SUPPRESSED_PERSON: ['Person suppressed (opted out or erased)', 'الشخص ضمن قائمة المنع (طلب الإيقاف أو الحذف)'], SUPPRESSED_DOMAIN: ['Domain suppressed', 'النطاق ضمن قائمة المنع'], NOT_GOVERNMENT: ['Entity not confirmed as government', 'لم تُؤكَّد الصفة الحكومية للجهة'],
    FORMER_EMPLOYEE: ['Role is a former one', 'الدور سابق'], EMPLOYMENT_UNVERIFIED: ['Confirm the current role first', 'أكّد الدور الحالي أولاً'], EMAIL_UNAVAILABLE: ['No legitimate email', 'لا يوجد بريد إلكتروني مشروع'],
    NO_TENANT: ['Create or link the workspace first', 'أنشئ مساحة العمل أو اربطها أولاً'], INVALID: ['Marked invalid', 'مُعلَّم كغير صالح'], NOT_INTERESTED: ['Not interested', 'غير مهتم'], ALREADY_ACTIVATED: ['Already a user / already emailed', 'مستخدم بالفعل أو تمت مراسلته'],
    NO_INVITATION: ['Prepare the invitation first', 'أعدّ الدعوة أولاً'], INVITATION_FAILED: ['The invitation could not be renewed', 'تعذّر تجديد الدعوة'], ATTACHMENT_UNAVAILABLE: ['The presentation could not be read', 'تعذّرت قراءة العرض التقديمي'],
  }),

  // Invitations
  'owner.outreach.invite': { EN: 'Prepare invitations', AR: 'إعداد الدعوات' },
  'owner.outreach.invite_help': { EN: 'Creates a pending invitation in the entity\'s workspace with a single-use activation link. It is not emailed here: the link goes in the outreach email you approve. Nobody becomes an administrator unless you choose it and confirm with your password.', AR: 'يُنشئ دعوة معلّقة في مساحة عمل الجهة برابط تفعيل يُستخدم مرة واحدة. لا تُرسل الدعوة من هنا، بل يُضمَّن الرابط في رسالة التواصل التي تعتمدها. لا يصبح أي شخص مسؤولاً إلا إذا اخترت ذلك وأكّدته بكلمة المرور.' },
  'owner.outreach.invite.access_level': { EN: 'Access level', AR: 'مستوى الوصول' },
  'owner.outreach.invite.role': { EN: 'Role', AR: 'الدور' },
  'owner.outreach.invite.suggested': { EN: 'Suggested for this role', AR: 'المقترح لهذا الدور' },
  'owner.outreach.invite.keep': { EN: 'Keep the current choice', AR: 'الإبقاء على الاختيار الحالي' },
  'owner.outreach.invite.elevated': { EN: 'Administrator access is a separate decision. Confirm it with your password.', AR: 'صلاحية المسؤول قرار مستقل، أكّده بكلمة المرور.' },
  'owner.outreach.invite.prepare': { EN: 'Prepare', AR: 'إعداد' },
  'owner.outreach.invite.done': { EN: '{n} invitations prepared.', AR: 'تم إعداد {n} دعوة.' },
  'owner.outreach.invite.not_emailed': { EN: 'No email was sent. Prepare outreach to write the email that carries the link.', AR: 'لم تُرسل أي رسالة. أعدّ التواصل لكتابة الرسالة التي تتضمن الرابط.' },
  ...fam('owner.outreach.invite.status', { PREPARED: ['Prepared', 'تم الإعداد'], BLOCKED: ['Not prepared', 'لم يتم الإعداد'], FAILED: ['Failed', 'فشل'], NOT_FOUND: ['Not found', 'غير موجود'] }),
  ...fam('owner.outreach.legacy', { ARCHITECT: ['Standard user', 'مستخدم عادي'], REVIEWER: ['Reviewer', 'مراجِع'], TENANT_ADMIN: ['Administrator', 'مسؤول'], SUPERADMIN: ['Super administrator', 'مسؤول أعلى'] }),
  ...fam('owner.outreach.template', { 'chief-enterprise-architect': ['Chief Enterprise Architect', 'كبير المعماريين المؤسسيين'], 'ea-contributor': ['EA contributor', 'مساهم في البنية المؤسسية'], 'ea-reviewer': ['EA reviewer', 'مراجِع البنية المؤسسية'], 'ea-viewer': ['EA viewer', 'مطّلع على البنية المؤسسية'], 'executive-viewer': ['Executive viewer', 'مطّلع تنفيذي'], 'guest-viewer': ['Guest viewer', 'مطّلع ضيف'], 'tenant-administrator': ['Workspace administrator', 'مسؤول مساحة العمل'] }),

  // Outreach preparation
  'owner.outreach.prepare_outreach': { EN: 'Prepare outreach', AR: 'إعداد التواصل' },
  'owner.outreach.prepare_outreach_help': { EN: 'Writes a personalised draft per person (role-aware, only facts you can check, stating the workspace was prepared from public information). Nothing is sent: you review, edit and approve each email in the campaign.', AR: 'يكتب مسودة مخصّصة لكل شخص (مراعية لدوره، وتقتصر على حقائق يمكنك التحقق منها، وتوضح أن مساحة العمل أُعدّت من معلومات عامة). لا يُرسل شيء: تراجع كل رسالة وتعدّلها وتعتمدها ضمن الحملة.' },
  'owner.outreach.campaign': { EN: 'Campaign', AR: 'الحملة' },
  'owner.outreach.language': { EN: 'Language', AR: 'اللغة' },
  'owner.outreach.language.auto': { EN: 'From the person\'s title', AR: 'حسب المسمى الوظيفي للشخص' },
  'owner.outreach.generate_drafts': { EN: 'Generate drafts', AR: 'إنشاء المسودات' },
  'owner.outreach.drafts_done': { EN: '{n} drafts ready for review.', AR: '{n} مسودة جاهزة للمراجعة.' },
  ...fam('owner.outreach.draft_status', { DRAFTED: ['Drafted', 'تم إنشاء المسودة'], EXISTS: ['Already has an email in this campaign', 'لديه رسالة في هذه الحملة بالفعل'], BLOCKED: ['Not drafted', 'لم تُنشأ مسودة'] }),
  'owner.outreach.open_campaign': { EN: 'Open campaign', AR: 'فتح الحملة' },

  // Campaigns
  'owner.outreach.campaigns.title': { EN: 'Campaigns', AR: 'الحملات' },
  'owner.outreach.campaigns.subtitle': { EN: 'Prepared, approved and sent outreach with activation and engagement', AR: 'التواصل المُعدّ والمعتمد والمرسل مع التفعيل والتفاعل' },
  'owner.outreach.campaigns.help': { EN: 'A campaign groups the entities and people you reach in one effort and tracks them from workspace preparation to activation and use.', AR: 'تجمع الحملة الجهات والأشخاص الذين تتواصل معهم في جهد واحد، وتتابعهم من تجهيز مساحة العمل حتى التفعيل والاستخدام.' },
  'owner.outreach.campaigns.new': { EN: 'New campaign', AR: 'حملة جديدة' },
  'owner.outreach.campaigns.name': { EN: 'Campaign name', AR: 'اسم الحملة' },
  'owner.outreach.campaigns.name_example': { EN: 'KSA Government EA Outreach — Q4 2026', AR: 'التواصل مع الجهات الحكومية - الربع الرابع 2026' },
  'owner.outreach.campaigns.description': { EN: 'Description', AR: 'الوصف' },
  'owner.outreach.campaigns.emails': { EN: 'Emails', AR: 'الرسائل' },
  'owner.outreach.campaigns.empty': { EN: 'No campaigns yet.', AR: 'لا توجد حملات بعد.' },
  ...fam('owner.outreach.campaign_status', { DRAFT: ['Draft', 'مسودة'], ACTIVE: ['Active', 'نشطة'], CLOSED: ['Closed', 'مغلقة'] }),
  'owner.outreach.campaign.help': { EN: 'Review each email, approve it, then send approved emails with your password. Every check (do-not-contact, verification, email legitimacy, limits) runs again at send time.', AR: 'راجع كل رسالة واعتمدها، ثم أرسل الرسائل المعتمدة بكلمة المرور. تُعاد جميع الفحوصات (عدم التواصل، والتحقق، ومشروعية البريد، والحدود) عند الإرسال.' },
  'owner.outreach.campaign.activate': { EN: 'Activate', AR: 'تفعيل' },
  'owner.outreach.campaign.close': { EN: 'Close campaign', AR: 'إغلاق الحملة' },
  'owner.outreach.campaign.emails': { EN: 'Emails', AR: 'الرسائل' },
  'owner.outreach.campaign.emails_help': { EN: 'Select drafts to approve, or approved emails to send.', AR: 'حدّد المسودات لاعتمادها، أو الرسائل المعتمدة لإرسالها.' },
  'owner.outreach.campaign.no_emails': { EN: 'No emails yet. Select prospects on an entity or the Prospects page and prepare outreach.', AR: 'لا توجد رسائل بعد. حدّد العملاء المحتملين من صفحة الجهة أو صفحة العملاء المحتملين ثم أعدّ التواصل.' },
  ...fam('owner.outreach.metric', { entities: ['Entities selected', 'الجهات المختارة'], prospects: ['Prospects selected', 'العملاء المحتملون المختارون'], tenants: ['Workspaces', 'مساحات العمل'], enriched: ['Workspaces enriched', 'مساحات عمل أُثريت'], invitations: ['Invitations prepared', 'الدعوات المُعدّة'], prepared: ['Emails prepared', 'الرسائل المُعدّة'], approved: ['Emails approved', 'الرسائل المعتمدة'], sent: ['Emails sent', 'الرسائل المرسلة'], failed: ['Delivery failed', 'تعذّر التسليم'], activated: ['Activated', 'مفعَّلون'], first_login: ['Workspaces with a first sign-in', 'مساحات عمل سُجّل الدخول إليها'], engaged: ['Engaged', 'متفاعلون'] }),
  ...fam('owner.outreach.message_status', { DRAFT: ['Draft', 'مسودة'], APPROVED: ['Approved', 'معتمدة'], SENT: ['Sent', 'مرسلة'], FAILED: ['Failed', 'فشلت'], CANCELLED: ['Cancelled', 'ملغاة'] }),
  ...fam('owner.outreach.generator', { AI: ['AI (reviewed by you)', 'الذكاء الاصطناعي (بمراجعتك)'], TEMPLATE: ['Standard template', 'قالب قياسي'] }),
  ...fam('owner.outreach.result', { SENT: ['Sent', 'أُرسلت'], APPROVED: ['Approved', 'اعتُمدت'], SKIPPED: ['Skipped', 'تم التخطي'], BLOCKED: ['Blocked', 'محظورة'], FAILED: ['Failed', 'فشلت'] }),
  'owner.outreach.approve': { EN: 'Approve', AR: 'اعتماد' },
  'owner.outreach.approve.done': { EN: '{n} emails approved.', AR: 'تم اعتماد {n} رسالة.' },
  'owner.outreach.send': { EN: 'Send', AR: 'إرسال' },
  'owner.outreach.send.title': { EN: 'Send {n} approved emails', AR: 'إرسال {n} رسالة معتمدة' },
  'owner.outreach.send.help': { EN: 'Each email gets a fresh single-use activation link and the presentation. Emails that no longer pass the checks are not sent.', AR: 'تحصل كل رسالة على رابط تفعيل جديد يُستخدم مرة واحدة وعلى العرض التقديمي. لا تُرسل الرسائل التي لم تعد تجتاز الفحوصات.' },
  'owner.outreach.send.done': { EN: '{n} emails sent.', AR: 'تم إرسال {n} رسالة.' },
  'owner.outreach.send.remaining': { EN: '{n} more can be sent today', AR: 'يمكن إرسال {n} رسالة أخرى اليوم' },
  'owner.outreach.send.daily_limit': { EN: 'daily sending limit reached', AR: 'تم بلوغ الحد اليومي للإرسال' },
  'owner.outreach.review_edit': { EN: 'Review / edit', AR: 'مراجعة / تعديل' },

  // Email editor
  'owner.outreach.editor.title': { EN: 'Review email', AR: 'مراجعة الرسالة' },
  'owner.outreach.editor.help': { EN: 'Edit anything above the line. The footer (activation link, public-information statement, your contact line and the opt-out link) is added by ArchMind and cannot be removed. Editing an approved email returns it to draft.', AR: 'يمكنك تعديل كل ما فوق الخط. أما التذييل (رابط التفعيل، وبيان المعلومات العامة، وبيانات التواصل، ورابط إيقاف الرسائل) فيضيفه ArchMind ولا يمكن حذفه. تعديل رسالة معتمدة يعيدها إلى مسودة.' },
  'owner.outreach.editor.recipient_help': { EN: 'Changing the address records it as provided by you and re-issues the invitation to it.', AR: 'تغيير العنوان يسجّله كعنوان مقدَّم منك ويعيد إصدار الدعوة إليه.' },
  'owner.outreach.editor.body': { EN: 'Message', AR: 'نص الرسالة' },
  'owner.outreach.editor.footer': { EN: 'Added by ArchMind when sent', AR: 'يضيفه ArchMind عند الإرسال' },
  'owner.outreach.editor.attach': { EN: 'Attach the presentation', AR: 'إرفاق العرض التقديمي' },
  'owner.outreach.editor.material': { EN: 'Presentation', AR: 'العرض التقديمي' },
  'owner.outreach.editor.no_material': { EN: 'None', AR: 'بلا' },
  'owner.outreach.editor.role': { EN: 'Change the invited role', AR: 'تغيير دور المدعو' },
  'owner.outreach.editor.saved': { EN: 'Saved.', AR: 'تم الحفظ.' },
  'owner.outreach.editor.approved': { EN: 'Approved.', AR: 'تم الاعتماد.' },
  'owner.outreach.editor.not_approved': { EN: 'Not approved: the checks below must pass first.', AR: 'لم يتم الاعتماد: يجب اجتياز الفحوصات أدناه أولاً.' },
  'owner.outreach.editor.ai_rejected': { EN: 'the AI text broke a rule, so the standard template was used', AR: 'خالف نص الذكاء الاصطناعي إحدى القواعد، لذا استُخدم القالب القياسي' },
  'owner.outreach.editor.cancel_email': { EN: 'Cancel this email', AR: 'إلغاء هذه الرسالة' },

  // Settings
  'owner.outreach.settings.title': { EN: 'Outreach settings', AR: 'إعدادات التواصل' },
  'owner.outreach.settings.subtitle': { EN: 'Marketing materials, sending and compliance controls, discovery providers', AR: 'المواد التسويقية، وضوابط الإرسال والامتثال، ومزوّدو الاكتشاف' },
  'owner.outreach.settings.help': { EN: 'These controls apply to every campaign. Sending is off until you switch it on and record the legal basis.', AR: 'تنطبق هذه الضوابط على جميع الحملات. يبقى الإرسال متوقفاً حتى تفعّله وتسجّل الأساس النظامي.' },
  'owner.outreach.materials.title': { EN: 'Marketing materials', AR: 'المواد التسويقية' },
  'owner.outreach.materials.help': { EN: 'The default presentation is attached to outreach emails. It is stored once and reused; replace it any time by uploading a new one and making it the default.', AR: 'يُرفق العرض التقديمي الافتراضي برسائل التواصل. يُخزَّن مرة واحدة ويُعاد استخدامه، ويمكنك استبداله في أي وقت برفع عرض جديد وجعله افتراضياً.' },
  'owner.outreach.materials.upload': { EN: 'Upload presentation', AR: 'رفع عرض تقديمي' },
  'owner.outreach.materials.make_default': { EN: 'Make it the default', AR: 'جعله الافتراضي' },
  'owner.outreach.materials.limits': { EN: 'PowerPoint (.pptx) or PDF, up to 15 MB', AR: 'ملف PowerPoint (.pptx) أو PDF، بحد أقصى 15 ميجابايت' },
  'owner.outreach.materials.empty': { EN: 'No presentation uploaded.', AR: 'لم يُرفع أي عرض تقديمي.' },
  'owner.outreach.materials.name': { EN: 'Presentation', AR: 'العرض التقديمي' },
  'owner.outreach.materials.size': { EN: 'Size', AR: 'الحجم' },
  'owner.outreach.materials.download': { EN: 'Download', AR: 'تنزيل' },
  'owner.outreach.materials.set_default': { EN: 'Make default', AR: 'جعله افتراضياً' },
  'owner.outreach.materials.archive': { EN: 'Archive', AR: 'أرشفة' },
  'owner.outreach.materials.uploaded': { EN: 'Presentation uploaded.', AR: 'تم رفع العرض التقديمي.' },
  'owner.outreach.settings.sending': { EN: 'Sending and compliance', AR: 'الإرسال والامتثال' },
  'owner.outreach.settings.sending_help': { EN: 'Rate limits, verification before outreach, retention of never-contacted records and the sender details shown in every email.', AR: 'حدود الإرسال، والتحقق قبل التواصل، ومدة الاحتفاظ بسجلات من لم يُتواصل معهم، وبيانات المرسل الظاهرة في كل رسالة.' },
  'owner.outreach.settings.legal_note': { EN: 'Professional names, titles and work emails are personal data under the Saudi PDPL. Confirm with legal counsel that your outreach has a lawful basis and meets the direct-marketing and anti-spam rules before enabling sending. ArchMind enforces the controls below; it does not decide the legal position.', AR: 'تُعد الأسماء والمسميات الوظيفية وعناوين البريد المهنية بيانات شخصية وفق نظام حماية البيانات الشخصية السعودي. تحقّق مع مستشار قانوني من وجود أساس نظامي للتواصل ومن استيفاء قواعد التسويق المباشر ومكافحة الرسائل الاقتحامية قبل تفعيل الإرسال. يطبّق ArchMind الضوابط أدناه، ولا يحدّد الموقف النظامي.' },
  'owner.outreach.settings.enabled': { EN: 'Sending enabled', AR: 'الإرسال مفعّل' },
  'owner.outreach.settings.legal_basis': { EN: 'Legal basis and approval reference (required to enable sending)', AR: 'الأساس النظامي ومرجع الموافقة (مطلوب لتفعيل الإرسال)' },
  'owner.outreach.settings.daily': { EN: 'Emails per day', AR: 'عدد الرسائل في اليوم' },
  'owner.outreach.settings.batch': { EN: 'Emails per send', AR: 'عدد الرسائل في كل إرسال' },
  'owner.outreach.settings.retention': { EN: 'Keep never-contacted records (days)', AR: 'مدة الاحتفاظ بسجلات من لم يُتواصل معهم (بالأيام)' },
  'owner.outreach.settings.retention_help': { EN: 'Prospects never contacted are deleted after this period; do-not-contact entries are kept as hashes.', AR: 'يُحذف العملاء المحتملون الذين لم يُتواصل معهم بعد هذه المدة، وتُحفظ قيود عدم التواصل بصيغة مشفّرة.' },
  'owner.outreach.settings.require_verification': { EN: 'Require your confirmation of the current role when evidence is not conclusive', AR: 'اشتراط تأكيدك للدور الحالي عندما لا تكون الأدلة قاطعة' },
  'owner.outreach.settings.sender': { EN: 'Sender name', AR: 'اسم المرسل' },
  'owner.outreach.settings.reply_to': { EN: 'Reply-to address', AR: 'عنوان الرد' },
  'owner.outreach.settings.contact': { EN: 'Contact line in the footer', AR: 'بيانات التواصل في التذييل' },
  'owner.outreach.settings.updated': { EN: 'Last updated', AR: 'آخر تحديث' },
  'owner.outreach.settings.saved': { EN: 'Settings saved.', AR: 'تم حفظ الإعدادات.' },
  'owner.outreach.providers.title': { EN: 'Providers', AR: 'المزوّدون' },
  'owner.outreach.providers.help': { EN: 'Discovery uses only compliant public sources. LinkedIn needs an approved partner integration or a licensed provider; ArchMind does not scrape it.', AR: 'يستخدم الاكتشاف مصادر عامة ملتزمة فقط. يتطلب LinkedIn تكاملاً معتمداً من شركائه أو مزوّداً مرخّصاً، ولا يقوم ArchMind بجمع بياناته آلياً.' },
  'owner.outreach.providers.email': { EN: 'Email sender', AR: 'مرسل البريد الإلكتروني' },
  'owner.outreach.providers.email_on': { EN: 'Approved emails can be sent.', AR: 'يمكن إرسال الرسائل المعتمدة.' },
  'owner.outreach.providers.email_off': { EN: 'No SMTP sender is configured: emails can be prepared and approved but not sent.', AR: 'لم يُضبط مرسل SMTP: يمكن إعداد الرسائل واعتمادها دون إرسالها.' },
  ...fam('owner.outreach.provider', { 'web-search-organizations': ['Public web search (entities)', 'البحث العام في الويب (الجهات)'], 'official-site-people': ['Official websites', 'المواقع الرسمية'], 'web-search-people': ['Public web search (professionals)', 'البحث العام في الويب (المختصون)'], linkedin: ['LinkedIn', 'لينكدإن (LinkedIn)'] }),
  ...fam('owner.outreach.provider_detail', { 'web-search-organizations': ['Finds Saudi government organisations in public sources; only cited passages are used.', 'يبحث عن الجهات الحكومية السعودية في المصادر العامة، ويستخدم المقاطع المستشهد بها فقط.'], 'official-site-people': ['Reads the entity\'s own leadership, structure and news pages, respecting robots.txt.', 'يقرأ صفحات القيادة والهيكل التنظيمي والأخبار في موقع الجهة نفسها مع احترام ملف robots.txt.'], 'web-search-people': ['Official announcements, conference and speaker pages, publications. Social networks and contact-data brokers are excluded.', 'الإعلانات الرسمية وصفحات المؤتمرات والمتحدثين والمنشورات، مع استبعاد الشبكات الاجتماعية ووسطاء بيانات الاتصال.'], linkedin: ['Not available: needs an approved LinkedIn partner integration or a licensed provider. ArchMind never scrapes LinkedIn or bypasses its access controls.', 'غير متاح: يتطلب تكاملاً معتمداً من شركاء LinkedIn أو مزوّداً مرخّصاً. لا يجمع ArchMind بيانات LinkedIn آلياً ولا يتجاوز ضوابط الوصول فيه.'] }),
  'owner.outreach.suppression.title': { EN: 'Do-not-contact list', AR: 'قائمة عدم التواصل' },
  'owner.outreach.suppression.help': { EN: 'People, addresses, entities and domains that must never be contacted. People and addresses are kept as hashes, so the list survives erasure without keeping personal data.', AR: 'الأشخاص والعناوين والجهات والنطاقات التي يجب عدم التواصل معها أبداً. يُحفظ الأشخاص والعناوين بصيغة مشفّرة، فتبقى القائمة بعد الحذف دون الاحتفاظ ببيانات شخصية.' },
  'owner.outreach.suppression.domain': { EN: 'Domain', AR: 'النطاق' },
  'owner.outreach.suppression.add': { EN: 'Add domain', AR: 'إضافة نطاق' },
  'owner.outreach.suppression.scope': { EN: 'Type', AR: 'النوع' },
  'owner.outreach.suppression.value': { EN: 'Value', AR: 'القيمة' },
  ...fam('owner.outreach.suppression.scope', { EMAIL: ['Email (hash)', 'بريد إلكتروني (مشفّر)'], PERSON: ['Person (hash)', 'شخص (مشفّر)'], ENTITY: ['Entity', 'جهة'], DOMAIN: ['Domain', 'نطاق'] }),
  ...fam('owner.outreach.suppression.source', { OWNER: ['You', 'أنت'], OPT_OUT: ['Recipient opted out', 'طلب المستلم الإيقاف'], ERASURE: ['Erasure request', 'طلب حذف'] }),
}
