// Government Outreach strings (AR/EN), merged into OWNER_TRANSLATIONS.
// Terms: entity = جهة (a government organisation); tenant = مساحة عمل ArchMind;
// prospect = عميل محتمل.
type S = Record<string, { EN: string; AR: string }>

const fam = (prefix: string, items: Record<string, [string, string]>): S =>
  Object.fromEntries(Object.entries(items).map(([k, [EN, AR]]) => [`${prefix}.${k}`, { EN, AR }]))

export const OUTREACH_TRANSLATIONS: S = {
  'owner.nav.outreach': { EN: 'Government Outreach', AR: 'التواصل مع الجهات الحكومية' },
  'owner.outreach.nav.dashboard': { EN: 'Overview', AR: 'نظرة عامة' },
  'owner.outreach.nav.entities': { EN: 'Entities', AR: 'الجهات' },
  'owner.outreach.nav.prospects': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.nav.campaigns': { EN: 'Campaigns', AR: 'الحملات' },
  'owner.outreach.nav.settings': { EN: 'Settings', AR: 'الإعدادات' },

  'owner.outreach.title': { EN: 'Government Outreach', AR: 'التواصل مع الجهات الحكومية' },
  'owner.outreach.subtitle': { EN: 'KSA government entities, their EA / transformation / innovation leaders, prepared workspaces and approved outreach', AR: 'الجهات الحكومية في المملكة وقادة البنية المؤسسية والتحول الرقمي والابتكار فيها، ومساحات العمل المُعدّة، والتواصل المعتمد' },
  'owner.outreach.help': { EN: 'Find Saudi government entities and the people responsible for enterprise architecture, digital transformation and innovation there, from public sources with evidence. Prepare an ArchMind workspace for the entity, invite selected people securely and send personalised emails only after you approve each one.', AR: 'ابحث عن الجهات الحكومية السعودية والمسؤولين فيها عن البنية المؤسسية والتحول الرقمي والابتكار من مصادر عامة موثّقة بالأدلة. جهّز مساحة عمل ArchMind للجهة، وادعُ الأشخاص المختارين بطريقة آمنة، وأرسل رسائل مخصّصة فقط بعد اعتمادك لكل رسالة.' },
  'owner.outreach.email_not_configured': { EN: 'No email sender is configured (SMTP). You can prepare and approve emails, but nothing can be sent until an administrator configures it.', AR: 'لم يُضبط مرسل البريد الإلكتروني (SMTP). يمكنك إعداد الرسائل واعتمادها، ولكن لا يمكن إرسال أي رسالة حتى يضبطه أحد المسؤولين.' },
  'owner.outreach.web_search_off': { EN: 'Web search is not configured, so discovery can only read official websites. Add entities by hand meanwhile.', AR: 'البحث في الويب غير مفعّل، لذا يقتصر الاكتشاف على قراءة المواقع الرسمية. يمكنك إضافة الجهات يدوياً في الوقت الحالي.' },

  // Dashboard
  'owner.outreach.dash.entities': { EN: 'Government entities', AR: 'الجهات الحكومية' },
  'owner.outreach.dash.professionals': { EN: 'Relevant professionals', AR: 'المختصون ذوو الصلة' },
  'owner.outreach.dash.ea_leaders': { EN: 'EA leaders', AR: 'قادة البنية المؤسسية' },
  'owner.outreach.dash.dt_leaders': { EN: 'Digital transformation leaders', AR: 'قادة التحول الرقمي' },
  'owner.outreach.dash.innovation_leaders': { EN: 'Digital innovation leaders', AR: 'قادة الابتكار الرقمي' },
  'owner.outreach.dash.no_tenant': { EN: 'Entities without an ArchMind workspace', AR: 'جهات بلا مساحة عمل في ArchMind' },
  'owner.outreach.dash.tenants_created': { EN: 'Workspaces created from outreach', AR: 'مساحات عمل أُنشئت من التواصل' },
  'owner.outreach.dash.tenants_enriched': { EN: 'Workspaces enriched', AR: 'مساحات عمل أُثريت' },
  'owner.outreach.dash.invitations_sent': { EN: 'Invitations sent', AR: 'الدعوات المرسلة' },
  'owner.outreach.dash.activated': { EN: 'Activated users', AR: 'المستخدمون المفعّلون' },
  'owner.outreach.dash.engaged_tenants': { EN: 'Engaged workspaces', AR: 'مساحات عمل متفاعلة' },
  'owner.outreach.dash.funnel': { EN: 'Outreach funnel', AR: 'مسار التواصل' },
  'owner.outreach.dash.by_type': { EN: 'Entities by type', AR: 'الجهات حسب النوع' },
  ...fam('owner.outreach.funnel', { DISCOVERED: ['Discovered', 'مكتشَف'], QUALIFIED: ['Qualified', 'مؤهَّل'], TENANT_CREATED: ['Workspace ready', 'مساحة العمل جاهزة'], INVITED: ['Invited', 'مدعو'], ACTIVATED: ['Activated', 'مفعَّل'], ENGAGED: ['Engaged', 'متفاعل'] }),

  // Entities
  'owner.outreach.entities.title': { EN: 'Government Entity Directory', AR: 'دليل الجهات الحكومية' },
  'owner.outreach.entities.subtitle': { EN: 'Saudi public-sector organisations, their prospects, ArchMind workspace and outreach status', AR: 'جهات القطاع العام السعودي، وعملاؤها المحتملون، ومساحة عملها في ArchMind، وحالة التواصل' },
  'owner.outreach.entities.help': { EN: 'Each entity is one organisation. Government status comes from its official domain (gov.sa) or name; private companies are kept out of outreach. An entity links to at most one ArchMind workspace.', AR: 'كل جهة تمثّل منظمة واحدة. تُحدَّد الصفة الحكومية من نطاقها الرسمي (gov.sa) أو من اسمها، وتُستبعد الشركات الخاصة من التواصل. ترتبط كل جهة بمساحة عمل واحدة على الأكثر في ArchMind.' },
  'owner.outreach.entities.add': { EN: 'Add entity', AR: 'إضافة جهة' },
  'owner.outreach.entities.add_help': { EN: 'An organisation already in the directory (same website or name) is not added twice.', AR: 'لا تُضاف الجهة مرتين إذا كانت موجودة في الدليل بالموقع نفسه أو الاسم نفسه.' },
  'owner.outreach.entities.discover': { EN: 'Discover entities', AR: 'اكتشاف الجهات' },
  'owner.outreach.entities.discover_help': { EN: 'Searches public sources for Saudi government organisations of the chosen type. Every organisation found cites the source passage; companies and foreign bodies are left out.', AR: 'يبحث في المصادر العامة عن جهات حكومية سعودية من النوع المختار. تستشهد كل جهة يُعثر عليها بمقطع من مصدرها، وتُستبعد الشركات والجهات الأجنبية.' },
  'owner.outreach.entities.search': { EN: 'Search name or website', AR: 'ابحث بالاسم أو الموقع' },
  'owner.outreach.entities.empty': { EN: 'No entities yet. Add one or discover entities from public sources.', AR: 'لا توجد جهات بعد. أضف جهة أو اكتشف الجهات من المصادر العامة.' },
  'owner.outreach.entities.research': { EN: 'Research prospects', AR: 'البحث عن العملاء المحتملين' },
  'owner.outreach.entities.research_help': { EN: 'Looks for EA, digital transformation and innovation leaders of the selected entities (up to 10 at a time) on their official websites and public professional sources. LinkedIn is not accessed.', AR: 'يبحث عن قادة البنية المؤسسية والتحول الرقمي والابتكار في الجهات المختارة (حتى 10 جهات في المرة الواحدة) في مواقعها الرسمية والمصادر المهنية العامة. لا يتم الوصول إلى LinkedIn.' },
  'owner.outreach.entities.research_started': { EN: 'Research started for {n} entities ({skipped} skipped).', AR: 'بدأ البحث في {n} جهة (تم تخطي {skipped}).' },
  'owner.outreach.all_types': { EN: 'All types', AR: 'جميع الأنواع' },
  'owner.outreach.all_gov': { EN: 'Any government status', AR: 'أي صفة حكومية' },
  'owner.outreach.all_tenant': { EN: 'Any workspace status', AR: 'أي حالة لمساحة العمل' },
  'owner.outreach.all_outreach': { EN: 'Any outreach status', AR: 'أي حالة تواصل' },
  'owner.outreach.any': { EN: 'any', AR: 'الكل' },
  ...fam('owner.outreach.tenant', { LINKED: ['Has a workspace', 'لديها مساحة عمل'], NONE: ['No workspace', 'بلا مساحة عمل'] }),
  'owner.outreach.select': { EN: 'Select', AR: 'تحديد' },
  'owner.outreach.selection': { EN: 'Selection', AR: 'المحدَّد' },
  'owner.outreach.selected': { EN: '{n} selected', AR: '{n} محدَّد' },
  'owner.outreach.suppressed': { EN: 'Do not contact', AR: 'عدم التواصل' },
  'owner.outreach.start': { EN: 'Start', AR: 'بدء' },
  'owner.outreach.save': { EN: 'Save', AR: 'حفظ' },
  'owner.outreach.back': { EN: 'Back', AR: 'رجوع' },
  'owner.outreach.edit': { EN: 'Edit', AR: 'تعديل' },
  'owner.outreach.view': { EN: 'View', AR: 'عرض' },
  'owner.outreach.yes': { EN: 'Yes', AR: 'نعم' },
  'owner.outreach.no': { EN: 'No', AR: 'لا' },
  'owner.outreach.created': { EN: 'Created', AR: 'تاريخ الإنشاء' },
  'owner.outreach.default': { EN: 'Default', AR: 'افتراضي' },
  'owner.outreach.tier': { EN: 'tier', AR: 'المستوى' },
  'owner.outreach.country': { EN: 'Country', AR: 'الدولة' },
  'owner.outreach.country.SA': { EN: 'Saudi Arabia', AR: 'المملكة العربية السعودية' },

  'owner.outreach.col.entity': { EN: 'Entity', AR: 'الجهة' },
  'owner.outreach.col.entities': { EN: 'Entities', AR: 'الجهات' },
  'owner.outreach.col.type': { EN: 'Type', AR: 'النوع' },
  'owner.outreach.col.government': { EN: 'Government status', AR: 'الصفة الحكومية' },
  'owner.outreach.col.prospects': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.col.tenant': { EN: 'ArchMind workspace', AR: 'مساحة العمل في ArchMind' },
  'owner.outreach.col.outreach': { EN: 'Outreach', AR: 'التواصل' },
  'owner.outreach.col.name': { EN: 'Name', AR: 'الاسم' },
  'owner.outreach.col.role': { EN: 'Role', AR: 'الدور' },
  'owner.outreach.col.seniority': { EN: 'Seniority', AR: 'المستوى الوظيفي' },
  'owner.outreach.col.employment': { EN: 'Current employment', AR: 'الوضع الوظيفي الحالي' },
  'owner.outreach.col.email': { EN: 'Email', AR: 'البريد الإلكتروني' },
  'owner.outreach.col.relevance': { EN: 'Relevance', AR: 'درجة الملاءمة' },
  'owner.outreach.col.stage': { EN: 'Stage', AR: 'المرحلة' },
  'owner.outreach.col.recipient': { EN: 'Recipient', AR: 'المستلم' },
  'owner.outreach.col.subject': { EN: 'Subject', AR: 'الموضوع' },
  'owner.outreach.col.generator': { EN: 'Written by', AR: 'كُتبت بواسطة' },

  'owner.outreach.field.name_en': { EN: 'Name (English)', AR: 'الاسم (بالإنجليزية)' },
  'owner.outreach.field.name_ar': { EN: 'Name (Arabic)', AR: 'الاسم (بالعربية)' },
  'owner.outreach.field.aliases': { EN: 'Other names / abbreviations (comma-separated)', AR: 'أسماء أخرى أو اختصارات (مفصولة بفواصل)' },
  'owner.outreach.field.website': { EN: 'Official website', AR: 'الموقع الرسمي' },
  'owner.outreach.field.sector': { EN: 'Sector', AR: 'القطاع' },
  'owner.outreach.field.city': { EN: 'City', AR: 'المدينة' },
  'owner.outreach.field.query': { EN: 'Focus (optional)', AR: 'التركيز (اختياري)' },
  'owner.outreach.field.full_name': { EN: 'Full name', AR: 'الاسم الكامل' },
  'owner.outreach.field.full_name_ar': { EN: 'Full name (Arabic)', AR: 'الاسم الكامل (بالعربية)' },
  'owner.outreach.field.job_title': { EN: 'Job title', AR: 'المسمى الوظيفي' },
  'owner.outreach.field.email': { EN: 'Professional email', AR: 'البريد الإلكتروني المهني' },
  'owner.outreach.field.profile_url': { EN: 'Public professional profile URL', AR: 'رابط الملف المهني العام' },
  'owner.outreach.field.linkedin_url': { EN: 'LinkedIn URL (if you have it)', AR: 'رابط LinkedIn (إن توفر لديك)' },
  'owner.outreach.field.source_url': { EN: 'Where you found this (URL)', AR: 'مصدر المعلومة (رابط)' },
  'owner.outreach.field.notes': { EN: 'Notes', AR: 'ملاحظات' },
  'owner.outreach.email_rule': { EN: 'Only an address the person published or gave you. Never a guessed address.', AR: 'فقط عنوان نشره الشخص أو زوّدك به، وليس عنواناً مُخمَّناً.' },
  'owner.outreach.from_title': { EN: 'From the job title', AR: 'وفق المسمى الوظيفي' },

  ...fam('owner.outreach.type', { auto: ['Detect from the name', 'يُحدَّد من الاسم'], MINISTRY: ['Ministries', 'الوزارات'], AUTHORITY: ['Authorities', 'الهيئات'], FUND: ['Funds', 'الصناديق'], COMMISSION: ['Commissions', 'المفوضيات'], AGENCY: ['Agencies', 'الوكالات'], CENTER: ['Centers', 'المراكز'], PROGRAM: ['Programs', 'البرامج'], CORPORATION: ['Public corporations', 'المؤسسات العامة'], COUNCIL: ['Councils', 'المجالس'], PLATFORM: ['National platforms', 'المنصات الوطنية'], OTHER_PUBLIC: ['Other public entities', 'جهات عامة أخرى'] }),
  ...fam('owner.outreach.gov', { CONFIRMED_GOVERNMENT: ['Government (confirmed)', 'حكومية (مؤكدة)'], LIKELY_GOVERNMENT: ['Likely government', 'يُرجَّح أنها حكومية'], UNVERIFIED: ['Not verified', 'غير مُتحقق منها'], NOT_GOVERNMENT: ['Not government', 'ليست جهة حكومية'] }),
  ...fam('owner.outreach.match', { EXISTING_TENANT: ['Workspace exists', 'لها مساحة عمل'], POSSIBLE_MATCH: ['Possible match', 'تطابق محتمل'], NEW_ENTITY: ['No workspace yet', 'لا توجد مساحة عمل بعد'] }),
  ...fam('owner.outreach.match_help', { EXISTING_TENANT: ['An ArchMind workspace already exists for this organisation (same website or name). Link it instead of creating a duplicate.', 'توجد مساحة عمل في ArchMind لهذه الجهة (الموقع نفسه أو الاسم نفسه). اربطها بدلاً من إنشاء مساحة مكررة.'], POSSIBLE_MATCH: ['A workspace with a similar name exists. Link it if it is the same organisation, or confirm it is different when creating one.', 'توجد مساحة عمل باسم مشابه. اربطها إن كانت الجهة نفسها، أو أكّد أنها مختلفة عند الإنشاء.'], NEW_ENTITY: ['No ArchMind workspace matches this organisation.', 'لا توجد مساحة عمل في ArchMind تطابق هذه الجهة.'] }),
  ...fam('owner.outreach.entity_outreach', { NOT_STARTED: ['Not started', 'لم يبدأ'], PROSPECTS_FOUND: ['Prospects found', 'عُثر على عملاء محتملين'], PREPARING: ['Preparing outreach', 'جارٍ إعداد التواصل'], CONTACTED: ['Contacted', 'تم التواصل'], ACTIVATED: ['Activated', 'مفعَّل'], ENGAGED: ['Engaged', 'متفاعل'] }),

  // Entity detail
  'owner.outreach.entity.help': { EN: 'The entity, its prospects grouped by role, and its ArchMind workspace. Create or link the workspace, enrich it from public sources and prepare EA Views before inviting anyone.', AR: 'الجهة وعملاؤها المحتملون مصنّفون حسب الدور، ومساحة عملها في ArchMind. أنشئ مساحة العمل أو اربطها، وأثرِها من المصادر العامة، وجهّز العروض المعمارية قبل دعوة أي شخص.' },
  'owner.outreach.entity.overview': { EN: 'Organisation', AR: 'الجهة' },
  'owner.outreach.entity.tenant': { EN: 'ArchMind workspace', AR: 'مساحة العمل في ArchMind' },
  'owner.outreach.entity.tenant_help': { EN: 'Uses the Owner Console tenant creation, AI enrichment (with your review before anything is written) and EA View preparation. Never creates a duplicate.', AR: 'يستخدم إنشاء المساحات في وحدة تحكم المالك، والإثراء بالذكاء الاصطناعي (مع مراجعتك قبل حفظ أي شيء)، وتجهيز العروض المعمارية. لا يُنشئ مساحة مكررة أبداً.' },
  'owner.outreach.entity.meta_model': { EN: 'Meta Model published', AR: 'النموذج الوصفي منشور' },
  'owner.outreach.entity.enrichment': { EN: 'AI enrichment', AR: 'الإثراء بالذكاء الاصطناعي' },
  'owner.outreach.entity.not_enriched': { EN: 'Not enriched yet', AR: 'لم يتم الإثراء بعد' },
  'owner.outreach.entity.objects': { EN: 'Repository objects', AR: 'عناصر المستودع' },
  'owner.outreach.entity.public_objects': { EN: 'From public research', AR: 'من البحث في المصادر العامة' },
  'owner.outreach.entity.views': { EN: 'Prepared EA Views', AR: 'العروض المعمارية المُعدّة' },
  'owner.outreach.entity.view_tenant': { EN: 'Open workspace', AR: 'فتح مساحة العمل' },
  'owner.outreach.entity.enrich': { EN: 'Enrich from public sources', AR: 'الإثراء من المصادر العامة' },
  'owner.outreach.entity.enrich_started': { EN: 'Enrichment started. Review its findings before they are written to the repository.', AR: 'بدأ الإثراء. راجع نتائجه قبل حفظها في المستودع.' },
  'owner.outreach.entity.review_enrichment': { EN: 'Review enrichment', AR: 'مراجعة الإثراء' },
  'owner.outreach.entity.prepare_views': { EN: 'Prepare EA Views', AR: 'تجهيز العروض المعمارية' },
  'owner.outreach.entity.views_prepared': { EN: '{n} views prepared ({skipped} skipped: not enough data).', AR: 'تم تجهيز {n} عرض (تم تخطي {skipped} لعدم كفاية البيانات).' },
  'owner.outreach.entity.create_tenant': { EN: 'Create ArchMind workspace', AR: 'إنشاء مساحة عمل في ArchMind' },
  'owner.outreach.entity.confirm_not_duplicate': { EN: 'I checked the similar workspace: this is a different organisation.', AR: 'تحققت من مساحة العمل المشابهة: هذه جهة مختلفة.' },
  'owner.outreach.entity.link': { EN: 'Link', AR: 'ربط' },
  'owner.outreach.entity.linked': { EN: 'Workspace linked.', AR: 'تم ربط مساحة العمل.' },
  'owner.outreach.entity.rematch': { EN: 'Check again', AR: 'إعادة التحقق' },
  'owner.outreach.entity.prospects': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.entity.prospects_help': { EN: 'Grouped by role. Click a person to see the evidence and why they are relevant. Select people to prepare invitations and emails.', AR: 'مصنّفون حسب الدور. انقر على الشخص لعرض الأدلة وسبب ملاءمته. حدّد الأشخاص لإعداد الدعوات والرسائل.' },
  'owner.outreach.entity.no_prospects': { EN: 'No prospects yet. Research prospects or add one you know.', AR: 'لا يوجد عملاء محتملون بعد. ابحث عنهم أو أضف شخصاً تعرفه.' },
  'owner.outreach.entity.suppress': { EN: 'Do not contact this entity', AR: 'عدم التواصل مع هذه الجهة' },
  'owner.outreach.entity.unsuppress': { EN: 'Allow contact again', AR: 'السماح بالتواصل مجدداً' },
  'owner.outreach.entity.suppress_help': { EN: 'No one at this entity will be researched, invited or emailed; unsent emails are cancelled.', AR: 'لن يتم البحث عن أي شخص في هذه الجهة أو دعوته أو مراسلته، وتُلغى الرسائل غير المرسلة.' },
  'owner.outreach.entity.unsuppress_help': { EN: 'People who opted out themselves stay suppressed.', AR: 'يبقى من طلب إيقاف الرسائل بنفسه ضمن قائمة عدم التواصل.' },
  'owner.outreach.entity.suppressed_note': { EN: 'This entity is on the do-not-contact list', AR: 'هذه الجهة مدرجة في قائمة عدم التواصل' },
  'owner.outreach.entity.confirm_government': { EN: 'Confirm government status', AR: 'تأكيد الصفة الحكومية' },
  'owner.outreach.entity.confirm_government_help': { EN: 'Normally computed from the official domain and name. Set it only when you have checked the organisation yourself; the reason is recorded.', AR: 'تُحسب عادةً من النطاق الرسمي والاسم. لا تحدّدها إلا بعد التحقق من الجهة بنفسك، ويُسجَّل السبب.' },
  'owner.outreach.entity.keep_computed': { EN: 'Keep the computed status', AR: 'الإبقاء على الحالة المحسوبة' },
  ...fam('owner.outreach.skip', { NOT_FOUND: ['Entity not found.', 'لم يتم العثور على الجهة.'], ENTITY_SUPPRESSED: ['The entity is on the do-not-contact list.', 'الجهة مدرجة في قائمة عدم التواصل.'], NOT_GOVERNMENT: ['The entity is not a government organisation.', 'الجهة ليست جهة حكومية.'], DISCOVERY_RUNNING: ['Research is already running for this entity.', 'البحث جارٍ بالفعل لهذه الجهة.'] }),

  // Discovery jobs
  ...fam('owner.outreach.job.mode', { ENTITIES: ['Entity discovery', 'اكتشاف الجهات'], PROFESSIONALS: ['Prospect research', 'البحث عن العملاء المحتملين'] }),
  ...fam('owner.outreach.job.status', { QUEUED: ['Queued', 'في الانتظار'], ENTITY_DISCOVERY: ['Searching', 'جارٍ البحث'], PROFESSIONAL_DISCOVERY: ['Searching', 'جارٍ البحث'], VERIFICATION: ['Reading sources', 'جارٍ قراءة المصادر'], CLASSIFICATION: ['Verifying', 'جارٍ التحقق'], DEDUPLICATION: ['Checking duplicates', 'جارٍ فحص التكرار'], ENTITY_MAPPING: ['Saving', 'جارٍ الحفظ'], READY_FOR_REVIEW: ['Ready for review', 'جاهز للمراجعة'], COMPLETED: ['Reviewed', 'تمت المراجعة'], FAILED: ['Failed', 'فشل'], CANCELLED: ['Cancelled', 'ملغى'] }),
  ...fam('owner.outreach.job.stage', { ENTITY_DISCOVERY: ['Public search', 'البحث العام'], PROFESSIONAL_DISCOVERY: ['Official site + public search', 'الموقع الرسمي والبحث العام'], VERIFICATION: ['Candidates with evidence', 'مرشحون مع الأدلة'], CLASSIFICATION: ['Verification and role', 'التحقق والدور'], DEDUPLICATION: ['Duplicates and suppression', 'التكرار وقائمة عدم التواصل'], ENTITY_MAPPING: ['Grouped by entity', 'التجميع حسب الجهة'] }),
  'owner.outreach.job.results': { EN: '{created} new, {merged} updated, {dropped} dropped (not verifiable), {suppressed} on the do-not-contact list', AR: '{created} جديد، {merged} محدَّث، {dropped} مستبعد (تعذّر التحقق)، {suppressed} في قائمة عدم التواصل' },
  'owner.outreach.job.limitations': { EN: 'Limits of this research', AR: 'حدود هذا البحث' },
  'owner.outreach.job.rejected': { EN: 'Dropped candidates', AR: 'المرشحون المستبعدون' },
  'owner.outreach.job.sources': { EN: 'Sources read', AR: 'المصادر المقروءة' },
  'owner.outreach.job.mark_reviewed': { EN: 'Mark as reviewed', AR: 'تحديد كمراجَع' },

  // Prospects
  'owner.outreach.prospect': { EN: 'Prospect', AR: 'عميل محتمل' },
  'owner.outreach.prospects.title': { EN: 'Prospects', AR: 'العملاء المحتملون' },
  'owner.outreach.prospects.subtitle': { EN: 'EA, digital transformation and innovation professionals in Saudi government entities', AR: 'مختصو البنية المؤسسية والتحول الرقمي والابتكار في الجهات الحكومية السعودية' },
  'owner.outreach.prospects.help': { EN: 'Only professional information from public sources (or entered by you), each with its source. Emails are never guessed. A person whose current role is uncertain must be confirmed by you before outreach.', AR: 'معلومات مهنية فقط من مصادر عامة (أو أدخلتها أنت)، ولكل معلومة مصدرها. لا يتم تخمين عناوين البريد الإلكتروني أبداً. يجب أن تؤكد بنفسك الدور الحالي لأي شخص غير مؤكد قبل التواصل معه.' },
  'owner.outreach.prospects.ask': { EN: 'Find', AR: 'ابحث' },
  'owner.outreach.prospects.ask_help': { EN: 'Describe who you are looking for, for example "EA Directors in Saudi ministries". ArchMind turns it into filters you can adjust.', AR: 'صِف من تبحث عنه، مثل "مديري البنية المؤسسية في الوزارات السعودية"، وسيحوّله ArchMind إلى عوامل تصفية يمكنك تعديلها.' },
  'owner.outreach.prospects.ask_example': { EN: 'Find Enterprise Architecture Heads in government authorities', AR: 'ابحث عن رؤساء البنية المؤسسية في الهيئات الحكومية' },
  'owner.outreach.prospects.apply': { EN: 'Apply', AR: 'تطبيق' },
  'owner.outreach.prospects.understood': { EN: 'Understood as', AR: 'فُهم على أنه' },
  'owner.outreach.prospects.discover_matching': { EN: 'Research matching entities', AR: 'البحث في الجهات المطابقة' },
  'owner.outreach.prospects.no_entities': { EN: 'No directory entities match; discover or add entities first.', AR: 'لا توجد جهات مطابقة في الدليل؛ اكتشف الجهات أو أضفها أولاً.' },
  'owner.outreach.prospects.search': { EN: 'Search name or title', AR: 'ابحث بالاسم أو المسمى الوظيفي' },
  'owner.outreach.prospects.empty': { EN: 'No prospects match.', AR: 'لا يوجد عملاء محتملون مطابقون.' },
  'owner.outreach.prospects.add': { EN: 'Add prospect', AR: 'إضافة عميل محتمل' },
  'owner.outreach.prospects.add_help': { EN: 'Professional details only. An email you enter is marked as provided by you. A person who asked not to be contacted cannot be added again.', AR: 'البيانات المهنية فقط. يُعلَّم البريد الإلكتروني الذي تُدخله بأنه مقدَّم منك. لا يمكن إضافة شخص طلب عدم التواصل معه مرة أخرى.' },
  ...fam('owner.outreach.role', { ENTERPRISE_ARCHITECTURE: ['Enterprise Architecture', 'البنية المؤسسية'], DIGITAL_TRANSFORMATION: ['Digital Transformation', 'التحول الرقمي'], DIGITAL_INNOVATION: ['Digital Innovation', 'الابتكار الرقمي'], DIGITAL_STRATEGY: ['Digital Strategy', 'الاستراتيجية الرقمية'], TECHNOLOGY_STRATEGY: ['Technology Strategy', 'استراتيجية التقنية'], OTHER_RELEVANT: ['Other relevant roles', 'أدوار أخرى ذات صلة'] }),
  ...fam('owner.outreach.role_short', { ENTERPRISE_ARCHITECTURE: ['EA', 'البنية المؤسسية'], DIGITAL_TRANSFORMATION: ['DT', 'التحول الرقمي'], DIGITAL_INNOVATION: ['Innovation', 'الابتكار'], DIGITAL_STRATEGY: ['Digital strategy', 'الاستراتيجية الرقمية'], TECHNOLOGY_STRATEGY: ['Tech strategy', 'استراتيجية التقنية'], OTHER_RELEVANT: ['Other', 'أخرى'] }),
  ...fam('owner.outreach.seniority', { EXECUTIVE: ['Executive', 'قيادة تنفيذية'], DIRECTOR: ['Director', 'مدير'], HEAD: ['Head', 'رئيس'], MANAGER: ['Manager', 'مدير قسم'], CONSULTANT: ['Consultant', 'مستشار'], ARCHITECT: ['Architect', 'معماري'], OTHER: ['Other', 'أخرى'] }),
  ...fam('owner.outreach.employment', { CURRENT_CONFIRMED: ['Current (official site)', 'حالي (الموقع الرسمي)'], CURRENT_LIKELY: ['Likely current', 'يُرجَّح أنه حالي'], CURRENT_STATUS_UNCERTAIN: ['Current role uncertain', 'الدور الحالي غير مؤكد'], FORMER: ['Former role', 'دور سابق'] }),
  ...fam('owner.outreach.email_status', { VERIFIED_PUBLIC: ['Published', 'منشور علناً'], OWNER_PROVIDED: ['Provided by you', 'مقدَّم منك'], UNAVAILABLE: ['Unavailable', 'غير متاح'] }),
  ...fam('owner.outreach.stage', { DISCOVERED: ['Discovered', 'مكتشَف'], VERIFIED: ['Verified', 'مُتحقق منه'], SHORTLISTED: ['Shortlisted', 'في القائمة المختصرة'], TENANT_PREPARED: ['Workspace prepared', 'مساحة العمل مُعدّة'], INVITATION_PREPARED: ['Invitation prepared', 'الدعوة مُعدّة'], OUTREACH_READY: ['Email ready', 'الرسالة جاهزة'], CONTACTED: ['Contacted (other channel)', 'تم التواصل (قناة أخرى)'], INVITED: ['Invited', 'مدعو'], ACTIVATED: ['Activated', 'مفعَّل'], ENGAGED: ['Engaged', 'متفاعل'], NOT_INTERESTED: ['Not interested', 'غير مهتم'], INVALID: ['Invalid', 'غير صالح'], DO_NOT_CONTACT: ['Do not contact', 'عدم التواصل'] }),
  'owner.outreach.source': { EN: 'Source', AR: 'المصدر' },
  ...fam('owner.outreach.source', { AI_DISCOVERY: ['Public-source research', 'البحث في المصادر العامة'], OWNER: ['Entered by you', 'أدخلته أنت'] }),
  'owner.outreach.classification': { EN: 'Why this role', AR: 'سبب تصنيف الدور' },
  ...fam('owner.outreach.basis', { LEXICON: ['From the job title', 'من المسمى الوظيفي'], LEXICON_AND_AI: ['From the job title (AI agrees)', 'من المسمى الوظيفي (ويتفق معه الذكاء الاصطناعي)'], AI_PROPOSED: ['Proposed by AI - confirm', 'مقترح من الذكاء الاصطناعي - يحتاج تأكيداً'], OWNER: ['Set by you', 'حدّدته أنت'], NONE: ['Not classified', 'غير مصنّف'] }),
  'owner.outreach.owner_verified': { EN: 'Confirmed by you', AR: 'أكّدته أنت' },
  'owner.outreach.last_verified': { EN: 'Last verified', AR: 'آخر تحقق' },
  'owner.outreach.confidence': { EN: 'Confidence', AR: 'درجة الثقة' },
  'owner.outreach.email_source': { EN: 'Where the email is published', AR: 'مكان نشر البريد الإلكتروني' },
  'owner.outreach.profile': { EN: 'Profiles', AR: 'الملفات المهنية' },
  'owner.outreach.profile_link': { EN: 'Professional profile', AR: 'الملف المهني' },
  'owner.outreach.retain_until': { EN: 'Kept until', AR: 'يُحتفظ به حتى' },
  'owner.outreach.relevance': { EN: 'Relevance', AR: 'درجة الملاءمة' },
  'owner.outreach.relevance_help': { EN: 'The sum of six factors, each explained: role, seniority, current employment, government organisation, source quality and how recent the evidence is. No hidden score.', AR: 'مجموع ستة عوامل موضّحة: الدور، والمستوى الوظيفي، والوضع الوظيفي الحالي، والصفة الحكومية للجهة، وجودة المصدر، وحداثة الأدلة. لا توجد درجة خفية.' },
  ...fam('owner.outreach.factor', { ROLE: ['Role', 'الدور'], SENIORITY: ['Seniority', 'المستوى الوظيفي'], CURRENT_EMPLOYMENT: ['Current employment', 'الوضع الوظيفي الحالي'], GOVERNMENT_ORGANIZATION: ['Government organisation', 'الصفة الحكومية للجهة'], SOURCE_QUALITY: ['Source quality', 'جودة المصدر'], EVIDENCE_RECENCY: ['Evidence recency', 'حداثة الأدلة'] }),
  'owner.outreach.evidence': { EN: 'Evidence', AR: 'الأدلة' },
  'owner.outreach.no_evidence': { EN: 'No public source: entered by you.', AR: 'لا يوجد مصدر عام: أدخلته أنت.' },
  'owner.outreach.read_on': { EN: 'read on', AR: 'قُرئ في' },
  'owner.outreach.dated': { EN: 'dated', AR: 'بتاريخ' },
  'owner.outreach.eligibility': { EN: 'Can this person be emailed?', AR: 'هل يمكن مراسلة هذا الشخص؟' },
  'owner.outreach.eligible': { EN: 'Yes: all checks pass. The email still needs your approval.', AR: 'نعم: اجتاز جميع الفحوصات، ولا تزال الرسالة تحتاج إلى اعتمادك.' },
  'owner.outreach.eligible_short': { EN: 'Ready', AR: 'جاهز' },
  'owner.outreach.suggested_role': { EN: 'Suggested role', AR: 'الدور المقترح' },
  'owner.outreach.verify': { EN: 'Confirm current role', AR: 'تأكيد الدور الحالي' },
  'owner.outreach.verify_note': { EN: 'How did you confirm it? (e.g. official page checked today)', AR: 'كيف تحققت من ذلك؟ (مثلاً: راجعت الصفحة الرسمية اليوم)' },
  'owner.outreach.set_stage': { EN: 'Set stage…', AR: 'تحديد المرحلة…' },
  'owner.outreach.dnc.title': { EN: 'Do not contact', AR: 'عدم التواصل' },
  'owner.outreach.dnc.set': { EN: 'Do not contact', AR: 'عدم التواصل' },
  'owner.outreach.dnc.clear': { EN: 'Lift do-not-contact', AR: 'رفع حظر التواصل' },
  'owner.outreach.erase': { EN: 'Erase record', AR: 'حذف السجل' },
  'owner.outreach.erase_reason': { EN: 'Reason (e.g. removal request)', AR: 'السبب (مثلاً: طلب حذف)' },
  'owner.outreach.erase_suppress': { EN: 'Keep a suppression entry (hash only) so this person is never rediscovered or contacted', AR: 'الإبقاء على قيد منع (بصيغة مشفّرة فقط) حتى لا يُكتشف هذا الشخص أو يُتواصل معه مجدداً' },

  // Gates
  ...fam('owner.outreach.blocker', {
    DO_NOT_CONTACT: ['Do not contact', 'عدم التواصل'], ENTITY_SUPPRESSED: ['Entity on the do-not-contact list', 'الجهة في قائمة عدم التواصل'], SUPPRESSED_EMAIL: ['Email address suppressed', 'البريد الإلكتروني ضمن قائمة المنع'],
    SUPPRESSED_PERSON: ['Person suppressed (opted out or erased)', 'الشخص ضمن قائمة المنع (طلب الإيقاف أو الحذف)'], SUPPRESSED_DOMAIN: ['Domain suppressed', 'النطاق ضمن قائمة المنع'], NOT_GOVERNMENT: ['Entity not confirmed as government', 'لم تُؤكَّد الصفة الحكومية للجهة'],
    FORMER_EMPLOYEE: ['Role is a former one', 'الدور سابق'], EMPLOYMENT_UNVERIFIED: ['Confirm the current role first', 'أكّد الدور الحالي أولاً'], EMAIL_UNAVAILABLE: ['No legitimate email', 'لا يوجد بريد إلكتروني مشروع'],
    NO_TENANT: ['Create or link the workspace first', 'أنشئ مساحة العمل أو اربطها أولاً'], INVALID: ['Marked invalid', 'مُعلَّم كغير صالح'], NOT_INTERESTED: ['Not interested', 'غير مهتم'], ALREADY_ACTIVATED: ['Already a user / already emailed', 'مستخدم بالفعل أو تمت مراسلته'],
    NO_INVITATION: ['Prepare the invitation first', 'أعدّ الدعوة أولاً'], INVITATION_FAILED: ['The invitation could not be renewed', 'تعذّر تجديد الدعوة'], ATTACHMENT_UNAVAILABLE: ['The presentation could not be read', 'تعذّرت قراءة العرض التقديمي'],
  }),

  // Invitations
  'owner.outreach.invite': { EN: 'Prepare invitations', AR: 'إعداد الدعوات' },
  'owner.outreach.invite_help': { EN: 'Creates a pending invitation in the entity\'s workspace with a single-use activation link. It is not emailed here: the link goes in the outreach email you approve. Nobody becomes an administrator unless you choose it and confirm with your password.', AR: 'يُنشئ دعوة معلّقة في مساحة عمل الجهة برابط تفعيل يُستخدم مرة واحدة. لا تُرسل الدعوة من هنا، بل يُضمَّن الرابط في رسالة التواصل التي تعتمدها. لا يصبح أي شخص مسؤولاً إلا إذا اخترت ذلك وأكّدته بكلمة المرور.' },
  'owner.outreach.invite.access_level': { EN: 'Access level', AR: 'مستوى الوصول' },
  'owner.outreach.invite.role': { EN: 'Role', AR: 'الدور' },
  'owner.outreach.invite.suggested': { EN: 'Suggested for this role', AR: 'المقترح لهذا الدور' },
  'owner.outreach.invite.keep': { EN: 'Keep the current choice', AR: 'الإبقاء على الاختيار الحالي' },
  'owner.outreach.invite.elevated': { EN: 'Administrator access is a separate decision. Confirm it with your password.', AR: 'صلاحية المسؤول قرار مستقل، أكّده بكلمة المرور.' },
  'owner.outreach.invite.prepare': { EN: 'Prepare', AR: 'إعداد' },
  'owner.outreach.invite.done': { EN: '{n} invitations prepared.', AR: 'تم إعداد {n} دعوة.' },
  'owner.outreach.invite.not_emailed': { EN: 'No email was sent. Prepare outreach to write the email that carries the link.', AR: 'لم تُرسل أي رسالة. أعدّ التواصل لكتابة الرسالة التي تتضمن الرابط.' },
  ...fam('owner.outreach.invite.status', { PREPARED: ['Prepared', 'تم الإعداد'], BLOCKED: ['Not prepared', 'لم يتم الإعداد'], FAILED: ['Failed', 'فشل'], NOT_FOUND: ['Not found', 'غير موجود'] }),
  ...fam('owner.outreach.legacy', { ARCHITECT: ['Standard user', 'مستخدم عادي'], REVIEWER: ['Reviewer', 'مراجِع'], TENANT_ADMIN: ['Administrator', 'مسؤول'], SUPERADMIN: ['Super administrator', 'مسؤول أعلى'] }),
  ...fam('owner.outreach.template', { 'chief-enterprise-architect': ['Chief Enterprise Architect', 'كبير المعماريين المؤسسيين'], 'ea-contributor': ['EA contributor', 'مساهم في البنية المؤسسية'], 'ea-reviewer': ['EA reviewer', 'مراجِع البنية المؤسسية'], 'ea-viewer': ['EA viewer', 'مطّلع على البنية المؤسسية'], 'executive-viewer': ['Executive viewer', 'مطّلع تنفيذي'], 'guest-viewer': ['Guest viewer', 'مطّلع ضيف'], 'tenant-administrator': ['Workspace administrator', 'مسؤول مساحة العمل'] }),

  // Outreach preparation
  'owner.outreach.prepare_outreach': { EN: 'Prepare outreach', AR: 'إعداد التواصل' },
  'owner.outreach.campaign': { EN: 'Campaign', AR: 'الحملة' },
  'owner.outreach.language': { EN: 'Language', AR: 'اللغة' },
  'owner.outreach.language.auto': { EN: 'From the person\'s title', AR: 'حسب المسمى الوظيفي للشخص' },
  'owner.outreach.generate_drafts': { EN: 'Generate drafts', AR: 'إنشاء المسودات' },
  'owner.outreach.drafts_done': { EN: '{n} drafts ready for review.', AR: '{n} مسودة جاهزة للمراجعة.' },
  ...fam('owner.outreach.draft_status', { DRAFTED: ['Drafted', 'تم إنشاء المسودة'], EXISTS: ['Already has an email in this campaign', 'لديه رسالة في هذه الحملة بالفعل'], BLOCKED: ['Not drafted', 'لم تُنشأ مسودة'] }),
  'owner.outreach.open_campaign': { EN: 'Open campaign', AR: 'فتح الحملة' },

  // Campaigns
  'owner.outreach.campaigns.title': { EN: 'Campaigns', AR: 'الحملات' },
  'owner.outreach.campaigns.subtitle': { EN: 'Prepared, approved and sent outreach with activation and engagement', AR: 'التواصل المُعدّ والمعتمد والمرسل مع التفعيل والتفاعل' },
  'owner.outreach.campaigns.help': { EN: 'A campaign groups the entities and people you reach in one effort and tracks them from workspace preparation to activation and use.', AR: 'تجمع الحملة الجهات والأشخاص الذين تتواصل معهم في جهد واحد، وتتابعهم من تجهيز مساحة العمل حتى التفعيل والاستخدام.' },
  'owner.outreach.campaigns.new': { EN: 'New campaign', AR: 'حملة جديدة' },
  'owner.outreach.campaigns.name': { EN: 'Campaign name', AR: 'اسم الحملة' },
  'owner.outreach.campaigns.name_example': { EN: 'KSA Government EA Outreach — Q4 2026', AR: 'التواصل مع الجهات الحكومية - الربع الرابع 2026' },
  'owner.outreach.campaigns.description': { EN: 'Description', AR: 'الوصف' },
  'owner.outreach.campaigns.emails': { EN: 'Emails', AR: 'الرسائل' },
  'owner.outreach.campaigns.empty': { EN: 'No campaigns yet.', AR: 'لا توجد حملات بعد.' },
  ...fam('owner.outreach.campaign_status', { DRAFT: ['Draft', 'مسودة'], ACTIVE: ['Active', 'نشطة'], CLOSED: ['Closed', 'مغلقة'] }),
  'owner.outreach.campaign.activate': { EN: 'Activate', AR: 'تفعيل' },
  'owner.outreach.campaign.close': { EN: 'Close campaign', AR: 'إغلاق الحملة' },
  'owner.outreach.campaign.emails': { EN: 'Emails', AR: 'الرسائل' },
  'owner.outreach.campaign.emails_help': { EN: 'Select drafts to approve, or approved emails to send.', AR: 'حدّد المسودات لاعتمادها، أو الرسائل المعتمدة لإرسالها.' },
  'owner.outreach.campaign.no_emails': { EN: 'No emails yet. Select prospects on an entity or the Prospects page and prepare outreach.', AR: 'لا توجد رسائل بعد. حدّد العملاء المحتملين من صفحة الجهة أو صفحة العملاء المحتملين ثم أعدّ التواصل.' },
  ...fam('owner.outreach.metric', { entities: ['Entities selected', 'الجهات المختارة'], prospects: ['Prospects selected', 'العملاء المحتملون المختارون'], tenants: ['Workspaces', 'مساحات العمل'], enriched: ['Workspaces enriched', 'مساحات عمل أُثريت'], invitations: ['Invitations prepared', 'الدعوات المُعدّة'], prepared: ['Emails prepared', 'الرسائل المُعدّة'], approved: ['Emails approved', 'الرسائل المعتمدة'], sent: ['Emails sent', 'الرسائل المرسلة'], failed: ['Delivery failed', 'تعذّر التسليم'], activated: ['Activated', 'مفعَّلون'], first_login: ['Workspaces with a first sign-in', 'مساحات عمل سُجّل الدخول إليها'], engaged: ['Engaged', 'متفاعلون'] }),
  ...fam('owner.outreach.message_status', { DRAFT: ['Draft', 'مسودة'], APPROVED: ['Approved', 'معتمدة'], SENT: ['Sent', 'مرسلة'], FAILED: ['Failed', 'فشلت'], CANCELLED: ['Cancelled', 'ملغاة'] }),
  ...fam('owner.outreach.generator', { AI: ['AI (reviewed by you)', 'الذكاء الاصطناعي (بمراجعتك)'], TEMPLATE: ['Standard template', 'قالب قياسي'] }),
  ...fam('owner.outreach.result', { SENT: ['Sent', 'أُرسلت'], APPROVED: ['Approved', 'اعتُمدت'], SKIPPED: ['Skipped', 'تم التخطي'], BLOCKED: ['Blocked', 'محظورة'], FAILED: ['Failed', 'فشلت'] }),
  'owner.outreach.approve': { EN: 'Approve', AR: 'اعتماد' },
  'owner.outreach.send': { EN: 'Send', AR: 'إرسال' },
  'owner.outreach.send.remaining': { EN: '{n} more can be sent today', AR: 'يمكن إرسال {n} رسالة أخرى اليوم' },
  'owner.outreach.send.daily_limit': { EN: 'daily sending limit reached', AR: 'تم بلوغ الحد اليومي للإرسال' },
  'owner.outreach.review_edit': { EN: 'Review / edit', AR: 'مراجعة / تعديل' },

  // Email editor
  'owner.outreach.editor.title': { EN: 'Review email', AR: 'مراجعة الرسالة' },
  'owner.outreach.editor.recipient_help': { EN: 'Changing the address records it as provided by you and re-issues the invitation to it.', AR: 'تغيير العنوان يسجّله كعنوان مقدَّم منك ويعيد إصدار الدعوة إليه.' },
  'owner.outreach.editor.body': { EN: 'Message', AR: 'نص الرسالة' },
  'owner.outreach.editor.footer': { EN: 'Added by ArchMind when sent', AR: 'يضيفه ArchMind عند الإرسال' },
  'owner.outreach.editor.attach': { EN: 'Attach the presentation', AR: 'إرفاق العرض التقديمي' },
  'owner.outreach.editor.material': { EN: 'Presentation', AR: 'العرض التقديمي' },
  'owner.outreach.editor.no_material': { EN: 'None', AR: 'بلا' },
  'owner.outreach.editor.role': { EN: 'Change the invited role', AR: 'تغيير دور المدعو' },
  'owner.outreach.editor.saved': { EN: 'Saved.', AR: 'تم الحفظ.' },
  'owner.outreach.editor.approved': { EN: 'Approved.', AR: 'تم الاعتماد.' },
  'owner.outreach.editor.not_approved': { EN: 'Not approved: the checks below must pass first.', AR: 'لم يتم الاعتماد: يجب اجتياز الفحوصات أدناه أولاً.' },
  'owner.outreach.editor.ai_rejected': { EN: 'the AI text broke a rule, so the standard template was used', AR: 'خالف نص الذكاء الاصطناعي إحدى القواعد، لذا استُخدم القالب القياسي' },
  'owner.outreach.editor.cancel_email': { EN: 'Cancel this email', AR: 'إلغاء هذه الرسالة' },

  // Settings
  'owner.outreach.settings.title': { EN: 'Outreach settings', AR: 'إعدادات التواصل' },
  'owner.outreach.settings.subtitle': { EN: 'Marketing materials, sending and compliance controls, discovery providers', AR: 'المواد التسويقية، وضوابط الإرسال والامتثال، ومزوّدو الاكتشاف' },
  'owner.outreach.settings.help': { EN: 'These controls apply to every campaign. Sending is off until you switch it on and record the legal basis.', AR: 'تنطبق هذه الضوابط على جميع الحملات. يبقى الإرسال متوقفاً حتى تفعّله وتسجّل الأساس النظامي.' },
  'owner.outreach.materials.title': { EN: 'Marketing materials', AR: 'المواد التسويقية' },
  'owner.outreach.materials.help': { EN: 'The default presentation is attached to outreach emails. It is stored once and reused; replace it any time by uploading a new one and making it the default.', AR: 'يُرفق العرض التقديمي الافتراضي برسائل التواصل. يُخزَّن مرة واحدة ويُعاد استخدامه، ويمكنك استبداله في أي وقت برفع عرض جديد وجعله افتراضياً.' },
  'owner.outreach.materials.upload': { EN: 'Upload presentation', AR: 'رفع عرض تقديمي' },
  'owner.outreach.materials.make_default': { EN: 'Make it the default', AR: 'جعله الافتراضي' },
  'owner.outreach.materials.limits': { EN: 'PowerPoint (.pptx) or PDF, up to 15 MB', AR: 'ملف PowerPoint (.pptx) أو PDF، بحد أقصى 15 ميجابايت' },
  'owner.outreach.materials.empty': { EN: 'No presentation uploaded.', AR: 'لم يُرفع أي عرض تقديمي.' },
  'owner.outreach.materials.name': { EN: 'Presentation', AR: 'العرض التقديمي' },
  'owner.outreach.materials.size': { EN: 'Size', AR: 'الحجم' },
  'owner.outreach.materials.download': { EN: 'Download', AR: 'تنزيل' },
  'owner.outreach.materials.set_default': { EN: 'Make default', AR: 'جعله افتراضياً' },
  'owner.outreach.materials.archive': { EN: 'Archive', AR: 'أرشفة' },
  'owner.outreach.materials.uploaded': { EN: 'Presentation uploaded.', AR: 'تم رفع العرض التقديمي.' },
  'owner.outreach.settings.sending': { EN: 'Sending and compliance', AR: 'الإرسال والامتثال' },
  'owner.outreach.settings.sending_help': { EN: 'Rate limits, verification before outreach, retention of never-contacted records and the sender details shown in every email.', AR: 'حدود الإرسال، والتحقق قبل التواصل، ومدة الاحتفاظ بسجلات من لم يُتواصل معهم، وبيانات المرسل الظاهرة في كل رسالة.' },
  'owner.outreach.settings.legal_note': { EN: 'Professional names, titles and work emails are personal data under the Saudi PDPL. Confirm with legal counsel that your outreach has a lawful basis and meets the direct-marketing and anti-spam rules before enabling sending. ArchMind enforces the controls below; it does not decide the legal position.', AR: 'تُعد الأسماء والمسميات الوظيفية وعناوين البريد المهنية بيانات شخصية وفق نظام حماية البيانات الشخصية السعودي. تحقّق مع مستشار قانوني من وجود أساس نظامي للتواصل ومن استيفاء قواعد التسويق المباشر ومكافحة الرسائل الاقتحامية قبل تفعيل الإرسال. يطبّق ArchMind الضوابط أدناه، ولا يحدّد الموقف النظامي.' },
  'owner.outreach.settings.enabled': { EN: 'Sending enabled', AR: 'الإرسال مفعّل' },
  'owner.outreach.settings.legal_basis': { EN: 'Legal basis and approval reference (required to enable sending)', AR: 'الأساس النظامي ومرجع الموافقة (مطلوب لتفعيل الإرسال)' },
  'owner.outreach.settings.daily': { EN: 'Emails per day', AR: 'عدد الرسائل في اليوم' },
  'owner.outreach.settings.batch': { EN: 'Emails per send', AR: 'عدد الرسائل في كل إرسال' },
  'owner.outreach.settings.retention': { EN: 'Keep never-contacted records (days)', AR: 'مدة الاحتفاظ بسجلات من لم يُتواصل معهم (بالأيام)' },
  'owner.outreach.settings.retention_help': { EN: 'Prospects never contacted are deleted after this period; do-not-contact entries are kept as hashes.', AR: 'يُحذف العملاء المحتملون الذين لم يُتواصل معهم بعد هذه المدة، وتُحفظ قيود عدم التواصل بصيغة مشفّرة.' },
  'owner.outreach.settings.require_verification': { EN: 'Require your confirmation of the current role when evidence is not conclusive', AR: 'اشتراط تأكيدك للدور الحالي عندما لا تكون الأدلة قاطعة' },
  'owner.outreach.settings.sender': { EN: 'Sender name', AR: 'اسم المرسل' },
  'owner.outreach.settings.reply_to': { EN: 'Reply-to address', AR: 'عنوان الرد' },
  'owner.outreach.settings.contact': { EN: 'Contact line in the footer', AR: 'بيانات التواصل في التذييل' },
  'owner.outreach.settings.updated': { EN: 'Last updated', AR: 'آخر تحديث' },
  'owner.outreach.settings.saved': { EN: 'Settings saved.', AR: 'تم حفظ الإعدادات.' },
  'owner.outreach.providers.title': { EN: 'Providers', AR: 'المزوّدون' },
  'owner.outreach.providers.help': { EN: 'Discovery uses only compliant public sources. LinkedIn needs an approved partner integration or a licensed provider; ArchMind does not scrape it.', AR: 'يستخدم الاكتشاف مصادر عامة ملتزمة فقط. يتطلب LinkedIn تكاملاً معتمداً من شركائه أو مزوّداً مرخّصاً، ولا يقوم ArchMind بجمع بياناته آلياً.' },
  'owner.outreach.providers.email': { EN: 'Email sender', AR: 'مرسل البريد الإلكتروني' },
  'owner.outreach.providers.email_on': { EN: 'Approved emails can be sent.', AR: 'يمكن إرسال الرسائل المعتمدة.' },
  'owner.outreach.providers.email_off': { EN: 'No SMTP sender is configured: emails can be prepared and approved but not sent.', AR: 'لم يُضبط مرسل SMTP: يمكن إعداد الرسائل واعتمادها دون إرسالها.' },
  ...fam('owner.outreach.provider', { 'web-search-organizations': ['Public web search (entities)', 'البحث العام في الويب (الجهات)'], 'official-site-people': ['Official websites', 'المواقع الرسمية'], 'web-search-people': ['Public web search (professionals)', 'البحث العام في الويب (المختصون)'], linkedin: ['LinkedIn', 'لينكدإن (LinkedIn)'] }),
  ...fam('owner.outreach.provider_detail', { 'web-search-organizations': ['Finds Saudi government organisations in public sources; only cited passages are used.', 'يبحث عن الجهات الحكومية السعودية في المصادر العامة، ويستخدم المقاطع المستشهد بها فقط.'], 'official-site-people': ['Reads the entity\'s own leadership, structure and news pages, respecting robots.txt.', 'يقرأ صفحات القيادة والهيكل التنظيمي والأخبار في موقع الجهة نفسها مع احترام ملف robots.txt.'], 'web-search-people': ['Official announcements, conference and speaker pages, publications. Social networks and contact-data brokers are excluded.', 'الإعلانات الرسمية وصفحات المؤتمرات والمتحدثين والمنشورات، مع استبعاد الشبكات الاجتماعية ووسطاء بيانات الاتصال.'], linkedin: ['Not available: needs an approved LinkedIn partner integration or a licensed provider. ArchMind never scrapes LinkedIn or bypasses its access controls.', 'غير متاح: يتطلب تكاملاً معتمداً من شركاء LinkedIn أو مزوّداً مرخّصاً. لا يجمع ArchMind بيانات LinkedIn آلياً ولا يتجاوز ضوابط الوصول فيه.'] }),
  'owner.outreach.suppression.title': { EN: 'Do-not-contact list', AR: 'قائمة عدم التواصل' },
  'owner.outreach.suppression.help': { EN: 'People, addresses, entities and domains that must never be contacted. People and addresses are kept as hashes, so the list survives erasure without keeping personal data.', AR: 'الأشخاص والعناوين والجهات والنطاقات التي يجب عدم التواصل معها أبداً. يُحفظ الأشخاص والعناوين بصيغة مشفّرة، فتبقى القائمة بعد الحذف دون الاحتفاظ ببيانات شخصية.' },
  'owner.outreach.suppression.domain': { EN: 'Domain', AR: 'النطاق' },
  'owner.outreach.suppression.add': { EN: 'Add domain', AR: 'إضافة نطاق' },
  'owner.outreach.suppression.scope': { EN: 'Type', AR: 'النوع' },
  'owner.outreach.suppression.value': { EN: 'Value', AR: 'القيمة' },
  ...fam('owner.outreach.suppression.scope', { EMAIL: ['Email (hash)', 'بريد إلكتروني (مشفّر)'], PERSON: ['Person (hash)', 'شخص (مشفّر)'], ENTITY: ['Entity', 'جهة'], DOMAIN: ['Domain', 'نطاق'] }),
  ...fam('owner.outreach.suppression.source', { OWNER: ['You', 'أنت'], OPT_OUT: ['Recipient opted out', 'طلب المستلم الإيقاف'], ERASURE: ['Erasure request', 'طلب حذف'] }),

  // ── Multi-channel outreach (email + LinkedIn) ─────────────────────────
  // Later keys override the email-only wording above.
  'owner.outreach.dash.funnel_note': { EN: 'Verified = confirmed by evidence or by you. Connected = accepted a LinkedIn connection, which is not engagement. Engaged = used ArchMind after activating.', AR: 'متحقَّق منه = أكّدته الأدلة أو أكّدته أنت. متصل = قبل طلب التواصل على LinkedIn، وهذا لا يُعد تفاعلاً. متفاعل = استخدم ArchMind بعد تفعيل حسابه.' },
  'owner.outreach.dash.channels': { EN: 'Channels', AR: 'القنوات' },
  'owner.outreach.dash.channels_help': { EN: 'LinkedIn steps are prepared by ArchMind and sent by you on LinkedIn; they count as sent only when you record them.', AR: 'يُعدّ ArchMind خطوات LinkedIn وترسلها أنت بنفسك على LinkedIn، ولا تُحتسب مرسلة إلا عندما تسجّلها.' },
  'owner.outreach.dash.li_profiles': { EN: 'LinkedIn profiles known', AR: 'ملفات LinkedIn المعروفة' },
  ...fam('owner.outreach.funnel', { DISCOVERED: ['Discovered', 'مكتشَف'], VERIFIED: ['Verified', 'متحقَّق منه'], CONTACTED: ['Contacted', 'تم التواصل'], CONNECTED: ['Connected on LinkedIn', 'متصل على LinkedIn'], INVITED: ['Invited', 'مدعو'], ACTIVATED: ['Activated', 'مفعَّل'], ENGAGED: ['Engaged', 'متفاعل'] }),
  ...fam('owner.outreach.metric', { li_requests_prepared: ['Connection requests prepared', 'طلبات التواصل المُعدّة'], li_requests_sent: ['Connection requests sent', 'طلبات التواصل المرسلة'], li_connections: ['LinkedIn connections', 'جهات التواصل على LinkedIn'], li_messages_prepared: ['LinkedIn messages prepared', 'رسائل LinkedIn المُعدّة'], li_messages_sent: ['LinkedIn messages sent', 'رسائل LinkedIn المرسلة'], li_replies: ['LinkedIn replies', 'الردود على LinkedIn'] }),
  ...fam('owner.outreach.message_status', { DRAFT: ['Draft', 'مسودة'], READY_FOR_REVIEW: ['Ready for review', 'جاهزة للمراجعة'], APPROVED: ['Approved', 'معتمدة'], SENT: ['Sent', 'مرسلة'], DELIVERED: ['Delivered', 'تم التسليم'], REPLIED: ['Replied', 'تم الرد'], FAILED: ['Not sent', 'لم تُرسل'], CANCELLED: ['Cancelled', 'ملغاة'] }),
  ...fam('owner.outreach.result', { SENT: ['Sent', 'أُرسلت'], APPROVED: ['Approved', 'اعتُمدت'], SKIPPED: ['Skipped', 'تم التخطي'], BLOCKED: ['Blocked', 'محظورة'], FAILED: ['Failed', 'فشلت'], MANUAL_REQUIRED: ['Send it yourself on LinkedIn, then record it', 'أرسلها بنفسك على LinkedIn ثم سجّل ذلك'] }),
  ...fam('owner.outreach.draft_status', { DRAFTED: ['Prepared for review', 'أُعدّت للمراجعة'], EXISTS: ['Already has an email in this campaign', 'لديه رسالة بريد في هذه الحملة بالفعل'], BLOCKED: ['Not prepared', 'لم تُعدّ'] }),
  ...fam('owner.outreach.blocker', {
    LINKEDIN_UNAVAILABLE: ['No LinkedIn profile recorded', 'لم يُسجَّل ملف على LinkedIn'], LINKEDIN_ALREADY_REQUESTED: ['A connection request was already prepared or sent', 'سبق إعداد طلب تواصل أو إرساله'],
    LINKEDIN_MESSAGE_PENDING: ['A LinkedIn message is already waiting in this campaign', 'توجد رسالة LinkedIn بانتظار المراجعة في هذه الحملة'], LINKEDIN_ALREADY_MESSAGED: ['Already messaged on LinkedIn; wait for a reply', 'سبقت مراسلته على LinkedIn، انتظر رده'],
    LINKEDIN_TOO_LONG: ['The text is longer than LinkedIn allows', 'النص أطول مما يسمح به LinkedIn'], CHANNEL_UNAVAILABLE: ['This channel is not available', 'هذه القناة غير متاحة'], MANUAL_REQUIRED: ['Must be sent by you on LinkedIn', 'يجب أن ترسلها بنفسك على LinkedIn'],
  }),
  ...fam('owner.outreach.channel', { EMAIL: ['Email', 'البريد الإلكتروني'], LINKEDIN: ['LinkedIn', 'لينكدإن (LinkedIn)'] }),
  ...fam('owner.outreach.itype', { EMAIL: ['Email', 'رسالة بريد'], CONNECTION_REQUEST: ['Connection request', 'طلب تواصل'], DIRECT_MESSAGE: ['LinkedIn message', 'رسالة LinkedIn'], INVITATION: ['Invitation', 'دعوة'] }),
  ...fam('owner.outreach.li_status', {
    UNKNOWN: ['Not known', 'غير معروفة'], NOT_CONNECTED: ['Not connected', 'غير متصل'], CONNECTION_REQUEST_PREPARED: ['Connection request prepared', 'طلب التواصل مُعدّ'], CONNECTION_REQUEST_SENT: ['Connection request sent', 'أُرسل طلب التواصل'],
    CONNECTED: ['Connected', 'متصل'], MESSAGE_PREPARED: ['Message prepared', 'الرسالة مُعدّة'], MESSAGE_SENT: ['Message sent', 'أُرسلت الرسالة'], REPLIED: ['Replied', 'ردّ'], DO_NOT_CONTACT: ['Do not contact', 'عدم التواصل'],
  }),
  ...fam('owner.outreach.li_source', { SOURCE: ['Profile linked from a public source', 'الملف مرتبط من مصدر عام'], OWNER: ['Profile entered by you', 'الملف أدخلته أنت'] }),
  'owner.outreach.campaigns.interactions': { EN: 'Outreach', AR: 'التواصل' },
  'owner.outreach.campaign.help': { EN: 'Review each message, approve it, then send. Emails are sent by ArchMind with your password; LinkedIn texts are sent by you on LinkedIn and recorded here. Every check (do-not-contact, verification, limits) runs again at that moment.', AR: 'راجع كل رسالة واعتمدها ثم أرسلها. يرسل ArchMind رسائل البريد بعد إدخال كلمة المرور، أما نصوص LinkedIn فترسلها أنت بنفسك على LinkedIn ثم تسجّلها هنا. تُعاد جميع الفحوصات (عدم التواصل، والتحقق، والحدود) في تلك اللحظة.' },
  'owner.outreach.campaign.interactions': { EN: 'Emails and LinkedIn messages', AR: 'رسائل البريد ورسائل LinkedIn' },
  'owner.outreach.campaign.interactions_help': { EN: 'Select messages ready for review to approve them, or approved ones to send. Approved LinkedIn texts are opened from Review and sent by you.', AR: 'حدّد الرسائل الجاهزة للمراجعة لاعتمادها، أو المعتمدة لإرسالها. تُفتح نصوص LinkedIn المعتمدة من زر المراجعة وترسلها أنت بنفسك.' },
  'owner.outreach.col.channel': { EN: 'Channel', AR: 'القناة' },
  'owner.outreach.col.content': { EN: 'Subject / text', AR: 'الموضوع / النص' },
  'owner.outreach.all': { EN: 'All', AR: 'الكل' },
  'owner.outreach.linkedin_profile': { EN: 'LinkedIn profile', AR: 'ملف LinkedIn' },
  'owner.outreach.no_invitation': { EN: 'Without invitation', AR: 'بدون دعوة' },
  'owner.outreach.sent_manually': { EN: 'Sent by you', AR: 'أرسلتها بنفسك' },
  'owner.outreach.send.manual': { EN: '{n} LinkedIn texts must be sent by you: open each one, copy it, send it on LinkedIn and record it.', AR: 'يجب أن ترسل {n} من نصوص LinkedIn بنفسك: افتح كل نص وانسخه وأرسله على LinkedIn ثم سجّل ذلك.' },
  'owner.outreach.send.title': { EN: 'Send {n} approved messages', AR: 'إرسال {n} رسالة معتمدة' },
  'owner.outreach.send.help': { EN: 'Emails that include the invitation get a fresh single-use activation link and the presentation. Messages that no longer pass the checks are not sent; LinkedIn texts are listed for you to send yourself.', AR: 'تحصل رسائل البريد المتضمنة للدعوة على رابط تفعيل جديد يُستخدم مرة واحدة وعلى العرض التقديمي. لا تُرسل الرسائل التي لم تعد تجتاز الفحوصات، وتُعرض نصوص LinkedIn لترسلها بنفسك.' },
  'owner.outreach.send.done': { EN: '{n} messages sent.', AR: 'تم إرسال {n} رسالة.' },
  'owner.outreach.approve.done': { EN: '{n} messages approved.', AR: 'تم اعتماد {n} رسالة.' },
  'owner.outreach.messages': { EN: 'Outreach', AR: 'التواصل' },

  // Editor
  'owner.outreach.editor.help': { EN: 'Edit anything above the line. The footer (activation link when the invitation is included, public-information statement, your contact line and the opt-out link) is added by ArchMind and cannot be removed. Editing an approved message returns it to review.', AR: 'يمكنك تعديل كل ما فوق الخط. أما التذييل (رابط التفعيل عند تضمين الدعوة، وبيان المعلومات العامة، وبيانات التواصل، ورابط إيقاف الرسائل) فيضيفه ArchMind ولا يمكن حذفه. تعديل رسالة معتمدة يعيدها إلى المراجعة.' },
  'owner.outreach.editor.title_connection': { EN: 'Review LinkedIn connection request', AR: 'مراجعة طلب التواصل على LinkedIn' },
  'owner.outreach.editor.title_li_message': { EN: 'Review LinkedIn message', AR: 'مراجعة رسالة LinkedIn' },
  'owner.outreach.editor.li_help': { EN: 'A short, personal text with no links, attachments or invitation. ArchMind has no authorised LinkedIn integration, so it never sends on LinkedIn: approve the text, copy it, open the profile, send it yourself and record what happened.', AR: 'نص قصير وشخصي بلا روابط أو مرفقات أو دعوة. لا يملك ArchMind تكاملاً معتمداً مع LinkedIn، لذا لا يرسل عليه أبداً: اعتمد النص وانسخه وافتح الملف وأرسله بنفسك ثم سجّل ما حدث.' },
  'owner.outreach.editor.include_invitation': { EN: 'Include the ArchMind invitation (single-use activation link)', AR: 'تضمين دعوة ArchMind (رابط تفعيل يُستخدم مرة واحدة)' },
  'owner.outreach.editor.regenerate': { EN: 'Regenerate', AR: 'إعادة الصياغة' },
  'owner.outreach.editor.regenerated': { EN: 'A new text was prepared for review.', AR: 'أُعدّ نص جديد للمراجعة.' },
  'owner.outreach.li.manual_note': { EN: 'Sent by you on LinkedIn: ArchMind does not send LinkedIn messages or connection requests.', AR: 'ترسلها أنت بنفسك على LinkedIn: لا يرسل ArchMind رسائل LinkedIn ولا طلبات التواصل.' },
  'owner.outreach.li.not_connected': { EN: 'You have not recorded a connection with this person. LinkedIn usually only lets you message people you are connected with.', AR: 'لم تسجّل تواصلاً مع هذا الشخص، وعادةً لا يتيح LinkedIn مراسلة إلا من تتواصل معهم.' },
  'owner.outreach.li.note': { EN: 'Connection request note', AR: 'نص طلب التواصل' },
  'owner.outreach.li.message': { EN: 'LinkedIn message', AR: 'رسالة LinkedIn' },
  'owner.outreach.li.count': { EN: '{n} / {max} characters', AR: '{n} / {max} حرفاً' },
  'owner.outreach.li.copy': { EN: 'Copy message', AR: 'نسخ الرسالة' },
  'owner.outreach.li.copied': { EN: 'Copied. Paste it on LinkedIn.', AR: 'تم النسخ. الصقه على LinkedIn.' },
  'owner.outreach.li.copy_failed': { EN: 'Could not copy: select the text and copy it.', AR: 'تعذّر النسخ: حدّد النص وانسخه يدوياً.' },
  'owner.outreach.li.open_profile': { EN: 'Open LinkedIn profile', AR: 'فتح الملف على LinkedIn' },
  'owner.outreach.li.record_help': { EN: 'After you have sent it on LinkedIn, record it here. It is checked again (do-not-contact, verification, daily LinkedIn limit) and counted.', AR: 'بعد إرسالها على LinkedIn سجّل ذلك هنا، فيُعاد فحصها (عدم التواصل، والتحقق، والحد اليومي لـ LinkedIn) وتُحتسب.' },
  'owner.outreach.li.reply_help': { EN: 'Record a reply when the person answers.', AR: 'سجّل الرد عندما يجيب الشخص.' },
  'owner.outreach.li.outcome_note': { EN: 'Note (optional)', AR: 'ملاحظة (اختيارية)' },
  'owner.outreach.li.mark_request_sent': { EN: 'Mark connection request sent', AR: 'تسجيل إرسال طلب التواصل' },
  'owner.outreach.li.mark_message_sent': { EN: 'Mark message sent', AR: 'تسجيل إرسال الرسالة' },
  'owner.outreach.li.mark_not_sent': { EN: 'Mark not sent', AR: 'تسجيل عدم الإرسال' },
  'owner.outreach.li.mark_replied': { EN: 'Mark replied', AR: 'تسجيل الرد' },
  ...fam('owner.outreach.li.recorded', { SENT: ['Recorded as sent.', 'سُجّلت كمرسلة.'], REPLIED: ['Reply recorded.', 'سُجّل الرد.'], FAILED: ['Recorded as not sent.', 'سُجّلت كغير مرسلة.'] }),

  // Prepare outreach
  'owner.outreach.prepare_outreach_help': { EN: 'Prepares texts for review in a campaign; nothing is sent here. LinkedIn texts are short and personal; with both channels the email carries the details and the invitation and does not repeat the LinkedIn text.', AR: 'يُعدّ النصوص للمراجعة ضمن حملة، ولا يُرسل شيء من هنا. نصوص LinkedIn قصيرة وشخصية، وعند اختيار القناتين تحمل رسالة البريد التفاصيل والدعوة دون تكرار نص LinkedIn.' },
  'owner.outreach.strategy': { EN: 'Channels', AR: 'القنوات' },
  'owner.outreach.strategy_help': { EN: 'Use the channel the person can legitimately be reached on. ArchMind never sends more than one connection request, or a second LinkedIn message before a reply.', AR: 'استخدم القناة التي يمكن التواصل مع الشخص عبرها بصورة مشروعة. لا يرسل ArchMind أكثر من طلب تواصل واحد، ولا رسالة LinkedIn ثانية قبل الرد.' },
  ...fam('owner.outreach.strategy', { EMAIL: ['Email only', 'البريد الإلكتروني فقط'], LINKEDIN: ['LinkedIn only', 'LinkedIn فقط'], BOTH: ['Email and LinkedIn', 'البريد الإلكتروني وLinkedIn'] }),
  ...fam('owner.outreach.strategy_detail', { EMAIL: ['detailed email with the invitation and presentation', 'رسالة مفصّلة تتضمن الدعوة والعرض التقديمي'], LINKEDIN: ['a short connection request or message, sent by you', 'طلب تواصل أو رسالة قصيرة ترسلها بنفسك'], BOTH: ['a short LinkedIn introduction and a complementary email', 'تعريف قصير على LinkedIn ورسالة بريد مكمّلة له'] }),
  'owner.outreach.li_type': { EN: 'LinkedIn step', AR: 'خطوة LinkedIn' },
  ...fam('owner.outreach.li_type', { AUTO: ['Connection request unless already connected', 'طلب تواصل ما لم يكن متصلاً بالفعل'], CONNECTION_REQUEST: ['Connection request', 'طلب تواصل'], DIRECT_MESSAGE: ['Message (connected people)', 'رسالة (لمن تتواصل معهم)'] }),
  'owner.outreach.li_manual_short': { EN: 'You send LinkedIn texts yourself; ArchMind prepares them and records what you report.', AR: 'ترسل نصوص LinkedIn بنفسك، ويُعدّها ArchMind ويسجّل ما تبلّغ عنه.' },

  // Prospect outreach panel and timeline
  'owner.outreach.panel.title': { EN: 'Outreach', AR: 'التواصل' },
  'owner.outreach.panel.help': { EN: 'What can be prepared for this person and through which channel. Every action prepares a text for your review; nothing is sent from here.', AR: 'ما يمكن إعداده لهذا الشخص وعبر أي قناة. كل إجراء يُعدّ نصاً لمراجعتك، ولا يُرسل شيء من هنا.' },
  'owner.outreach.panel.no_linkedin': { EN: 'No profile recorded', AR: 'لم يُسجَّل ملف' },
  'owner.outreach.panel.tenant': { EN: 'Workspace', AR: 'مساحة العمل' },
  'owner.outreach.panel.ready': { EN: 'Ready', AR: 'جاهزة' },
  'owner.outreach.panel.enriched': { EN: 'Enriched', AR: 'مُثراة' },
  'owner.outreach.panel.not_enriched': { EN: 'Not enriched yet', AR: 'لم تُثرَ بعد' },
  'owner.outreach.panel.no_tenant': { EN: 'No workspace', AR: 'لا توجد مساحة عمل' },
  'owner.outreach.panel.recommended': { EN: 'Suggested', AR: 'المقترح' },
  'owner.outreach.panel.advisory': { EN: 'This is a suggestion; you decide.', AR: 'هذا اقتراح، والقرار لك.' },
  'owner.outreach.panel.linkedin_blocked': { EN: 'LinkedIn outreach is not possible yet:', AR: 'لا يمكن التواصل عبر LinkedIn بعد:' },
  'owner.outreach.panel.prepare_connection': { EN: 'Prepare LinkedIn connection', AR: 'إعداد طلب تواصل على LinkedIn' },
  'owner.outreach.panel.prepare_li_message': { EN: 'Prepare LinkedIn message', AR: 'إعداد رسالة LinkedIn' },
  'owner.outreach.panel.prepare_email': { EN: 'Prepare email', AR: 'إعداد رسالة بريد' },
  'owner.outreach.panel.prepare_both': { EN: 'Prepare both', AR: 'إعداد الاثنين' },
  'owner.outreach.panel.invite': { EN: 'Invite to ArchMind', AR: 'دعوة إلى ArchMind' },
  'owner.outreach.panel.view_tenant': { EN: 'View workspace', AR: 'عرض مساحة العمل' },
  'owner.outreach.panel.record_li': { EN: 'Record LinkedIn status', AR: 'تسجيل الحالة على LinkedIn' },
  'owner.outreach.panel.record_li_help': { EN: 'ArchMind cannot read LinkedIn. Record what you see there, for example that the person accepted your connection request.', AR: 'لا يستطيع ArchMind قراءة LinkedIn. سجّل ما تراه هناك، مثل قبول الشخص لطلب التواصل.' },
  'owner.outreach.panel.choose': { EN: 'Choose…', AR: 'اختر…' },
  'owner.outreach.panel.record': { EN: 'Record', AR: 'تسجيل' },
  ...fam('owner.outreach.recommend', { LINKEDIN_THEN_EMAIL: ['LinkedIn introduction, then email', 'تعريف على LinkedIn ثم رسالة بريد'], LINKEDIN: ['LinkedIn', 'لينكدإن (LinkedIn)'], EMAIL: ['Email', 'البريد الإلكتروني'], NONE: ['No channel yet', 'لا توجد قناة بعد'] }),
  ...fam('owner.outreach.recommend_reason', {
    LINKEDIN_THEN_EMAIL: ['A professional email and a LinkedIn profile are known: a short LinkedIn introduction first, then the detailed email with the invitation.', 'يتوفر بريد مهني وملف على LinkedIn: تعريف قصير على LinkedIn أولاً، ثم رسالة البريد المفصّلة مع الدعوة.'],
    LINKEDIN: ['Only a LinkedIn profile is known; there is no legitimate professional email.', 'يتوفر ملف على LinkedIn فقط، ولا يوجد بريد مهني مشروع.'],
    EMAIL: ['Only a professional email is known; there is no LinkedIn profile.', 'يتوفر بريد مهني فقط، ولا يوجد ملف على LinkedIn.'],
    NONE: ['Neither a legitimate email nor a LinkedIn profile is known. Add one you have from the person or a public source.', 'لا يتوفر بريد مشروع ولا ملف على LinkedIn. أضف أحدهما إن حصلت عليه من الشخص أو من مصدر عام.'],
  }),
  'owner.outreach.timeline': { EN: 'Timeline', AR: 'السجل الزمني' },
  'owner.outreach.timeline_help': { EN: 'Everything done with this person across channels, from the audit log: discovery, verification, workspace, messages prepared, approved and sent, replies, invitation and activation.', AR: 'كل ما تم مع هذا الشخص عبر القنوات، من سجل التدقيق: الاكتشاف، والتحقق، ومساحة العمل، والرسائل المُعدّة والمعتمدة والمرسلة، والردود، والدعوة والتفعيل.' },
  'owner.outreach.timeline_empty': { EN: 'Nothing recorded yet.', AR: 'لا يوجد شيء مسجّل بعد.' },
  ...fam('owner.outreach.tl', {
    DISCOVERED: ['Discovered from public sources', 'اكتُشف من مصادر عامة'], ADDED: ['Added by you', 'أضفته أنت'], PROSPECT_MODIFIED: ['Details corrected', 'صُحّحت البيانات'], PROSPECT_ENTITY_CHANGED: ['Moved to another entity', 'نُقل إلى جهة أخرى'],
    PROSPECT_VERIFIED: ['Current role confirmed', 'تأكّد الدور الحالي'], PROSPECT_STAGE_SET: ['Stage changed', 'تغيّرت المرحلة'], LINKEDIN_STATUS_RECORDED: ['LinkedIn status recorded', 'سُجّلت الحالة على LinkedIn'], INVITATION_CREATED: ['Invitation prepared', 'أُعدّت الدعوة'],
    INTERACTION_PREPARED: ['Message prepared', 'أُعدّت الرسالة'], INTERACTION_GENERATED: ['Email prepared', 'أُعدّت رسالة البريد'], INTERACTION_MODIFIED: ['Message edited', 'عُدّلت الرسالة'], INTERACTION_REGENERATED: ['Message rewritten', 'أُعيدت صياغة الرسالة'],
    INTERACTION_APPROVED: ['Message approved', 'اعتُمدت الرسالة'], INTERACTION_CANCELLED: ['Message cancelled', 'أُلغيت الرسالة'], INTERACTION_SENT: ['Message sent', 'أُرسلت الرسالة'], INTERACTION_SENT_MANUALLY: ['Sent by you on LinkedIn', 'أرسلتها بنفسك على LinkedIn'],
    INTERACTION_REPLIED: ['Reply received', 'وصل الرد'], INTERACTION_FAILED: ['Not sent', 'لم تُرسل'], DO_NOT_CONTACT_SET: ['Do not contact', 'عدم التواصل'], DO_NOT_CONTACT_CLEARED: ['Do not contact lifted', 'رُفع عدم التواصل'],
    RECIPIENT_OPTED_OUT: ['Opted out by the person', 'أوقف الشخص الرسائل'], TENANT_CREATED: ['Workspace created', 'أُنشئت مساحة العمل'], ENTITY_TENANT_LINKED: ['Workspace linked', 'رُبطت مساحة العمل'], TENANT_ENRICHMENT_STARTED: ['Workspace enrichment started', 'بدأ إثراء مساحة العمل'],
    TENANT_VIEWS_PREPARED: ['EA Views prepared', 'أُعدّت عروض البنية المؤسسية'], WORKSPACE_ENRICHED: ['Workspace enriched', 'أُثريت مساحة العمل'], INVITATION_ACCEPTED: ['Invitation accepted', 'قُبلت الدعوة'], INVITATION_ACTIVATED: ['Account activated', 'فُعّل الحساب'],
  }),

  // Settings
  'owner.outreach.settings.li_daily': { EN: 'LinkedIn texts per day', AR: 'عدد نصوص LinkedIn في اليوم' },
  'owner.outreach.settings.li_daily_help': { EN: 'The most LinkedIn connection requests and messages you can record as sent in 24 hours. Keep it low: outreach here is personal, not mass messaging.', AR: 'الحد الأقصى لطلبات التواصل ورسائل LinkedIn التي يمكن تسجيلها كمرسلة خلال 24 ساعة. أبقِه منخفضاً، فالتواصل هنا شخصي وليس رسائل جماعية.' },
  'owner.outreach.providers.channel': { EN: 'Channel', AR: 'القناة' },
  'owner.outreach.providers.manual': { EN: 'Manual', AR: 'يدوي' },
  'owner.outreach.providers.linkedin_manual': { EN: 'No authorised LinkedIn integration: LinkedIn offers invitations and member messaging only to approved partners. ArchMind prepares the texts; you send them on LinkedIn and record the outcome. It never stores LinkedIn credentials or automates LinkedIn.', AR: 'لا يوجد تكامل معتمد مع LinkedIn، إذ يتيح LinkedIn الدعوات ومراسلة الأعضاء للشركاء المعتمدين فقط. يُعدّ ArchMind النصوص، وترسلها أنت على LinkedIn ثم تسجّل النتيجة. لا يحفظ ArchMind بيانات دخول LinkedIn ولا يؤتمت استخدامه.' },
  ...fam('owner.outreach.capability', { supportsProfileDiscovery: ['Profile discovery', 'اكتشاف الملفات'], supportsConnectionRequest: ['Connection requests', 'طلبات التواصل'], supportsDirectMessaging: ['Direct messages', 'الرسائل المباشرة'], supportsMessageStatus: ['Message status', 'حالة الرسائل'] }),

  // ── ArchMind LinkedIn Company Page ────────────────────────────────────
  'owner.outreach.nav.page': { EN: 'LinkedIn page', AR: 'صفحة LinkedIn' },
  'owner.outreach.page.title': { EN: 'ArchMind LinkedIn page', AR: 'صفحة ArchMind على LinkedIn' },
  'owner.outreach.page.help': { EN: 'The ArchMind company page on LinkedIn. An administrator of the page signs in with LinkedIn once; ArchMind keeps only the access LinkedIn grants (encrypted) and publishes approved posts as the page. It never asks for or stores a LinkedIn password. A page can post, but it cannot message or connect with people.', AR: 'صفحة شركة ArchMind على LinkedIn. يسجّل أحد مسؤولي الصفحة الدخول عبر LinkedIn مرة واحدة، ويحتفظ ArchMind فقط بصلاحية الوصول التي يمنحها LinkedIn (مشفّرة) لينشر المنشورات المعتمدة باسم الصفحة. لا يطلب ArchMind كلمة مرور LinkedIn ولا يحفظها. يمكن للصفحة النشر، لكنها لا تستطيع مراسلة الأشخاص أو التواصل معهم.' },
  ...fam('owner.outreach.page.status', { NOT_CONNECTED: ['Not connected', 'غير مرتبطة'], SELECT_ORGANIZATION: ['Choose the page', 'اختر الصفحة'], CONNECTED: ['Connected', 'مرتبطة'], EXPIRED: ['Connection expired', 'انتهت صلاحية الربط'], ERROR: ['Connection failed', 'تعذّر الربط'] }),
  'owner.outreach.page.mode': { EN: 'Publishing', AR: 'طريقة النشر' },
  ...fam('owner.outreach.page.mode', { API: ['Published by ArchMind as the page', 'ينشرها ArchMind باسم الصفحة'], MANUAL: ['Published by you on LinkedIn', 'تنشرها أنت على LinkedIn'] }),
  'owner.outreach.page.organization': { EN: 'Page', AR: 'الصفحة' },
  'owner.outreach.page.address': { EN: 'Address', AR: 'العنوان' },
  'owner.outreach.page.expires': { EN: 'Access valid until', AR: 'صلاحية الوصول حتى' },
  'owner.outreach.page.not_configured': { EN: 'ArchMind has no approved LinkedIn app yet, so posts are prepared and approved here and you publish them on the page yourself. Direct publishing starts once the LinkedIn app (Community Management API) is approved and its keys are configured.', AR: 'لا يملك ArchMind بعد تطبيقاً معتمداً من LinkedIn، لذا تُعدّ المنشورات وتُعتمد هنا وتنشرها أنت على الصفحة بنفسك. يبدأ النشر المباشر بعد اعتماد تطبيق LinkedIn (واجهة إدارة المجتمع) وضبط مفاتيحه.' },
  'owner.outreach.page.never_password': { EN: 'ArchMind never asks for your LinkedIn password: you sign in on LinkedIn\'s own page.', AR: 'لا يطلب ArchMind كلمة مرور LinkedIn أبداً: تسجّل الدخول في صفحة LinkedIn نفسها.' },
  'owner.outreach.page.choose': { EN: 'You administer several pages. Choose the ArchMind page:', AR: 'أنت مسؤول عن عدة صفحات. اختر صفحة ArchMind:' },
  'owner.outreach.page.use_this': { EN: 'Use this page', AR: 'استخدام هذه الصفحة' },
  'owner.outreach.page.connect': { EN: 'Connect with LinkedIn', AR: 'الربط عبر LinkedIn' },
  'owner.outreach.page.reconnect': { EN: 'Connect again', AR: 'إعادة الربط' },
  'owner.outreach.page.disconnect': { EN: 'Disconnect the page', AR: 'إلغاء ربط الصفحة' },
  'owner.outreach.page.disconnect_help': { EN: 'ArchMind deletes the LinkedIn access it holds. Posts already published stay on LinkedIn.', AR: 'يحذف ArchMind صلاحية الوصول إلى LinkedIn التي يحتفظ بها، وتبقى المنشورات المنشورة على LinkedIn.' },
  'owner.outreach.page.manual_url': { EN: 'Page address (for publishing by hand)', AR: 'عنوان الصفحة (للنشر اليدوي)' },
  'owner.outreach.page.callback_failed': { EN: 'LinkedIn did not complete the sign-in. Try connecting again.', AR: 'لم يُكمل LinkedIn تسجيل الدخول. حاول الربط مرة أخرى.' },
  'owner.outreach.page.connecting': { EN: 'Connecting the LinkedIn page…', AR: 'جارٍ ربط صفحة LinkedIn…' },
  'owner.outreach.page.posts_title': { EN: 'LinkedIn page posts', AR: 'منشورات صفحة LinkedIn' },
  'owner.outreach.page.posts_subtitle': { EN: 'ArchMind\'s public voice: insights, product updates, welcomes and events', AR: 'صوت ArchMind العام: رؤى وتحديثات للمنصة وترحيب بالجهات وفعاليات' },
  'owner.outreach.page.posts_help': { EN: 'Prepare a post, review and approve it, then publish it with your password. Every post is checked: no links except archmindworks.com, no contact details, prices or claims about customers, and an organisation is named only in a welcome post you have its agreement for. At most 3 posts a day.', AR: 'أعدّ المنشور وراجعه واعتمده، ثم انشره بكلمة المرور. يُفحص كل منشور: لا روابط سوى archmindworks.com، ولا بيانات تواصل أو أسعار أو ادعاءات عن العملاء، ولا يُذكر اسم جهة إلا في منشور ترحيب وافقت عليه. بحد أقصى 3 منشورات في اليوم.' },
  'owner.outreach.page.new_post': { EN: 'New post', AR: 'منشور جديد' },
  'owner.outreach.page.new_post_help': { EN: 'Describe what the post is about; ArchMind writes it for your review. A welcome post names an entity only with its agreement, which you record here.', AR: 'صف موضوع المنشور، ويكتبه ArchMind لمراجعتك. لا يذكر منشور الترحيب اسم الجهة إلا بموافقتها التي تسجّلها هنا.' },
  'owner.outreach.page.posts': { EN: 'Posts', AR: 'المنشورات' },
  'owner.outreach.page.no_posts': { EN: 'No posts yet.', AR: 'لا توجد منشورات بعد.' },
  'owner.outreach.page.kind': { EN: 'Type', AR: 'النوع' },
  ...fam('owner.outreach.page.kind', { THOUGHT_LEADERSHIP: ['Insight', 'رؤية مهنية'], PRODUCT_UPDATE: ['Product update', 'تحديث للمنصة'], ENTITY_WELCOME: ['Welcome an entity', 'ترحيب بجهة'], EVENT: ['Event', 'فعالية'] }),
  'owner.outreach.page.topic': { EN: 'What it is about', AR: 'موضوع المنشور' },
  'owner.outreach.page.topic_example': { EN: 'e.g. How capability maps connect strategy to architecture decisions', AR: 'مثال: كيف تربط خرائط القدرات الاستراتيجية بقرارات البنية المؤسسية' },
  ...fam('owner.outreach.page.post_status', { READY_FOR_REVIEW: ['Ready for review', 'جاهز للمراجعة'], APPROVED: ['Approved', 'معتمد'], PUBLISHED: ['Published', 'منشور'], FAILED: ['Not published', 'لم يُنشر'], CANCELLED: ['Cancelled', 'ملغى'] }),
  'owner.outreach.page.view_post': { EN: 'View on LinkedIn', AR: 'عرض على LinkedIn' },
  'owner.outreach.page.choose_entity': { EN: 'Choose an entity with an ArchMind workspace', AR: 'اختر جهة لديها مساحة عمل في ArchMind' },
  'owner.outreach.page.consent': { EN: 'How the entity agreed to be named', AR: 'كيف وافقت الجهة على ذكر اسمها' },
  'owner.outreach.page.consent_example': { EN: 'e.g. Approved by the CIO office by email on 1 October 2026', AR: 'مثال: موافقة مكتب الرئيس التنفيذي للمعلومات بالبريد الإلكتروني في 1 أكتوبر 2026' },
  'owner.outreach.page.consent_help': { EN: 'Naming a government entity publicly needs its agreement. Your note is kept with the post.', AR: 'يتطلب ذكر اسم جهة حكومية علناً موافقتها، وتُحفظ ملاحظتك مع المنشور.' },
  'owner.outreach.page.prepare': { EN: 'Prepare the post', AR: 'إعداد المنشور' },
  'owner.outreach.page.review': { EN: 'Review post', AR: 'مراجعة المنشور' },
  'owner.outreach.page.review_help': { EN: 'Edit the text, then approve it. Editing an approved post returns it to review. Publishing needs your password.', AR: 'عدّل النص ثم اعتمده. تعديل منشور معتمد يعيده إلى المراجعة، ويتطلب النشر كلمة المرور.' },
  'owner.outreach.page.text': { EN: 'Post', AR: 'نص المنشور' },
  'owner.outreach.page.published_on': { EN: 'Published on {date}', AR: 'نُشر في {date}' },
  'owner.outreach.page.manual_required': { EN: 'ArchMind cannot publish on LinkedIn yet (no approved LinkedIn app). Copy the text, publish it on the page, then record it here.', AR: 'لا يستطيع ArchMind النشر على LinkedIn بعد (لا يوجد تطبيق معتمد). انسخ النص وانشره على الصفحة ثم سجّل ذلك هنا.' },
  'owner.outreach.page.manual_not_connected': { EN: 'The page is not connected (or the connection expired). Connect it to publish directly, or copy the text, publish it on the page and record it here.', AR: 'الصفحة غير مرتبطة (أو انتهت صلاحية الربط). اربطها للنشر المباشر، أو انسخ النص وانشره على الصفحة ثم سجّل ذلك هنا.' },
  'owner.outreach.page.copy': { EN: 'Copy text', AR: 'نسخ النص' },
  'owner.outreach.page.copied': { EN: 'Copied. Paste it in a new post on the page.', AR: 'تم النسخ. الصقه في منشور جديد على الصفحة.' },
  'owner.outreach.page.open_page': { EN: 'Open the page', AR: 'فتح الصفحة' },
  'owner.outreach.page.post_link': { EN: 'Link of the published post (optional)', AR: 'رابط المنشور بعد نشره (اختياري)' },
  'owner.outreach.page.mark_published': { EN: 'Mark published', AR: 'تسجيل النشر' },
  'owner.outreach.page.recorded': { EN: 'Recorded as published.', AR: 'سُجّل كمنشور.' },
  'owner.outreach.page.cancel_post': { EN: 'Cancel this post', AR: 'إلغاء هذا المنشور' },
  'owner.outreach.page.cancelled': { EN: 'Post cancelled.', AR: 'أُلغي المنشور.' },
  'owner.outreach.page.publish': { EN: 'Publish', AR: 'نشر' },
  'owner.outreach.page.publish_help': { EN: 'The rules, the entity\'s status and the daily limit are checked again. With a connected page ArchMind publishes it as the page; otherwise you publish it yourself.', AR: 'تُعاد مراجعة القواعد وحالة الجهة والحد اليومي. إذا كانت الصفحة مرتبطة ينشره ArchMind باسمها، وإلا تنشره أنت بنفسك.' },
  'owner.outreach.page.failed': { EN: 'LinkedIn did not accept the post', AR: 'لم يقبل LinkedIn المنشور' },
  'owner.outreach.page.published': { EN: 'Published on the LinkedIn page.', AR: 'نُشر على صفحة LinkedIn.' },
}
