// Meta-Model Studio release control and delete-impact strings (AR/EN), merged into LangContext's TRANSLATIONS.
export const METAMODEL_TRANSLATIONS: Record<string, { EN: string; AR: string }> = {
  // Version bar
  'mm.bar.draft': { EN: 'Editing draft {draft}', AR: 'تحرير المسودة {draft}' },
  'mm.bar.based_on': { EN: 'based on published {published}', AR: 'مبنية على الإصدار المنشور {published}' },
  'mm.bar.first': { EN: 'not published yet', AR: 'لم يُنشر بعد' },
  'mm.bar.changes': { EN: '{n} changes', AR: '{n} تغييرات' },
  'mm.bar.breaking': { EN: '{n} need attention', AR: '{n} تتطلب الانتباه' },
  'mm.bar.review': { EN: 'Review & publish', AR: 'المراجعة والنشر' },
  'mm.bar.published': { EN: 'Viewing published {published} — read-only', AR: 'عرض الإصدار المنشور {published} — للقراءة فقط' },
  'mm.bar.start': { EN: 'Start a new draft', AR: 'بدء مسودة جديدة' },
  'mm.bar.none': { EN: 'No version yet', AR: 'لا يوجد إصدار بعد' },
  'mm.bar.help': {
    EN: 'The published Meta Model is what the Repository, EA Views, Copilot and every other module use. It is never edited in place: changes are made in a draft, reviewed for their impact on your data, and take effect only when the draft is published.',
    AR: 'نموذج البيانات الوصفية المنشور هو ما يستخدمه المستودع وطرق العرض المعمارية والمساعد الذكي وجميع الوحدات الأخرى. لا يُعدَّل مباشرةً: تُجرى التغييرات في مسودة، وتُراجَع آثارها على بياناتك، ولا تسري إلا عند نشر المسودة.',
  },
  'mm.readonly': { EN: 'Start a new draft to change the Meta Model', AR: 'ابدأ مسودة جديدة لتعديل نموذج البيانات الوصفية' },

  // Release panel
  'mm.rel.title': { EN: 'Versions & Release', AR: 'الإصدارات والنشر' },
  'mm.rel.subtitle': { EN: 'Prepare changes in a draft, review their impact, then publish', AR: 'جهّز التغييرات في مسودة، وراجع أثرها، ثم انشرها' },
  'mm.rel.help': {
    EN: 'Lifecycle: Draft (being edited) → Published (in use by the platform; one at a time) → Deprecated (an earlier published version, kept as history). Only one draft can be open. Discarding a draft deletes it and its changes; published and deprecated versions are never deleted.',
    AR: 'دورة الحياة: مسودة (قيد التحرير) ← منشور (مستخدم في المنصة؛ إصدار واحد فقط) ← مُهمَل (إصدار منشور سابق يُحفظ للسجل). يمكن فتح مسودة واحدة فقط. حذف المسودة يحذفها مع تغييراتها؛ أما الإصدارات المنشورة والمُهمَلة فلا تُحذف أبدًا.',
  },
  'mm.rel.step.draft': { EN: 'Draft', AR: 'مسودة' },
  'mm.rel.step.review': { EN: 'Review impact', AR: 'مراجعة الأثر' },
  'mm.rel.step.publish': { EN: 'Publish', AR: 'النشر' },
  'mm.rel.no_draft': { EN: 'No draft is open. The published version is in use and read-only.', AR: 'لا توجد مسودة مفتوحة. الإصدار المنشور قيد الاستخدام وللقراءة فقط.' },
  'mm.rel.new_title': { EN: 'Start a new draft', AR: 'بدء مسودة جديدة' },
  'mm.rel.new_hint': { EN: 'The draft starts as a copy of the published version. Nothing changes for users until you publish it.', AR: 'تبدأ المسودة نسخةً من الإصدار المنشور. لا يتغير شيء للمستخدمين حتى تنشرها.' },
  'mm.rel.version_name': { EN: 'Version name', AR: 'اسم الإصدار' },
  'mm.rel.description': { EN: 'What this version changes', AR: 'ما الذي يغيّره هذا الإصدار' },
  'mm.rel.create': { EN: 'Create draft', AR: 'إنشاء المسودة' },
  'mm.rel.creating': { EN: 'Creating…', AR: 'جارٍ الإنشاء…' },
  'mm.rel.draft_title': { EN: 'Draft {draft}', AR: 'المسودة {draft}' },
  'mm.rel.compared': { EN: 'Compared with published {published}', AR: 'مقارنةً بالإصدار المنشور {published}' },
  'mm.rel.compared_first': { EN: 'First publish: everything in the draft is new', AR: 'النشر الأول: كل ما في المسودة جديد' },
  'mm.rel.loading': { EN: 'Analysing changes…', AR: 'جارٍ تحليل التغييرات…' },
  'mm.rel.no_changes': { EN: 'The draft has no changes yet.', AR: 'لا تحتوي المسودة على تغييرات بعد.' },
  'mm.rel.total': { EN: 'Changes', AR: 'التغييرات' },
  'mm.rel.sev.BREAKING': { EN: 'Breaking', AR: 'تغيير جذري' },
  'mm.rel.sev.POTENTIALLY_BREAKING': { EN: 'Needs attention', AR: 'يتطلب الانتباه' },
  'mm.rel.sev.NON_BREAKING': { EN: 'Safe', AR: 'آمن' },
  'mm.rel.kind.DOMAIN': { EN: 'Domain', AR: 'مجال' },
  'mm.rel.kind.OBJECT_TYPE': { EN: 'Object type', AR: 'نوع كائن' },
  'mm.rel.kind.ATTRIBUTE': { EN: 'Attribute', AR: 'سمة' },
  'mm.rel.kind.RELATIONSHIP': { EN: 'Relationship', AR: 'علاقة' },
  'mm.rel.action.ADDED': { EN: 'Added', AR: 'مُضاف' },
  'mm.rel.action.REMOVED': { EN: 'Removed', AR: 'محذوف' },
  'mm.rel.action.MODIFIED': { EN: 'Changed', AR: 'مُعدَّل' },
  'mm.rel.filter.all': { EN: 'All changes', AR: 'جميع التغييرات' },
  'mm.rel.filter.attention': { EN: 'Needing attention', AR: 'ما يتطلب الانتباه' },
  'mm.rel.fields': { EN: 'Changed: {fields}', AR: 'تم تغيير: {fields}' },
  'mm.rel.objects': { EN: '{n} objects', AR: '{n} كائنات' },
  'mm.rel.links': { EN: '{n} links', AR: '{n} روابط' },
  'mm.rel.values': { EN: '{n} values', AR: '{n} قيم' },
  'mm.rel.views': { EN: 'Saved views', AR: 'طرق العرض المحفوظة' },
  'mm.rel.refs': { EN: 'Reference architectures', AR: 'البنى المرجعية' },
  'mm.rel.ack': { EN: 'I have reviewed the impact and want to publish these changes', AR: 'راجعت الأثر وأرغب في نشر هذه التغييرات' },
  'mm.rel.publish': { EN: 'Publish draft', AR: 'نشر المسودة' },
  'mm.rel.publishing': { EN: 'Publishing…', AR: 'جارٍ النشر…' },
  'mm.rel.published_ok': { EN: 'Version {version} is published and now in use.', AR: 'تم نشر الإصدار {version} وأصبح قيد الاستخدام.' },
  'mm.rel.discard': { EN: 'Discard draft', AR: 'حذف المسودة' },
  'mm.rel.discard_confirm': { EN: 'Discard draft {draft} and all its changes? The published version is not affected. This cannot be undone.', AR: 'هل تريد حذف المسودة {draft} وجميع تغييراتها؟ لن يتأثر الإصدار المنشور. لا يمكن التراجع عن ذلك.' },
  'mm.rel.discarded': { EN: 'Draft {draft} was discarded.', AR: 'تم حذف المسودة {draft}.' },
  'mm.rel.history': { EN: 'Version history', AR: 'سجل الإصدارات' },
  'mm.rel.status.DRAFT': { EN: 'Draft', AR: 'مسودة' },
  'mm.rel.status.PUBLISHED': { EN: 'Published', AR: 'منشور' },
  'mm.rel.status.DEPRECATED': { EN: 'Deprecated', AR: 'مُهمَل' },
  'mm.rel.status.ARCHIVED': { EN: 'Archived', AR: 'مؤرشف' },
  'mm.rel.counts': { EN: '{d} domains · {t} types · {r} relationships', AR: '{d} مجالات · {t} أنواع · {r} علاقات' },
  'mm.rel.published_on': { EN: 'Published {date}', AR: 'نُشر في {date}' },
  'mm.rel.admin_only': { EN: 'Only tenant administrators can create, publish or discard versions.', AR: 'يمكن لمسؤولي الجهة فقط إنشاء الإصدارات أو نشرها أو حذفها.' },

  // Delete impact dialog
  'mm.del.title': { EN: 'Delete {name}?', AR: 'حذف {name}؟' },
  'mm.del.loading': { EN: 'Tracing where it is used…', AR: 'جارٍ تتبّع مواضع الاستخدام…' },
  'mm.del.help': {
    EN: 'Deleting removes the item from the draft only. Your data changes when the draft is published; this shows what that would affect.',
    AR: 'يحذف الإجراء العنصر من المسودة فقط. تتغير بياناتك عند نشر المسودة؛ ويعرض هذا ما سيتأثر بذلك.',
  },
  'mm.del.blocked': { EN: 'Cannot be deleted', AR: 'لا يمكن الحذف' },
  'mm.del.consequences': { EN: 'What happens when the draft is published', AR: 'ما سيحدث عند نشر المسودة' },
  'mm.del.sample_objects': { EN: 'Repository objects', AR: 'كائنات المستودع' },
  'mm.del.sample_links': { EN: 'Repository links', AR: 'روابط المستودع' },
  'mm.del.also_removed': { EN: 'Relationships removed with it', AR: 'علاقات تُحذف معه' },
  'mm.del.types_in_domain': { EN: 'Object types in this domain', AR: 'أنواع الكائنات في هذا المجال' },
  'mm.del.and_more': { EN: '…and {n} more', AR: '…و{n} أخرى' },
  'mm.del.confirm': { EN: 'Delete from draft', AR: 'الحذف من المسودة' },
  'mm.del.deleting': { EN: 'Deleting…', AR: 'جارٍ الحذف…' },
  'mm.del.cancel': { EN: 'Cancel', AR: 'إلغاء' },
  'mm.del.close': { EN: 'Close', AR: 'إغلاق' },
  'mm.del.ack': { EN: 'I understand the impact', AR: 'أدرك هذا الأثر' },
  'mm.del.button': { EN: 'Delete', AR: 'حذف' },
  'mm.del.attributes': { EN: '{n} attributes', AR: '{n} سمات' },
}
